FORM: declare.h File Reference
declare.h File Reference
Macros
#define MaX(x, y) ((x) > (y) ? (x): (y))
#define MiN(x, y) ((x) < (y) ? (x): (y))
#define ABS(x) ((x) < 0 ? -(x): (x))
#define SGN(x) ((x) > 0 ? 1 : (x) < 0 ? -1 : 0)
#define REDLENG(x) ((((x)<0)?((x)+1):((x)-1))/2)
#define INCLENG(x) (((x)<0)?(((x)*2)-1):(((x)*2)+1))
#define GETCOEF(x, y) x += *x;y = x[-1];x -= ABS(y);y=REDLENG(y)
#define GETSTOP(x, y) y=x+(*x)-1;y -= ABS(*y)-1
#define StuffAdd(x, y) (((x)<0?-1:1)*(y)+((y)<0?-1:1)*(x))
#define EXCHN(t1, t2, n) { WORD a,i; for(i=0;i<n;i++){a=t1[i];t1[i]=t2[i];t2[i]=a;} }
#define EXCH(x, y) { WORD a = (x); (x) = (y); (y) = a; }
#define TOKENTOLINE(x, y)
#define UngetFromStream(stream, c) ((stream)->nextchar[(stream)->isnextchar++]=c)
#define AddLineFeed(s, n) { (s)[(n)++] = LINEFEED; }
#define TryRecover(x) Terminate(-1)
#define UngetChar(c) { pushbackchar = c; }
#define ParseNumber(x, s) {(x)=0;while(*(s)>='0'&&*(s)<='9')(x)=10*(x)+*(s)++ -'0';}
#define ParseSign(sgn, s)
#define ParseSignedNumber(x, s)
#define NCOPY(s, t, n) { while ((n)-- > 0) { *s++ = *t++; } }
#define NCOPYI(s, t, n) { while ((n)-- > 0) { *s++ = *t++; } }
#define NCOPYB(s, t, n) { while ((n)-- > 0) { *s++ = *t++; } }
#define NCOPYI32(s, t, n) { while ((n)-- > 0) { *s++ = *t++; } }
#define WCOPY(s, t, n) { int nn=n; WORD *ss=(WORD *)s, *tt=(WORD *)t; while ((nn)-- > 0) { *ss++ = *tt++; } }
#define NeedNumber(x, s, err)
#define SKIPBLANKS(s) { while (*(s) == ' ' || *(s) == '\t') (s)++; }
#define FLUSHCONSOLE if (AP.InOutBuf > 0) CharOut(LINEFEED)
#define SKIPBRA1(s)
#define SKIPBRA2(s)
#define SKIPBRA3(s)
#define SKIPBRA4(s)
#define SKIPBRA5(s)
#define CYCLE1(t, a, i) {t iX=*a; WORD jX; for(jX=1;jX<i;jX++)a[jX-1]=a[jX]; a[i-1]=iX;}
#define AddToCB(c, wx)
#define EXCHINOUT
#define BACKINOUT
#define CopyArg(to, from)
#define FILLARG(w)
#define COPYARG(w, t)
#define ZEROARG(w)
#define FILLFUN(w)
#define COPYFUN(w, t)
#define COPYFUN3(w, t)
#define FILLFUN3(w)
#define FILLSUB(w)
#define COPYSUB(w, ww)
#define FILLEXPR(w)
#define NEXTARG(x) if(*x>0) x += *x; else if(*x <= -FUNCTION)x++; else x += 2;
#define COPY1ARG(s1, t1)
#define ZeroFillRange(w, begin, end)
#define TABLESIZE(a, b) (((WORD)sizeof(a))/((WORD)sizeof(b)))
#define WORDDIF(x, y) (WORD)(x-y)
#define wsizeof(a) ((WORD)sizeof(a))
#define VARNAME(type, num) (AC.varnames->namebuffer+type[num].name)
#define DOLLARNAME(type, num) (AC.dollarnames->namebuffer+type[num].name)
#define EXPRNAME(num) (AC.exprnames->namebuffer+Expressions[num].name)
#define PREV(x) prevorder?prevorder:x
#define Terminate(x) do { TerminateImpl(x, __FILE__, __LINE__, __FUNCTION__); } while(0)
#define SETERROR(x) { Terminate(-1); return(-1); }
#define DUMMYUSE(x) (void)(x);
#define ADDPOS(pp, x) (pp).p1 = ((pp).p1+(LONG)(x))
#define SETBASELENGTH(ss, x) (ss).p1 = (LONG)(x)
#define SETBASEPOSITION(pp, x) (pp).p1 = (LONG)(x)
#define ISEQUALPOSINC(pp1, pp2, x) ((pp1).p1 == ((pp2).p1+(LONG)(x)))
#define ISGEPOSINC(pp1, pp2, x) ((pp1).p1 >= ((pp2).p1+(LONG)(x)))
#define DIVPOS(pp, n) ((pp).p1/(LONG)(n))
#define MULPOS(pp, n) (pp).p1 *= (LONG)(n)
#define DIFPOS(ss, pp1, pp2) (ss).p1 = ((pp1).p1-(pp2).p1)
#define DIFBASE(pp1, pp2) ((pp1).p1-(pp2).p1)
#define ADD2POS(pp1, pp2) (pp1).p1 += (pp2).p1
#define PUTZERO(pp) (pp).p1 = 0
#define BASEPOSITION(pp) ((pp).p1)
#define SETSTARTPOS(pp) (pp).p1 = -2
#define NOTSTARTPOS(pp) ((pp).p1 > -2)
#define ISMINPOS(pp) ((pp).p1 == -1)
#define ISEQUALPOS(pp1, pp2) ((pp1).p1 == (pp2).p1)
#define ISNOTEQUALPOS(pp1, pp2) ((pp1).p1 != (pp2).p1)
#define ISLESSPOS(pp1, pp2) ((pp1).p1 < (pp2).p1)
#define ISGEPOS(pp1, pp2) ((pp1).p1 >= (pp2).p1)
#define ISNOTZEROPOS(pp) ((pp).p1 != 0)
#define ISZEROPOS(pp) ((pp).p1 == 0)
#define ISPOSPOS(pp) ((pp).p1 > 0)
#define ISNEGPOS(pp) ((pp).p1 < 0)
#define TOLONG(x) ((LONG)(x))
#define Add2Com(x) { WORD cod[2]; cod[0] = x; cod[1] = 2; AddNtoL(2,cod); }
#define Add3Com(x1, x2) { WORD cod[3]; cod[0] = x1; cod[1] = 3; cod[2] = x2; AddNtoL(3,cod); }
#define Add4Com(x1, x2, x3)
#define Add5Com(x1, x2, x3, x4)
#define WantAddPointers(x)
#define WantAddLongs(x)
#define WantAddPositions(x)
#define FORM_INLINE inline
#define MEMORYMACROS
#define TermMalloc(x) ((AT.TermMemTop <= 0) ? TermMallocAddMemory(BHEAD0), AT.TermMemHeap[--AT.TermMemTop]: AT.TermMemHeap[--AT.TermMemTop])
#define NumberMalloc(x) ((AT.NumberMemTop <= 0) ? NumberMallocAddMemory(BHEAD0), AT.NumberMemHeap[--AT.NumberMemTop]: AT.NumberMemHeap[--AT.NumberMemTop])
#define CacheNumberMalloc(x) ((AT.CacheNumberMemTop <= 0) ? CacheNumberMallocAddMemory(BHEAD0), AT.CacheNumberMemHeap[--AT.CacheNumberMemTop]: AT.CacheNumberMemHeap[--AT.CacheNumberMemTop])
#define TermFree(TermMem, x) AT.TermMemHeap[AT.TermMemTop++] = (WORD *)(TermMem)
#define NumberFree(NumberMem, x) AT.NumberMemHeap[AT.NumberMemTop++] = (UWORD *)(NumberMem)
#define CacheNumberFree(NumberMem, x) AT.CacheNumberMemHeap[AT.CacheNumberMemTop++] = (UWORD *)(NumberMem)
#define NestingChecksum() (AC.IfLevel + AC.RepLevel + AC.arglevel + AC.insidelevel + AC.termlevel + AC.inexprlevel + AC.dolooplevel +AC.SwitchLevel)
#define MesNesting() MesPrint("&Illegal nesting of if, repeat, argument, inside, term, inexpression and do")
#define MarkPolyRatFunDirty(T)
#define PUSHPREASSIGNLEVEL
#define POPPREASSIGNLEVEL
#define EXTERNLOCK(x)
#define INILOCK(x)
#define LOCK(x)
#define UNLOCK(x)
#define EXTERNRWLOCK(x)
#define INIRWLOCK(x)
#define RWLOCKR(x)
#define RWLOCKW(x)
#define UNRWLOCK(x)
#define MLOCK(x)
#define MUNLOCK(x)
#define GETIDENTITY
#define GETBIDENTITY
#define M_alloc(x) malloc((size_t)(x))
#define CompareTerms ((COMPARE)AR.CompareRoutine)
#define FiniShuffle AN.SHvar.finishuf
#define DoShtuffle ((DO_UFFLE)AN.SHvar.do_uffle)
Typedefs
typedef int(* WRITEBUFTOEXTCHANNEL) (char *, size_t)
typedef int(* GETCFROMEXTCHANNEL) (VOID)
typedef int(* SETTERMINATORFOREXTERNALCHANNEL) (char *)
typedef int(* SETKILLMODEFOREXTERNALCHANNEL) (int, int)
typedef LONG(* WRITEFILE) (int, UBYTE *, LONG)
typedef WORD(* GETTERM) (PHEAD WORD *)
Functions
VOID TELLFILE (int, POSITION *)
VOID StartVariables (VOID)
VOID setSignalHandlers (VOID)
UBYTE * CodeToLine (WORD, UBYTE *)
UBYTE * AddArrayIndex (WORD, UBYTE *)
INDEXENTRY * FindInIndex (WORD, FILEDATA *, WORD, WORD)
INDEXENTRY * NextFileIndex (POSITION *)
WORD * PasteTerm (PHEAD WORD, WORD *, WORD *, WORD, WORD)
UBYTE * StrCopy (UBYTE *, UBYTE *)
UBYTE * WrtPower (UBYTE *, WORD)
WORD AccumGCD (PHEAD UWORD *, WORD *, UWORD *, WORD)
VOID AddArgs (PHEAD WORD *, WORD *, WORD *)
WORD AddCoef (PHEAD WORD **, WORD **)
WORD AddLong (UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *)
WORD AddPLon (UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *)
WORD AddPoly (PHEAD WORD **, WORD **)
WORD AddRat (PHEAD UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *)
VOID AddToLine (UBYTE *)
WORD AddWild (PHEAD WORD, WORD, WORD)
WORD BigLong (UWORD *, WORD, UWORD *, WORD)
WORD BinomGen (PHEAD WORD *, WORD, WORD **, WORD, WORD, WORD, WORD, WORD, UWORD *, WORD)
WORD CheckWild (PHEAD WORD, WORD, WORD, WORD *)
WORD Chisholm (PHEAD WORD *, WORD)
WORD CleanExpr (WORD)
VOID CleanUp (WORD)
VOID ClearWild (PHEAD0)
WORD CompareFunctions (WORD *, WORD *)
WORD Commute (WORD *, WORD *)
WORD DetCommu (WORD *)
WORD DoesCommu (WORD *)
int CompArg (WORD *, WORD *)
WORD CompCoef (WORD *, WORD *)
WORD CompGroup (PHEAD WORD, WORD **, WORD *, WORD *, WORD)
WORD Compare1 (PHEAD WORD *, WORD *, WORD)
WORD CountDo (WORD *, WORD *)
WORD CountFun (WORD *, WORD *)
WORD DimensionSubterm (WORD *)
WORD DimensionTerm (WORD *)
WORD DimensionExpression (PHEAD WORD *)
WORD Deferred (PHEAD WORD *, WORD)
WORD DeleteStore (WORD)
WORD DetCurDum (PHEAD WORD *)
VOID DetVars (WORD *, WORD)
WORD Distribute (DISTRIBUTE *, WORD)
WORD DivLong (UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *, UWORD *, WORD *)
WORD DivRat (PHEAD UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *)
WORD Divvy (PHEAD UWORD *, WORD *, UWORD *, WORD)
WORD DoDelta (WORD *)
WORD DoDelta3 (PHEAD WORD *, WORD)
WORD TestPartitions (WORD *, PARTI *)
WORD DoPartitions (PHEAD WORD *, WORD)
int CoCanonicalize (UBYTE *)
int DoCanonicalize (PHEAD WORD *, WORD *)
WORD GenTopologies (PHEAD WORD *, WORD)
WORD GenDiagrams (PHEAD WORD *, WORD)
int DoTopologyCanonicalize (PHEAD WORD *, WORD, WORD, WORD *)
int DoShattering (PHEAD WORD *, WORD *, WORD *, WORD)
WORD GenerateTopologies (PHEAD WORD, WORD, WORD, WORD)
WORD DoTableExpansion (WORD *, WORD)
WORD DoDistrib (PHEAD WORD *, WORD)
WORD DoShuffle (WORD *, WORD, WORD, WORD)
WORD DoPermutations (PHEAD WORD *, WORD)
int Shuffle (WORD *, WORD *, WORD *)
int FinishShuffle (WORD *)
WORD DoStuffle (WORD *, WORD, WORD, WORD)
int Stuffle (WORD *, WORD *, WORD *)
int FinishStuffle (WORD *)
WORD * StuffRootAdd (WORD *, WORD *, WORD *)
WORD TestUse (WORD *, WORD)
DBASE * FindTB (UBYTE *)
int CheckTableDeclarations (DBASE *)
WORD Apply (WORD *, WORD)
int ApplyExec (WORD *, int, WORD)
WORD ApplyReset (WORD)
WORD TableReset (VOID)
VOID ReWorkT (WORD *, WORD *, WORD)
WORD GetIfDollarNum (WORD *, WORD *)
int FindVar (WORD *, WORD *)
WORD DoIfStatement (PHEAD WORD *, WORD *)
WORD DoOnePow (PHEAD WORD *, WORD, WORD, WORD *, WORD *, WORD, WORD *)
void DoRevert (WORD *, WORD *)
WORD DoSumF1 (PHEAD WORD *, WORD *, WORD, WORD)
WORD DoSumF2 (PHEAD WORD *, WORD *, WORD, WORD)
WORD DoTheta (PHEAD WORD *)
LONG EndSort (PHEAD WORD *, int)
WORD EntVar (WORD, UBYTE *, WORD, WORD, WORD, WORD)
WORD EpfCon (PHEAD WORD *, WORD *, WORD, WORD)
WORD EpfFind (PHEAD WORD *, WORD *)
WORD EpfGen (WORD, WORD *, WORD *, WORD *, WORD)
WORD EqualArg (WORD *, WORD, WORD)
WORD Evaluate (UBYTE **)
int Factorial (PHEAD WORD, UWORD *, WORD *)
int Bernoulli (WORD, UWORD *, WORD *)
int FactorIn (PHEAD WORD *, WORD)
int FactorInExpr (PHEAD WORD *, WORD)
WORD FindAll (PHEAD WORD *, WORD *, WORD, WORD *)
WORD FindMulti (PHEAD WORD *, WORD *)
WORD FindOnce (PHEAD WORD *, WORD *)
WORD FindOnly (PHEAD WORD *, WORD *)
WORD FindRest (PHEAD WORD *, WORD *)
WORD FindSpecial (WORD *)
WORD FindrNumber (WORD, VARRENUM *)
VOID FiniLine (VOID)
WORD FiniTerm (PHEAD WORD *, WORD *, WORD *, WORD, WORD)
WORD FlushOut (POSITION *, FILEHANDLE *, int)
VOID FunLevel (PHEAD WORD *)
VOID AdjustRenumScratch (PHEAD0)
VOID GarbHand (VOID)
WORD GcdLong (PHEAD UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *)
WORD LcmLong (PHEAD UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *)
VOID GCD (UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *)
ULONG GCD2 (ULONG, ULONG)
WORD Generator (PHEAD WORD *, WORD)
WORD GetBinom (UWORD *, WORD *, WORD, WORD)
WORD GetFromStore (WORD *, POSITION *, RENUMBER, WORD *, WORD)
WORD GetLong (UBYTE *, UWORD *, WORD *)
WORD GetMoreTerms (WORD *)
WORD GetMoreFromMem (WORD *, WORD **)
WORD GetOneTerm (PHEAD WORD *, FILEHANDLE *, POSITION *, int)
RENUMBER GetTable (WORD, POSITION *, WORD)
WORD GetTerm (PHEAD WORD *)
WORD Glue (PHEAD WORD *, WORD *, WORD *, WORD)
WORD InFunction (PHEAD WORD *, WORD *)
VOID IniLine (WORD)
WORD IniVars (VOID)
VOID Initialize (VOID)
WORD InsertTerm (PHEAD WORD *, WORD, WORD, WORD *, WORD *, WORD)
VOID LongToLine (UWORD *, WORD)
WORD MakeDirty (WORD *, WORD *, WORD)
VOID MarkDirty (WORD *, WORD)
VOID PolyFunDirty (PHEAD WORD *)
VOID PolyFunClean (PHEAD WORD *)
WORD MakeModTable (VOID)
WORD MatchE (PHEAD WORD *, WORD *, WORD *, WORD)
int MatchCy (PHEAD WORD *, WORD *, WORD *, WORD)
int FunMatchCy (PHEAD WORD *, WORD *, WORD *, WORD)
int FunMatchSy (PHEAD WORD *, WORD *, WORD *, WORD)
int MatchArgument (PHEAD WORD *, WORD *)
WORD MatchFunction (PHEAD WORD *, WORD *, WORD *)
WORD MergePatches (WORD)
WORD MesCerr (char *, UBYTE *)
WORD MesComp (char *, UBYTE *, UBYTE *)
WORD Modulus (WORD *)
VOID MoveDummies (PHEAD WORD *, WORD)
WORD MulLong (UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *)
WORD MulRat (PHEAD UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *)
WORD Mully (PHEAD UWORD *, WORD *, UWORD *, WORD)
WORD MultDo (PHEAD WORD *, WORD *)
WORD NewSort (PHEAD0)
WORD ExtraSymbol (WORD, WORD, WORD, WORD *, WORD *)
WORD Normalize (PHEAD WORD *)
WORD BracketNormalize (PHEAD WORD *)
VOID DropCoefficient (PHEAD WORD *)
VOID DropSymbols (PHEAD WORD *)
int PutInside (PHEAD WORD *, WORD *)
WORD OpenTemp (VOID)
VOID Pack (UWORD *, WORD *, UWORD *, WORD)
LONG PasteFile (PHEAD WORD, WORD *, POSITION *, WORD **, RENUMBER, WORD *, WORD)
WORD Permute (PERM *, WORD)
WORD PermuteP (PERMP *, WORD)
WORD PolyFunMul (PHEAD WORD *)
WORD PopVariables (VOID)
WORD PrepPoly (PHEAD WORD *, WORD)
WORD Processor (VOID)
WORD Product (UWORD *, WORD *, WORD)
VOID PrtLong (UWORD *, WORD, UBYTE *)
VOID PrtTerms (VOID)
void PrintDeprecation (const char *, const char *)
VOID PrintRunningTime (VOID)
LONG GetRunningTime (VOID)
WORD PutBracket (PHEAD WORD *)
LONG PutIn (FILEHANDLE *, POSITION *, WORD *, WORD **, int)
WORD PutInStore (INDEXENTRY *, WORD)
WORD PutOut (PHEAD WORD *, POSITION *, FILEHANDLE *, WORD)
UWORD Quotient (UWORD *, WORD *, WORD)
WORD RaisPow (PHEAD UWORD *, WORD *, UWORD)
VOID RaisPowCached (PHEAD WORD, WORD, UWORD **, WORD *)
WORD RaisPowMod (WORD, WORD, WORD)
int NormalModulus (UWORD *, WORD *)
int MakeInverses (VOID)
int GetModInverses (WORD, WORD, WORD *, WORD *)
int GetLongModInverses (PHEAD UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *, UWORD *, WORD *)
VOID RatToLine (UWORD *, WORD)
WORD RatioFind (PHEAD WORD *, WORD *)
WORD RatioGen (PHEAD WORD *, WORD *, WORD, WORD)
WORD ReNumber (PHEAD WORD *)
WORD ReadSnum (UBYTE **)
WORD Remain10 (UWORD *, WORD *)
WORD Remain4 (UWORD *, WORD *)
WORD ResetScratch (VOID)
WORD ResolveSet (PHEAD WORD *, WORD *, WORD *)
WORD RevertScratch (VOID)
WORD ScanFunctions (PHEAD WORD *, WORD *, WORD)
VOID SeekScratch (FILEHANDLE *, POSITION *)
VOID SetEndScratch (FILEHANDLE *, POSITION *)
VOID SetEndHScratch (FILEHANDLE *, POSITION *)
WORD SetFileIndex (VOID)
WORD Sflush (FILEHANDLE *)
WORD Simplify (PHEAD UWORD *, WORD *, UWORD *, WORD *)
WORD SortWild (WORD *, WORD)
FILE * LocateBase (char **, char **, char *)
LONG SplitMerge (PHEAD WORD **, LONG)
WORD StoreTerm (PHEAD WORD *)
VOID SubPLon (UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *)
VOID Substitute (PHEAD WORD *, WORD *, WORD)
WORD SymFind (PHEAD WORD *, WORD *)
WORD SymGen (PHEAD WORD *, WORD *, WORD, WORD)
WORD Symmetrize (PHEAD WORD *, WORD *, WORD, WORD, WORD)
int FullSymmetrize (PHEAD WORD *, int)
WORD TakeModulus (UWORD *, WORD *, UWORD *, WORD, WORD)
WORD TakeNormalModulus (UWORD *, WORD *, UWORD *, WORD, WORD)
VOID TalToLine (UWORD)
WORD TenVec (PHEAD WORD *, WORD *, WORD, WORD)
WORD TenVecFind (PHEAD WORD *, WORD *)
WORD TermRenumber (WORD *, RENUMBER, WORD)
VOID TestDrop (VOID)
VOID PutInVflags (WORD)
WORD TestMatch (PHEAD WORD *, WORD *)
WORD TestSub (PHEAD WORD *, WORD)
LONG TimeCPU (WORD)
LONG TimeChildren (WORD)
LONG TimeWallClock (WORD)
LONG Timer (int)
int GetTimerInfo (LONG **, LONG **)
void WriteTimerInfo (LONG *, LONG *)
LONG GetWorkerTimes (VOID)
WORD ToStorage (EXPRESSIONS, POSITION *)
VOID TokenToLine (UBYTE *)
WORD Trace4 (PHEAD WORD *, WORD *, WORD, WORD)
WORD Trace4Gen (PHEAD TRACES *, WORD)
WORD Trace4no (WORD, WORD *, TRACES *)
WORD TraceFind (PHEAD WORD *, WORD *)
WORD TraceN (PHEAD WORD *, WORD *, WORD, WORD)
WORD TraceNgen (PHEAD TRACES *, WORD)
WORD TraceNno (WORD, WORD *, TRACES *)
WORD Traces (PHEAD WORD *, WORD *, WORD, WORD)
WORD Trick (WORD *, TRACES *)
WORD TryDo (PHEAD WORD *, WORD *, WORD)
VOID UnPack (UWORD *, WORD, WORD *, WORD *)
WORD VarStore (UBYTE *, WORD, WORD, WORD)
WORD WildFill (PHEAD WORD *, WORD *, WORD *)
WORD WriteAll (VOID)
WORD WriteOne (UBYTE *, int, int, WORD)
VOID WriteArgument (WORD *)
WORD WriteExpression (WORD *, LONG)
WORD WriteInnerTerm (WORD *, WORD)
VOID WriteLists (VOID)
VOID WriteSetup (VOID)
VOID WriteStats (POSITION *, WORD, WORD)
WORD WriteSubTerm (WORD *, WORD)
WORD WriteTerm (WORD *, WORD *, WORD, WORD, WORD)
WORD execarg (PHEAD WORD *, WORD)
WORD execterm (PHEAD WORD *, WORD)
VOID SpecialCleanup (PHEAD0)
void SetMods (VOID)
void UnSetMods (VOID)
WORD DoExecute (WORD, WORD)
VOID SetScratch (FILEHANDLE *, POSITION *)
VOID Warning (char *)
VOID HighWarning (char *)
int SpareTable (TABLES)
UBYTE * strDup1 (UBYTE *, char *)
VOID * Malloc (LONG)
VOID * Malloc1 (LONG, const char *)
int DoTail (int, UBYTE **)
int OpenInput (VOID)
int PutPreVar (UBYTE *, UBYTE *, UBYTE *, int)
VOID Error0 (char *)
VOID Error1 (char *, UBYTE *)
VOID Error2 (char *, char *, UBYTE *)
UBYTE ReadFromStream (STREAM *)
UBYTE GetFromStream (STREAM *)
UBYTE LookInStream (STREAM *)
STREAM * OpenStream (UBYTE *, int, int, int)
int LocateFile (UBYTE **, int)
STREAM * CloseStream (STREAM *)
VOID PositionStream (STREAM *, LONG)
int ReverseStatements (STREAM *)
int ProcessOption (UBYTE *, UBYTE *, int)
int DoSetups (VOID)
VOID TerminateImpl (int, const char *, int, const char *)
NAMENODE * GetNode (NAMETREE *, UBYTE *)
int AddName (NAMETREE *, UBYTE *, WORD, WORD, int *)
int GetName (NAMETREE *, UBYTE *, WORD *, int)
UBYTE * GetFunction (UBYTE *, WORD *)
UBYTE * GetNumber (UBYTE *, WORD *)
int GetLastExprName (UBYTE *, WORD *)
int GetAutoName (UBYTE *, WORD *)
int GetVar (UBYTE *, WORD *, WORD *, int, int)
int MakeDubious (NAMETREE *, UBYTE *, WORD *)
int GetOName (NAMETREE *, UBYTE *, WORD *, int)
VOID DumpTree (NAMETREE *)
VOID DumpNode (NAMETREE *, WORD, WORD)
VOID LinkTree (NAMETREE *, WORD, WORD)
VOID CopyTree (NAMETREE *, NAMETREE *, WORD, WORD)
int CompactifyTree (NAMETREE *, WORD)
NAMETREE * MakeNameTree (VOID)
VOID FreeNameTree (NAMETREE *)
int AddExpression (UBYTE *, int, int)
int AddSymbol (UBYTE *, int, int, int, int)
int AddDollar (UBYTE *, WORD, WORD *, LONG)
int ReplaceDollar (WORD, WORD, WORD *, LONG)
int DollarRaiseLow (UBYTE *, LONG)
int AddVector (UBYTE *, int, int)
int AddDubious (UBYTE *)
int AddIndex (UBYTE *, int, int)
UBYTE * DoDimension (UBYTE *, int *, int *)
int AddFunction (UBYTE *, int, int, int, int, int, int, int)
int CoCommuteInSet (UBYTE *)
int CoFunction (UBYTE *, int, int)
int TestName (UBYTE *)
int AddSet (UBYTE *, WORD)
int DoElements (UBYTE *, SETS, UBYTE *)
int DoTempSet (UBYTE *, UBYTE *)
int NameConflict (int, UBYTE *)
int OpenFile (char *)
int OpenAddFile (char *)
int ReOpenFile (char *)
int CreateFile (char *)
int CreateLogFile (char *)
VOID CloseFile (int)
int CopyFile (char *, char *)
int CreateHandle (VOID)
LONG ReadFile (int, UBYTE *, LONG)
LONG ReadPosFile (PHEAD FILEHANDLE *, UBYTE *, LONG, POSITION *)
LONG WriteFileToFile (int, UBYTE *, LONG)
VOID SeekFile (int, POSITION *, int)
LONG TellFile (int)
void FlushFile (int)
int GetPosFile (int, fpos_t *)
int SetPosFile (int, fpos_t *)
VOID SynchFile (int)
VOID TruncateFile (int)
int GetChannel (char *, int)
int GetAppendChannel (char *)
int CloseChannel (char *)
VOID inictable (VOID)
KEYWORD * findcommand (UBYTE *)
int inicbufs (VOID)
VOID StartFiles (VOID)
UBYTE * MakeDate (VOID)
VOID PreProcessor (VOID)
VOID * FromList (LIST *)
VOID * From0List (LIST *)
VOID * FromVarList (LIST *)
int DoubleList (VOID ***, int *, int, char *)
int DoubleLList (VOID ***, LONG *, int, char *)
void DoubleBuffer (void **, void **, int, char *)
void ExpandBuffer (void **, LONG *, int)
LONG iexp (LONG, int)
int IsLikeVector (WORD *)
int AreArgsEqual (WORD *, WORD *)
int CompareArgs (WORD *, WORD *)
UBYTE * SkipField (UBYTE *, int)
int StrCmp (UBYTE *, UBYTE *)
int StrICmp (UBYTE *, UBYTE *)
int StrHICmp (UBYTE *, UBYTE *)
int StrICont (UBYTE *, UBYTE *)
int CmpArray (WORD *, WORD *, WORD)
int ConWord (UBYTE *, UBYTE *)
int StrLen (UBYTE *)
UBYTE * GetPreVar (UBYTE *, int)
void ToGeneral (WORD *, WORD *, WORD)
WORD ToPolyFunGeneral (PHEAD WORD *)
int ToFast (WORD *, WORD *)
SETUPPARAMETERS * GetSetupPar (UBYTE *)
int RecalcSetups (VOID)
int AllocSetups (VOID)
SORTING * AllocSort (LONG, LONG, LONG, LONG, int, int, LONG, int)
VOID AllocSortFileName (SORTING *)
UBYTE * LoadInputFile (UBYTE *, int)
UBYTE GetInput (VOID)
VOID ClearPushback (VOID)
UBYTE GetChar (int)
VOID CharOut (UBYTE)
VOID UnsetAllowDelay (VOID)
VOID PopPreVars (int)
VOID IniModule (int)
VOID IniSpecialModule (int)
int ModuleInstruction (int *, int *)
int PreProInstruction (VOID)
int LoadInstruction (int)
int LoadStatement (int)
KEYWORD * FindKeyWord (UBYTE *, KEYWORD *, int)
KEYWORD * FindInKeyWord (UBYTE *, KEYWORD *, int)
int DoDefine (UBYTE *)
int DoRedefine (UBYTE *)
int TheDefine (UBYTE *, int)
int TheUndefine (UBYTE *)
int ClearMacro (UBYTE *)
int DoUndefine (UBYTE *)
int DoInclude (UBYTE *)
int DoReverseInclude (UBYTE *)
int Include (UBYTE *, int)
int DoExternal (UBYTE *)
int DoToExternal (UBYTE *)
int DoFromExternal (UBYTE *)
int DoPrompt (UBYTE *)
int DoSetExternal (UBYTE *)
int DoSetExternalAttr (UBYTE *)
int DoRmExternal (UBYTE *)
int DoFactDollar (UBYTE *)
WORD GetDollarNumber (UBYTE **, DOLLARS)
int DoSetRandom (UBYTE *)
int DoOptimize (UBYTE *)
int DoClearOptimize (UBYTE *)
int DoSkipExtraSymbols (UBYTE *)
int DoTimeOutAfter (UBYTE *)
int DoMessage (UBYTE *)
int DoPreOut (UBYTE *)
int DoPreAppend (UBYTE *)
int DoPreCreate (UBYTE *)
int DoPreAssign (UBYTE *)
int DoPreBreak (UBYTE *)
int DoPreDefault (UBYTE *)
int DoPreSwitch (UBYTE *)
int DoPreEndSwitch (UBYTE *)
int DoPreCase (UBYTE *)
int DoPreShow (UBYTE *)
int DoPreExchange (UBYTE *)
int DoSystem (UBYTE *)
int DoPipe (UBYTE *)
VOID StartPrepro (VOID)
int DoIfdef (UBYTE *, int)
int DoIfydef (UBYTE *)
int DoIfndef (UBYTE *)
int DoElse (UBYTE *)
int DoElseif (UBYTE *)
int DoEndif (UBYTE *)
int DoTerminate (UBYTE *)
int DoIf (UBYTE *)
int DoCall (UBYTE *)
int DoDebug (UBYTE *)
int DoContinueDo (UBYTE *)
int DoDo (UBYTE *)
int DoBreakDo (UBYTE *)
int DoEnddo (UBYTE *)
int DoEndprocedure (UBYTE *)
int DoInside (UBYTE *)
int DoEndInside (UBYTE *)
int DoProcedure (UBYTE *)
int DoPrePrintTimes (UBYTE *)
int DoPreWrite (UBYTE *)
int DoPreClose (UBYTE *)
int DoPreRemove (UBYTE *)
int DoPreSortReallocate (UBYTE *)
int DoCommentChar (UBYTE *)
int DoPrcExtension (UBYTE *)
int DoPreReset (UBYTE *)
VOID WriteString (int, UBYTE *, int)
VOID WriteUnfinString (int, UBYTE *, int)
UBYTE * AddToString (UBYTE *, UBYTE *, int)
UBYTE * PreCalc (VOID)
UBYTE * PreEval (UBYTE *, LONG *)
VOID NumToStr (UBYTE *, LONG)
int PreCmp (int, int, UBYTE *, int, int, UBYTE *, int)
int PreEq (int, int, UBYTE *, int, int, UBYTE *, int)
UBYTE * pParseObject (UBYTE *, int *, LONG *)
UBYTE * PreIfEval (UBYTE *, int *)
int EvalPreIf (UBYTE *)
int PreLoad (PRELOAD *, UBYTE *, UBYTE *, int, char *)
int PreSkip (UBYTE *, UBYTE *, int)
UBYTE * EndOfToken (UBYTE *)
VOID SetSpecialMode (int, int)
VOID MakeGlobal (VOID)
int ExecModule (int)
int ExecStore (VOID)
VOID FullCleanUp (VOID)
int DoExecStatement (VOID)
int DoPipeStatement (VOID)
int DoPolyfun (UBYTE *)
int DoPolyratfun (UBYTE *)
int CompileStatement (UBYTE *)
UBYTE * ToToken (UBYTE *)
int GetDollar (UBYTE *)
int MesWork (VOID)
int MesPrint (const char *,...)
int MesCall (char *)
UBYTE * NumCopy (WORD, UBYTE *)
char * LongCopy (LONG, char *)
char * LongLongCopy (off_t *, char *)
VOID ReserveTempFiles (int)
VOID PrintTerm (WORD *, char *)
VOID PrintTermC (WORD *, char *)
VOID PrintSubTerm (WORD *, char *)
VOID PrintWords (WORD *, LONG)
void PrintSeq (WORD *, char *)
int ExpandTripleDots (int)
LONG ComPress (WORD **, LONG *)
VOID StageSort (FILEHANDLE *)
void M_free (VOID *, const char *)
void ClearWildcardNames (VOID)
int AddWildcardName (UBYTE *)
int GetWildcardName (UBYTE *)
void Globalize (int)
void ResetVariables (int)
void AddToPreTypes (int)
void MessPreNesting (int)
LONG GetStreamPosition (STREAM *)
WORD * DoubleCbuffer (int, WORD *, int)
WORD * AddLHS (int)
WORD * AddRHS (int, int)
int AddNtoL (int, WORD *)
int AddNtoC (int, int, WORD *, int)
VOID DoubleIfBuffers (VOID)
STREAM * CreateStream (UBYTE *)
int setonoff (UBYTE *, int *, int, int)
int DoPrint (UBYTE *, int)
int SetExpr (UBYTE *, int, int)
void AddToCom (int, WORD *)
int Add2ComStrings (int, WORD *, UBYTE *, UBYTE *)
int DoSymmetrize (UBYTE *, int)
int DoArgument (UBYTE *, int)
int ArgFactorize (PHEAD WORD *, WORD *)
WORD * TakeArgContent (PHEAD WORD *, WORD *)
WORD * MakeInteger (PHEAD WORD *, WORD *, WORD *)
WORD * MakeMod (PHEAD WORD *, WORD *, WORD *)
WORD FindArg (PHEAD WORD *)
WORD InsertArg (PHEAD WORD *, WORD *, int)
int CleanupArgCache (PHEAD WORD)
int ArgSymbolMerge (WORD *, WORD *)
int ArgDotproductMerge (WORD *, WORD *)
void SortWeights (LONG *, LONG *, WORD)
int DoBrackets (UBYTE *, int)
int DoPutInside (UBYTE *, int)
WORD * CountComp (UBYTE *, WORD *)
int CoAntiBracket (UBYTE *)
int CoAntiSymmetrize (UBYTE *)
int DoArgPlode (UBYTE *, int)
int CoArgExplode (UBYTE *)
int CoArgImplode (UBYTE *)
int CoArgument (UBYTE *)
int CoInside (UBYTE *)
int ExecInside (UBYTE *)
int CoInExpression (UBYTE *)
int CoInParallel (UBYTE *)
int CoNotInParallel (UBYTE *)
int DoInParallel (UBYTE *, int)
int CoEndInExpression (UBYTE *)
int CoBracket (UBYTE *)
int CoPutInside (UBYTE *)
int CoAntiPutInside (UBYTE *)
int CoMultiBracket (UBYTE *)
int CoCFunction (UBYTE *)
int CoCTensor (UBYTE *)
int CoCollect (UBYTE *)
int CoCompress (UBYTE *)
int CoContract (UBYTE *)
int CoCycleSymmetrize (UBYTE *)
int CoDelete (UBYTE *)
int CoTableBase (UBYTE *)
int CoApply (UBYTE *)
int CoDenominators (UBYTE *)
int CoDimension (UBYTE *)
int CoDiscard (UBYTE *)
int CoDisorder (UBYTE *)
int CoDrop (UBYTE *)
int CoDropCoefficient (UBYTE *)
int CoDropSymbols (UBYTE *)
int CoElse (UBYTE *)
int CoElseIf (UBYTE *)
int CoEndArgument (UBYTE *)
int CoEndInside (UBYTE *)
int CoEndIf (UBYTE *)
int CoEndRepeat (UBYTE *)
int CoEndTerm (UBYTE *)
int CoEndWhile (UBYTE *)
int CoExit (UBYTE *)
int CoFactArg (UBYTE *)
int CoFactDollar (UBYTE *)
int CoFactorize (UBYTE *)
int CoNFactorize (UBYTE *)
int CoUnFactorize (UBYTE *)
int CoNUnFactorize (UBYTE *)
int DoFactorize (UBYTE *, int)
int CoFill (UBYTE *)
int CoFillExpression (UBYTE *)
int CoFixIndex (UBYTE *)
int CoFormat (UBYTE *)
int CoGlobal (UBYTE *)
int CoGlobalFactorized (UBYTE *)
int CoGoTo (UBYTE *)
int CoId (UBYTE *)
int CoIdNew (UBYTE *)
int CoIdOld (UBYTE *)
int CoIf (UBYTE *)
int CoIfMatch (UBYTE *)
int CoIfNoMatch (UBYTE *)
int CoIndex (UBYTE *)
int CoInsideFirst (UBYTE *)
int CoKeep (UBYTE *)
int CoLabel (UBYTE *)
int CoLoad (UBYTE *)
int CoLocal (UBYTE *)
int CoLocalFactorized (UBYTE *)
int CoMany (UBYTE *)
int CoMerge (UBYTE *)
int CoStuffle (UBYTE *)
int CoMetric (UBYTE *)
int CoModOption (UBYTE *)
int CoModuleOption (UBYTE *)
int CoModulus (UBYTE *)
int CoMulti (UBYTE *)
int CoMultiply (UBYTE *)
int CoNFunction (UBYTE *)
int CoNPrint (UBYTE *)
int CoNTensor (UBYTE *)
int CoNWrite (UBYTE *)
int CoNoDrop (UBYTE *)
int CoNoSkip (UBYTE *)
int CoNormalize (UBYTE *)
int CoMakeInteger (UBYTE *)
int CoFlags (UBYTE *, int)
int CoOff (UBYTE *)
int CoOn (UBYTE *)
int CoOnce (UBYTE *)
int CoOnly (UBYTE *)
int CoOptimizeOption (UBYTE *)
int CoOptimize (UBYTE *)
int CoPolyFun (UBYTE *)
int CoPolyRatFun (UBYTE *)
int CoPrint (UBYTE *)
int CoPrintB (UBYTE *)
int CoProperCount (UBYTE *)
int CoUnitTrace (UBYTE *)
int CoRCycleSymmetrize (UBYTE *)
int CoRatio (UBYTE *)
int CoRedefine (UBYTE *)
int CoRenumber (UBYTE *)
int CoRepeat (UBYTE *)
int CoSave (UBYTE *)
int CoSelect (UBYTE *)
int CoSet (UBYTE *)
int CoSetExitFlag (UBYTE *)
int CoSkip (UBYTE *)
int CoProcessBucket (UBYTE *)
int CoPushHide (UBYTE *)
int CoPopHide (UBYTE *)
int CoHide (UBYTE *)
int CoIntoHide (UBYTE *)
int CoNoHide (UBYTE *)
int CoUnHide (UBYTE *)
int CoNoUnHide (UBYTE *)
int CoSort (UBYTE *)
int CoSplitArg (UBYTE *)
int CoSplitFirstArg (UBYTE *)
int CoSplitLastArg (UBYTE *)
int CoSum (UBYTE *)
int CoSymbol (UBYTE *)
int CoSymmetrize (UBYTE *)
int DoTable (UBYTE *, int)
int CoTable (UBYTE *)
int CoTerm (UBYTE *)
int CoNTable (UBYTE *)
int CoCTable (UBYTE *)
void EmptyTable (TABLES)
int CoToTensor (UBYTE *)
int CoToVector (UBYTE *)
int CoTrace4 (UBYTE *)
int CoTraceN (UBYTE *)
int CoChisholm (UBYTE *)
int CoTransform (UBYTE *)
int CoClearTable (UBYTE *)
int DoChain (UBYTE *, int)
int CoChainin (UBYTE *)
int CoChainout (UBYTE *)
int CoTryReplace (UBYTE *)
int CoVector (UBYTE *)
int CoWhile (UBYTE *)
int CoWrite (UBYTE *)
int CoAuto (UBYTE *)
int CoSwitch (UBYTE *)
int CoCase (UBYTE *)
int CoBreak (UBYTE *)
int CoDefault (UBYTE *)
int CoEndSwitch (UBYTE *)
int CoTBaddto (UBYTE *)
int CoTBaudit (UBYTE *)
int CoTBcleanup (UBYTE *)
int CoTBcreate (UBYTE *)
int CoTBenter (UBYTE *)
int CoTBhelp (UBYTE *)
int CoTBload (UBYTE *)
int CoTBoff (UBYTE *)
int CoTBon (UBYTE *)
int CoTBopen (UBYTE *)
int CoTBreplace (UBYTE *)
int CoTBuse (UBYTE *)
int CoTestUse (UBYTE *)
int CoThreadBucket (UBYTE *)
int AddComString (int, WORD *, UBYTE *, int)
int CompileAlgebra (UBYTE *, int, WORD *)
int IsIdStatement (UBYTE *)
UBYTE * IsRHS (UBYTE *, UBYTE)
int ParenthesesTest (UBYTE *)
int tokenize (UBYTE *, WORD)
void WriteTokens (SBYTE *)
int simp1token (SBYTE *)
int simpwtoken (SBYTE *)
int simp2token (SBYTE *)
int simp3atoken (SBYTE *, int)
int simp3btoken (SBYTE *, int)
int simp4token (SBYTE *)
int simp5token (SBYTE *, int)
int simp6token (SBYTE *, int)
UBYTE * SkipAName (UBYTE *)
int TestTables (VOID)
int GetLabel (UBYTE *)
int CoIdExpression (UBYTE *, int)
int CoAssign (UBYTE *)
int DoExpr (UBYTE *, int, int)
int CompileSubExpressions (SBYTE *)
int CodeGenerator (SBYTE *)
int CompleteTerm (WORD *, UWORD *, UWORD *, WORD, WORD, int)
int CodeFactors (SBYTE *s)
WORD GenerateFactors (WORD, WORD)
int InsTree (int, int)
int FindTree (int, WORD *)
void RedoTree (CBUF *, int)
void ClearTree (int)
int CatchDollar (int)
int AssignDollar (PHEAD WORD *, WORD)
UBYTE * WriteDollarToBuffer (WORD, WORD)
UBYTE * WriteDollarFactorToBuffer (WORD, WORD, WORD)
void AddToDollarBuffer (UBYTE *)
int PutTermInDollar (WORD *, WORD)
void TermAssign (WORD *)
void WildDollars (PHEAD WORD *)
LONG numcommute (WORD *, LONG *)
int FullRenumber (PHEAD WORD *, WORD)
int Lus (WORD *, WORD, WORD, WORD, WORD, WORD)
int FindLus (int, int, int)
int CoReplaceLoop (UBYTE *)
int CoFindLoop (UBYTE *)
int DoFindLoop (UBYTE *, int)
int CoFunPowers (UBYTE *)
int SortTheList (int *, int)
int MatchIsPossible (WORD *, WORD *)
int StudyPattern (WORD *)
WORD DolToTensor (PHEAD WORD)
WORD DolToFunction (PHEAD WORD)
WORD DolToVector (PHEAD WORD)
WORD DolToNumber (PHEAD WORD)
WORD DolToSymbol (PHEAD WORD)
WORD DolToIndex (PHEAD WORD)
LONG DolToLong (PHEAD WORD)
int DollarFactorize (PHEAD WORD)
int CoPrintTable (UBYTE *)
int CoDeallocateTable (UBYTE *)
void CleanDollarFactors (DOLLARS)
WORD * TakeDollarContent (PHEAD WORD *, WORD **)
WORD * MakeDollarInteger (PHEAD WORD *, WORD **)
WORD * MakeDollarMod (PHEAD WORD *, WORD **)
int GetDolNum (PHEAD WORD *, WORD *)
void AddPotModdollar (WORD)
int Optimize (WORD, int)
int ClearOptimize (VOID)
int LoadOpti (WORD)
int PutObject (WORD *, int)
void CleanOptiBuffer (VOID)
int PrintOptima (WORD)
int FindScratchName (VOID)
WORD MaxPowerOpti (LONG)
WORD HuntNumFactor (LONG, WORD *, int)
WORD HuntFactor (LONG, WORD *, int)
void HuntPairs (LONG, WORD)
void HuntBrackets (LONG)
int AddToOpti (WORD *, int)
LONG TestNewSca (LONG, WORD *, WORD *)
void NormOpti (WORD *)
void SortOpti (LONG)
void SplitOpti (WORD **, LONG)
void CombiOpti (VOID)
int TakeLongRoot (UWORD *, WORD *, WORD)
int TakeRatRoot (UWORD *, WORD *, WORD)
int MakeRational (WORD, WORD, WORD *, WORD *)
int MakeLongRational (PHEAD UWORD *, WORD, UWORD *, WORD, UWORD *, WORD *)
void HuntPowers (LONG, WORD)
void HuntNumBrackets (LONG)
void ClearTableTree (TABLES)
int InsTableTree (TABLES, WORD *)
void RedoTableTree (TABLES, int)
int FindTableTree (TABLES, WORD *, int)
void finishcbuf (WORD)
void clearcbuf (WORD)
void CleanUpSort (int)
FILEHANDLE * AllocFileHandle (WORD, char *)
VOID DeAllocFileHandle (FILEHANDLE *)
VOID LowerSortLevel (VOID)
WORD * PolyRatFunSpecial (PHEAD WORD *, WORD *)
VOID SimpleSplitMergeRec (WORD *, WORD, WORD *)
VOID SimpleSplitMerge (WORD *, WORD)
WORD BinarySearch (WORD *, WORD, WORD)
int InsideDollar (PHEAD WORD *, WORD)
DOLLARS DolToTerms (PHEAD WORD)
WORD EvalDoLoopArg (PHEAD WORD *, WORD)
int SetExprCases (int, int, int)
int TestSelect (WORD *, WORD *)
VOID SubsInAll (PHEAD0)
VOID TransferBuffer (int, int, int)
int TakeIDfunction (PHEAD WORD *)
int MakeSetupAllocs (VOID)
int TryFileSetups (VOID)
void ExchangeExpressions (int, int)
void ExchangeDollars (int, int)
int GetFirstBracket (WORD *, int)
int GetFirstTerm (WORD *, int, int)
int GetContent (WORD *, int)
int CleanupTerm (WORD *)
WORD ContentMerge (PHEAD WORD *, WORD *)
UBYTE * PreIfDollarEval (UBYTE *, int *)
LONG TermsInDollar (WORD)
LONG SizeOfDollar (WORD)
LONG TermsInExpression (WORD)
LONG SizeOfExpression (WORD)
WORD * TranslateExpression (UBYTE *)
int IsSetMember (WORD *, WORD)
int IsMultipleOf (WORD *, WORD *)
int TwoExprCompare (WORD *, WORD *, int)
void UpdatePositions (VOID)
void M_check (VOID)
void M_print (VOID)
void M_check1 (VOID)
void PrintTime (UBYTE *)
POSITION * FindBracket (WORD, WORD *)
VOID PutBracketInIndex (PHEAD WORD *, POSITION *)
void ClearBracketIndex (WORD)
VOID OpenBracketIndex (WORD)
int DoNoParallel (UBYTE *)
int DoParallel (UBYTE *)
int DoModSum (UBYTE *)
int DoModMax (UBYTE *)
int DoModMin (UBYTE *)
int DoModLocal (UBYTE *)
UBYTE * DoModDollar (UBYTE *, int)
int DoProcessBucket (UBYTE *)
int DoinParallel (UBYTE *)
int DonotinParallel (UBYTE *)
int FlipTable (FUNCTIONS, int)
int ChainIn (PHEAD WORD *, WORD)
int ChainOut (PHEAD WORD *, WORD)
int ArgumentImplode (PHEAD WORD *, WORD *)
int ArgumentExplode (PHEAD WORD *, WORD *)
int DenToFunction (WORD *, WORD)
WORD HowMany (PHEAD WORD *, WORD *)
VOID RemoveDollars (VOID)
LONG CountTerms1 (PHEAD0)
LONG TermsInBracket (PHEAD WORD *, WORD)
int Crash (VOID)
char * str_dup (char *)
void convertblock (INDEXBLOCK *, INDEXBLOCK *, int)
void convertnamesblock (NAMESBLOCK *, NAMESBLOCK *, int)
void convertiniinfo (INIINFO *, INIINFO *, int)
int ReadIndex (DBASE *)
int WriteIndexBlock (DBASE *, MLONG)
int WriteNamesBlock (DBASE *, MLONG)
int WriteIndex (DBASE *)
int WriteIniInfo (DBASE *)
int ReadIniInfo (DBASE *)
int AddToIndex (DBASE *, MLONG)
DBASE * GetDbase (char *, MLONG)
DBASE * OpenDbase (char *)
char * ReadObject (DBASE *, MLONG, char *)
char * ReadijObject (DBASE *, MLONG, MLONG, char *)
int ExistsObject (DBASE *, MLONG, char *)
int DeleteObject (DBASE *, MLONG, char *)
int WriteObject (DBASE *, MLONG, char *, char *, MLONG)
MLONG AddObject (DBASE *, MLONG, char *, char *)
int Cleanup (DBASE *)
DBASE * NewDbase (char *, MLONG)
void FreeTableBase (DBASE *)
int ComposeTableNames (DBASE *)
int PutTableNames (DBASE *)
MLONG AddTableName (DBASE *, char *, TABLES)
MLONG GetTableName (DBASE *, char *)
MLONG FindTableNumber (DBASE *, char *)
int TryEnvironment (VOID)
int CopyExpression (FILEHANDLE *, FILEHANDLE *)
int set_in (UBYTE, set_of_char)
one_byte set_set (UBYTE, set_of_char)
one_byte set_del (UBYTE, set_of_char)
one_byte set_sub (set_of_char, set_of_char, set_of_char)
int DoPreAddSeparator (UBYTE *)
int DoPreRmSeparator (UBYTE *)
int openExternalChannel (UBYTE *, int, UBYTE *, UBYTE *)
int initPresetExternalChannels (UBYTE *, int)
int closeExternalChannel (int)
int selectExternalChannel (int)
int getCurrentExternalChannel (VOID)
VOID closeAllExternalChannels (VOID)
UBYTE * defineChannel (UBYTE *, HANDLERS *)
int writeToChannel (int, UBYTE *, HANDLERS *)
int writeBufToExtChannelOk (char *, size_t)
int getcFromExtChannelOk (VOID)
int setKillModeForExternalChannelOk (int, int)
int setTerminatorForExternalChannelOk (char *)
int getcFromExtChannelFailure (VOID)
int setKillModeForExternalChannelFailure (int, int)
int setTerminatorForExternalChannelFailure (char *)
int writeBufToExtChannelFailure (char *, size_t)
int ReleaseTB (VOID)
int SymbolNormalize (WORD *)
int TestFunFlag (PHEAD WORD *)
WORD CompareSymbols (PHEAD WORD *, WORD *, WORD)
WORD CompareHSymbols (PHEAD WORD *, WORD *, WORD)
WORD NextPrime (PHEAD WORD)
WORD Moebius (PHEAD WORD)
UWORD wranf (PHEAD0)
UWORD iranf (PHEAD UWORD)
void iniwranf (PHEAD0)
UBYTE * PreRandom (UBYTE *)
WORD * PolyNormPoly (PHEAD WORD)
WORD * EvaluateGcd (PHEAD WORD *)
int TreatPolyRatFun (PHEAD WORD *)
WORD ReadSaveHeader (VOID)
WORD ReadSaveIndex (FILEINDEX *)
WORD ReadSaveExpression (UBYTE *, UBYTE *, LONG *, LONG *)
UBYTE * ReadSaveTerm32 (UBYTE *, UBYTE *, UBYTE **, UBYTE *, UBYTE *, int)
WORD ReadSaveVariables (UBYTE *, UBYTE *, LONG *, LONG *, INDEXENTRY *, LONG *)
WORD WriteStoreHeader (WORD)
void InitRecovery (VOID)
int CheckRecoveryFile (VOID)
void DeleteRecoveryFile (VOID)
char * RecoveryFilename (VOID)
int DoRecovery (int *)
void DoCheckpoint (int)
VOID NumberMallocAddMemory (PHEAD0)
VOID CacheNumberMallocAddMemory (PHEAD0)
VOID TermMallocAddMemory (PHEAD0)
void ExprStatus (EXPRESSIONS)
VOID iniTools (VOID)
int TestTerm (WORD *)
WORD RunTransform (PHEAD WORD *term, WORD *params)
WORD RunEncode (PHEAD WORD *fun, WORD *args, WORD *info)
WORD RunDecode (PHEAD WORD *fun, WORD *args, WORD *info)
WORD RunReplace (PHEAD WORD *fun, WORD *args, WORD *info)
WORD RunImplode (WORD *fun, WORD *args)
WORD RunExplode (PHEAD WORD *fun, WORD *args)
int TestArgNum (int n, int totarg, WORD *args)
WORD PutArgInScratch (WORD *arg, UWORD *scrat)
UBYTE * ReadRange (UBYTE *s, WORD *out, int par)
int FindRange (PHEAD WORD *, WORD *, WORD *, WORD)
WORD RunPermute (PHEAD WORD *fun, WORD *args, WORD *info)
WORD RunReverse (PHEAD WORD *fun, WORD *args)
WORD RunCycle (PHEAD WORD *fun, WORD *args, WORD *info)
WORD RunAddArg (PHEAD WORD *fun, WORD *args)
WORD RunMulArg (PHEAD WORD *fun, WORD *args)
WORD RunIsLyndon (PHEAD WORD *fun, WORD *args, int par)
WORD RunToLyndon (PHEAD WORD *fun, WORD *args, int par)
WORD RunDropArg (PHEAD WORD *fun, WORD *args)
WORD RunSelectArg (PHEAD WORD *fun, WORD *args)
WORD RunDedup (PHEAD WORD *fun, WORD *args)
WORD RunZtoHArg (PHEAD WORD *fun, WORD *args)
WORD RunHtoZArg (PHEAD WORD *fun, WORD *args)
int NormPolyTerm (PHEAD WORD *)
WORD ComparePoly (WORD *, WORD *, WORD)
int ConvertToPoly (PHEAD WORD *, WORD *, WORD *, WORD)
int LocalConvertToPoly (PHEAD WORD *, WORD *, WORD, WORD)
int ConvertFromPoly (PHEAD WORD *, WORD *, WORD, WORD, WORD, WORD)
WORD FindSubterm (WORD *)
WORD FindLocalSubterm (PHEAD WORD *, WORD)
void PrintSubtermList (int, int)
void PrintExtraSymbol (int, WORD *, int)
WORD FindSubexpression (WORD *)
void UpdateMaxSize (VOID)
int CoToPolynomial (UBYTE *)
int CoFromPolynomial (UBYTE *)
int CoArgToExtraSymbol (UBYTE *)
int CoExtraSymbols (UBYTE *)
UBYTE * GetDoParam (UBYTE *, WORD **, int)
WORD * GetIfDollarFactor (UBYTE **, WORD *)
int CoDo (UBYTE *)
int CoEndDo (UBYTE *)
int ExtraSymFun (PHEAD WORD *, WORD)
int PruneExtraSymbols (WORD)
int IniFbuffer (WORD)
void IniFbufs (VOID)
int GCDfunction (PHEAD WORD *, WORD)
WORD * GCDfunction3 (PHEAD WORD *, WORD *)
WORD * GCDfunction4 (PHEAD WORD *, WORD *)
int ReadPolyRatFun (PHEAD WORD *)
int FromPolyRatFun (PHEAD WORD *, WORD **, WORD **)
void PRFnormalize (PHEAD WORD *)
WORD * PRFadd (PHEAD WORD *, WORD *)
WORD * PolyDiv (PHEAD WORD *, WORD *, char *)
WORD * PolyGCD (PHEAD WORD *, WORD *)
WORD * PolyAdd (PHEAD WORD *, WORD *)
void GCDclean (PHEAD WORD *, WORD *)
int RatFunNormalize (PHEAD WORD *)
WORD * TakeSymbolContent (PHEAD WORD *, WORD *)
int GCDterms (PHEAD WORD *, WORD *, WORD *)
WORD * PutExtraSymbols (PHEAD WORD *, WORD, int *)
WORD * TakeExtraSymbols (PHEAD WORD *, WORD)
WORD * MultiplyWithTerm (PHEAD WORD *, WORD *, WORD)
WORD * TakeContent (PHEAD WORD *, WORD *)
int MergeSymbolLists (PHEAD WORD *, WORD *, int)
int MergeDotproductLists (PHEAD WORD *, WORD *, int)
WORD * CreateExpression (PHEAD WORD)
int DIVfunction (PHEAD WORD *, WORD, int)
WORD * MULfunc (PHEAD WORD *, WORD *)
WORD * ConvertArgument (PHEAD WORD *, int *)
int ExpandRat (PHEAD WORD *)
int InvPoly (PHEAD WORD *, WORD, WORD)
WORD TestDoLoop (PHEAD WORD *, WORD)
WORD TestEndDoLoop (PHEAD WORD *, WORD)
WORD * poly_gcd (PHEAD WORD *, WORD *, WORD)
WORD * poly_div (PHEAD WORD *, WORD *, WORD)
WORD * poly_rem (PHEAD WORD *, WORD *, WORD)
WORD * poly_inverse (PHEAD WORD *, WORD *)
WORD * poly_mul (PHEAD WORD *, WORD *)
WORD * poly_ratfun_add (PHEAD WORD *, WORD *)
int poly_ratfun_normalize (PHEAD WORD *)
int poly_factorize_argument (PHEAD WORD *, WORD *)
WORD * poly_factorize_dollar (PHEAD WORD *)
int poly_factorize_expression (EXPRESSIONS)
int poly_unfactorize_expression (EXPRESSIONS)
void poly_free_poly_vars (PHEAD const char *)
VOID optimize_print_code (int)
int DoPreAdd (UBYTE *s)
int DoPreUseDictionary (UBYTE *s)
int DoPreCloseDictionary (UBYTE *s)
int DoPreOpenDictionary (UBYTE *s)
void RemoveDictionary (DICTIONARY *dict)
void UnSetDictionary (VOID)
int SetDictionaryOptions (UBYTE *options)
int SelectDictionary (UBYTE *name, UBYTE *options)
int AddToDictionary (DICTIONARY *dict, UBYTE *left, UBYTE *right)
int AddDictionary (UBYTE *name)
int FindDictionary (UBYTE *name)
UBYTE * IsExponentSign (VOID)
UBYTE * IsMultiplySign (VOID)
VOID TransformRational (UWORD *a, WORD na)
void WriteDictionary (DICTIONARY *)
void ShrinkDictionary (DICTIONARY *)
void MultiplyToLine (VOID)
UBYTE * FindSymbol (WORD num)
UBYTE * FindVector (WORD num)
UBYTE * FindIndex (WORD num)
UBYTE * FindFunction (WORD num)
UBYTE * FindFunWithArgs (WORD *t)
UBYTE * FindExtraSymbol (WORD num)
LONG DictToBytes (DICTIONARY *dict, UBYTE *buf)
DICTIONARY * DictFromBytes (UBYTE *buf)
int CoCreateSpectator (UBYTE *inp)
int CoToSpectator (UBYTE *inp)
int CoRemoveSpectator (UBYTE *inp)
int CoEmptySpectator (UBYTE *inp)
int CoCopySpectator (UBYTE *inp)
int PutInSpectator (WORD *, WORD)
void ClearSpectators (WORD)
WORD GetFromSpectator (WORD *, WORD)
void FlushSpectators (VOID)
WORD * PreGCD (PHEAD WORD *, WORD *, int)
WORD * FindCommonVariables (PHEAD int, int)
VOID AddToSymbolList (PHEAD WORD)
int AddToListPoly (PHEAD0)
int ReadFromScratch (FILEHANDLE *, POSITION *, UBYTE *, POSITION *)
int AddToScratch (FILEHANDLE *, POSITION *, UBYTE *, POSITION *, int)
int DoPreAppendPath (UBYTE *)
int DoPrePrependPath (UBYTE *)
int DoSwitch (PHEAD WORD *, WORD *)
int DoEndSwitch (PHEAD WORD *, WORD *)
SWITCHTABLE * FindCase (WORD, WORD)
VOID SwitchSplitMergeRec (SWITCHTABLE *, WORD, SWITCHTABLE *)
VOID SwitchSplitMerge (SWITCHTABLE *, WORD)
int DoubleSwitchBuffers (VOID)
int DistrN (int, int *, int, int *)
int DoNamespace (UBYTE *)
int DoEndNamespace (UBYTE *)
int DoUse (UBYTE *)
UBYTE * SkipName (UBYTE *)
UBYTE * ConstructName (UBYTE *, UBYTE)
int DoSetUserFlag (UBYTE *)
int DoClearUserFlag (UBYTE *)
int DoUserFlag (UBYTE *, int)
VERTEX * CreateVertex (MODEL *)
UBYTE * ReadParticle (UBYTE *, VERTEX *, MODEL *, int)
int CoModel (UBYTE *)
int CoParticle (UBYTE *)
int CoVertex (UBYTE *)
int CoEndModel (UBYTE *)
int LoadModel (MODEL *)
int CoSetUserFlag (UBYTE *)
int CoClearUserFlag (UBYTE *)
int CoCreateAllLoops (UBYTE *)
int CoCreateAllPaths (UBYTE *)
int CoCreateAll (UBYTE *)
WORD AllLoops (PHEAD WORD *, WORD)
LONG StartLoops (PHEAD WORD *, WORD, LONG, WORD, WORD *, WORD, WORD *, WORD)
LONG GenLoops (PHEAD WORD *, WORD, LONG, WORD, WORD *, WORD, WORD *, WORD)
void LoopOutput (PHEAD WORD *, WORD, WORD *, WORD)
WORD AllPaths (PHEAD WORD *, WORD)
LONG GenPaths (PHEAD WORD *, WORD, LONG, WORD, WORD *, WORD, WORD *, WORD)
void PathOutput (PHEAD WORD *, WORD, WORD *, WORD)
Detailed Description
Contains macros and function declarations.
Definition in file declare.h.
Macro Definition Documentation
MaX
#define MaX (x, y) ((x) > (y) ? (x): (y))
Definition at line 40 of file declare.h.
MiN
#define MiN (x, y) ((x) < (y) ? (x): (y))
Definition at line 41 of file declare.h.
ABS
#define ABS (x) ((x) < 0 ? -(x): (x))
Definition at line 42 of file declare.h.
SGN
#define SGN (x) ((x) > 0 ? 1 : (x) < 0 ? -1 : 0)
Definition at line 43 of file declare.h.
REDLENG
#define REDLENG (x) ((((x)<0)?((x)+1):((x)-1))/2)
Definition at line 44 of file declare.h.
INCLENG
#define INCLENG (x) (((x)<0)?(((x)*2)-1):(((x)*2)+1))
Definition at line 45 of file declare.h.
GETCOEF
#define GETCOEF (x, y) x += *x;y = x[-1];x -= ABS(y);y=REDLENG(y)
Definition at line 46 of file declare.h.
GETSTOP
#define GETSTOP (x, y) y=x+(*x)-1;y -= ABS(*y)-1
Definition at line 47 of file declare.h.
StuffAdd
#define StuffAdd (x, y) (((x)<0?-1:1)*(y)+((y)<0?-1:1)*(x))
Definition at line 48 of file declare.h.
EXCHN
#define EXCHN (t1, t2, n) { WORD a,i; for(i=0;i<n;i++){a=t1[i];t1[i]=t2[i];t2[i]=a;} }
Definition at line 50 of file declare.h.
EXCH
#define EXCH (x, y) { WORD a = (x); (x) = (y); (y) = a; }
Definition at line 51 of file declare.h.
TOKENTOLINE
#define TOKENTOLINE (x, y)
Value:
        if ( AC.OutputSpaces == NOSPACEFORMAT ) { \
        TokenToLine((UBYTE *)(y)); } else { TokenToLine((UBYTE *)(x)); }
Definition at line 53 of file declare.h.
UngetFromStream
#define UngetFromStream (stream, c) ((stream)->nextchar[(stream)->isnextchar++]=c)
Definition at line 56 of file declare.h.
AddLineFeed
#define AddLineFeed (s, n) { (s)[(n)++] = LINEFEED; }
Definition at line 60 of file declare.h.
TryRecover
#define TryRecover (x) Terminate(-1)
Definition at line 62 of file declare.h.
UngetChar
#define UngetChar (c) { pushbackchar = c; }
Definition at line 63 of file declare.h.
ParseNumber
#define ParseNumber (x, s) {(x)=0;while(*(s)>='0'&&*(s)<='9')(x)=10*(x)+*(s)++ -'0';}
Definition at line 64 of file declare.h.
ParseSign
#define ParseSign (sgn, s)
Value:
          {(sgn)=0;while(*(s)=='-'||*(s)=='+'){\
          if ( *(s)++ == '-' ) sgn ^= 1;}}
Definition at line 65 of file declare.h.
ParseSignedNumber
#define ParseSignedNumber (x, s)
Value:
          { int sgn; ParseSign(sgn,s)\
          ParseNumber(x,s) if ( sgn ) x = -x; }
Definition at line 67 of file declare.h.
NCOPY
#define NCOPY (s, t, n) { while ((n)-- > 0) { *s++ = *t++; } }
Definition at line 71 of file declare.h.
NCOPYI
#define NCOPYI (s, t, n) { while ((n)-- > 0) { *s++ = *t++; } }
Definition at line 73 of file declare.h.
NCOPYB
#define NCOPYB (s, t, n) { while ((n)-- > 0) { *s++ = *t++; } }
Definition at line 74 of file declare.h.
NCOPYI32
#define NCOPYI32 (s, t, n) { while ((n)-- > 0) { *s++ = *t++; } }
Definition at line 75 of file declare.h.
WCOPY
#define WCOPY (s, t, n) { int nn=n; WORD *ss=(WORD *)s, *tt=(WORD *)t; while ((nn)-- > 0) { *ss++ = *tt++; } }
Definition at line 76 of file declare.h.
NeedNumber
#define NeedNumber (x, s, err)
Value:
        { int sgn = 1;                               \
        while ( *s == ' ' || *s == '\t' || *s == '-' || *s == '+' ) {      \
            if ( *s == '-' ) {sgn = -sgn;} s++; }                           \
        if ( chartype[*s] != 1 ) goto err;                                 \
        ParseNumber(x,s)                                                   \
        if ( sgn < 0 ) {(x) = -(x);} while ( *s == ' ' || *s == '\t' ) s++;\
    }
Definition at line 78 of file declare.h.
SKIPBLANKS
#define SKIPBLANKS (s) { while (*(s) == ' ' || *(s) == '\t') (s)++; }
Definition at line 85 of file declare.h.
FLUSHCONSOLE
#define FLUSHCONSOLE if (AP.InOutBuf > 0) CharOut(LINEFEED)
Definition at line 86 of file declare.h.
SKIPBRA1
#define SKIPBRA1 (s)
Value:
                    { int lev1=0; s++; while(*s) { if(*s=='['){lev1++;} \
                    else {if(*s==']'&&--lev1<0){break;}} s++;} }
Definition at line 88 of file declare.h.
SKIPBRA2
#define SKIPBRA2 (s)
Value:
                    { int lev2=0; s++; while(*s) { if(*s=='{'){lev2++;} \
                    else {if(*s=='}'&&--lev2<0){break;} \
                    else {if(*s=='['){SKIPBRA1(s)}}} s++;} }
Definition at line 90 of file declare.h.
SKIPBRA3
#define SKIPBRA3 (s)
Value:
                    { int lev3=0; s++; while(*s) { if(*s=='('){lev3++;} \
                    else {if(*s==')'&&--lev3<0){break;} \
                    else {if(*s=='{'){SKIPBRA2(s)} \
                    else {if(*s=='['){SKIPBRA1(s)}}}} s++;} }
Definition at line 93 of file declare.h.
SKIPBRA4
#define SKIPBRA4 (s)
Value:
                    { int lev4=0; s++; while(*s) { if(*s=='('){lev4++;} \
                    else {if(*s==')'&&--lev4<0){break;} \
                    else {if(*s=='['){SKIPBRA1(s)}}} s++;} }
Definition at line 97 of file declare.h.
SKIPBRA5
#define SKIPBRA5 (s)
Value:
                    { int lev5=0; s++; while(*s) { if(*s=='{'){lev5++;} \
                    else {if(*s=='}'&&--lev5<0){break;} \
                    else {if(*s=='('){SKIPBRA4(s)} \
                    else {if(*s=='['){SKIPBRA1(s)}}}} s++;} }
Definition at line 100 of file declare.h.
CYCLE1
#define CYCLE1 (t, a, i) {t iX=*a; WORD jX; for(jX=1;jX<i;jX++)a[jX-1]=a[jX]; a[i-1]=iX;}
Definition at line 108 of file declare.h.
AddToCB
#define AddToCB (c, wx)
Value:
        if(c->Pointer>=c->Top) \
        {DoubleCbuffer(c-cbuf,c->Pointer,21);} \
        *(c->Pointer)++ = wx;
Definition at line 110 of file declare.h.
EXCHINOUT
#define EXCHINOUT
Value:
    { FILEHANDLE *ffFi = AR.outfile; \
    AR.outfile = AR.infile; AR.infile = ffFi; }
Definition at line 114 of file declare.h.
BACKINOUT
#define BACKINOUT
Value:
    { FILEHANDLE *ffFi = AR.outfile; POSITION posi; \
    AR.outfile = AR.infile; AR.infile = ffFi; \
    SetEndScratch(AR.infile,&posi); }
Definition at line 116 of file declare.h.
CopyArg
#define CopyArg (to, from)
Value:
        { if ( *from > 0 ) { int ica = *from; NCOPY(to,from,ica) } \
        else if ( *from <= -FUNCTION ) *to++ = *from++;  \
        else { *to++ = *from++; *to++ = *from++; } }
Definition at line 120 of file declare.h.
FILLARG
#define FILLARG (w)
Definition at line 129 of file declare.h.
COPYARG
#define COPYARG (w, t)
Definition at line 130 of file declare.h.
ZEROARG
#define ZEROARG (w)
Definition at line 131 of file declare.h.
FILLFUN
#define FILLFUN (w)
Definition at line 138 of file declare.h.
COPYFUN
#define COPYFUN (w, t)
Definition at line 139 of file declare.h.
COPYFUN3
#define COPYFUN3 (w, t)
Definition at line 146 of file declare.h.
FILLFUN3
#define FILLFUN3 (w)
Definition at line 147 of file declare.h.
FILLSUB
#define FILLSUB (w)
Definition at line 154 of file declare.h.
COPYSUB
#define COPYSUB (w, ww)
Definition at line 155 of file declare.h.
FILLEXPR
#define FILLEXPR (w)
Definition at line 161 of file declare.h.
NEXTARG
#define NEXTARG (x) if(*x>0) x += *x; else if(*x <= -FUNCTION)x++; else x += 2;
Definition at line 164 of file declare.h.
COPY1ARG
#define COPY1ARG (s1, t1)
Value:
        { int ica; if ( (ica=*t1) > 0 ) { NCOPY(s1,t1,ica) } \
        else if(*t1<=-FUNCTION){*s1++=*t1++;} else{*s1++=*t1++;*s1++=*t1++;} }
Definition at line 165 of file declare.h.
ZeroFillRange
#define ZeroFillRange (w, begin, end)
Value:
    do { \
    int tmp_i; \
    for ( tmp_i = begin; tmp_i < end; tmp_i++ ) { (w)[tmp_i] = 0; } \
} while (0)
Fills a buffer by zero in the range [begin,end).
Parameters
w The buffer.
begin The index for the beginning of the range.
end The index for the end of the range (exclusive).
Definition at line 175 of file declare.h.
TABLESIZE
#define TABLESIZE (a, b) (((WORD)sizeof(a))/((WORD)sizeof(b)))
Definition at line 180 of file declare.h.
WORDDIF
#define WORDDIF (x, y) (WORD)(x-y)
Definition at line 181 of file declare.h.
wsizeof
#define wsizeof (a) ((WORD)sizeof(a))
Definition at line 182 of file declare.h.
VARNAME
#define VARNAME (type, num) (AC.varnames->namebuffer+type[num].name)
Definition at line 183 of file declare.h.
DOLLARNAME
#define DOLLARNAME (type, num) (AC.dollarnames->namebuffer+type[num].name)
Definition at line 184 of file declare.h.
EXPRNAME
#define EXPRNAME (num) (AC.exprnames->namebuffer+Expressions[num].name)
Definition at line 185 of file declare.h.
PREV
#define PREV (x) prevorder?prevorder:x
Definition at line 187 of file declare.h.
Terminate
#define Terminate (x) do { TerminateImpl(x, __FILE__, __LINE__, __FUNCTION__); } while(0)
Definition at line 189 of file declare.h.
SETERROR
#define SETERROR (x) { Terminate(-1); return(-1); }
Definition at line 190 of file declare.h.
DUMMYUSE
#define DUMMYUSE (x) (void)(x);
Definition at line 193 of file declare.h.
ADDPOS
#define ADDPOS (pp, x) (pp).p1 = ((pp).p1+(LONG)(x))
Definition at line 219 of file declare.h.
SETBASELENGTH
#define SETBASELENGTH (ss, x) (ss).p1 = (LONG)(x)
Definition at line 220 of file declare.h.
SETBASEPOSITION
#define SETBASEPOSITION (pp, x) (pp).p1 = (LONG)(x)
Definition at line 221 of file declare.h.
ISEQUALPOSINC
#define ISEQUALPOSINC (pp1, pp2, x) ((pp1).p1 == ((pp2).p1+(LONG)(x)))
Definition at line 222 of file declare.h.
ISGEPOSINC
#define ISGEPOSINC (pp1, pp2, x) ((pp1).p1 >= ((pp2).p1+(LONG)(x)))
Definition at line 223 of file declare.h.
DIVPOS
#define DIVPOS (pp, n) ((pp).p1/(LONG)(n))
Definition at line 224 of file declare.h.
MULPOS
#define MULPOS (pp, n) (pp).p1 *= (LONG)(n)
Definition at line 225 of file declare.h.
DIFPOS
#define DIFPOS (ss, pp1, pp2) (ss).p1 = ((pp1).p1-(pp2).p1)
Definition at line 228 of file declare.h.
DIFBASE
#define DIFBASE (pp1, pp2) ((pp1).p1-(pp2).p1)
Definition at line 229 of file declare.h.
ADD2POS
#define ADD2POS (pp1, pp2) (pp1).p1 += (pp2).p1
Definition at line 230 of file declare.h.
PUTZERO
#define PUTZERO (pp) (pp).p1 = 0
Definition at line 231 of file declare.h.
BASEPOSITION
#define BASEPOSITION (pp) ((pp).p1)
Definition at line 232 of file declare.h.
SETSTARTPOS
#define SETSTARTPOS (pp) (pp).p1 = -2
Definition at line 233 of file declare.h.
NOTSTARTPOS
#define NOTSTARTPOS (pp) ((pp).p1 > -2)
Definition at line 234 of file declare.h.
ISMINPOS
#define ISMINPOS (pp) ((pp).p1 == -1)
Definition at line 235 of file declare.h.
ISEQUALPOS
#define ISEQUALPOS (pp1, pp2) ((pp1).p1 == (pp2).p1)
Definition at line 236 of file declare.h.
ISNOTEQUALPOS
#define ISNOTEQUALPOS (pp1, pp2) ((pp1).p1 != (pp2).p1)
Definition at line 237 of file declare.h.
ISLESSPOS
#define ISLESSPOS (pp1, pp2) ((pp1).p1 < (pp2).p1)
Definition at line 238 of file declare.h.
ISGEPOS
#define ISGEPOS (pp1, pp2) ((pp1).p1 >= (pp2).p1)
Definition at line 239 of file declare.h.
ISNOTZEROPOS
#define ISNOTZEROPOS (pp) ((pp).p1 != 0)
Definition at line 240 of file declare.h.
ISZEROPOS
#define ISZEROPOS (pp) ((pp).p1 == 0)
Definition at line 241 of file declare.h.
ISPOSPOS
#define ISPOSPOS (pp) ((pp).p1 > 0)
Definition at line 242 of file declare.h.
ISNEGPOS
#define ISNEGPOS (pp) ((pp).p1 < 0)
Definition at line 243 of file declare.h.
TOLONG
#define TOLONG (x) ((LONG)(x))
Definition at line 246 of file declare.h.
Add2Com
#define Add2Com (x) { WORD cod[2]; cod[0] = x; cod[1] = 2; AddNtoL(2,cod); }
Definition at line 248 of file declare.h.
Add3Com
#define Add3Com (x1, x2) { WORD cod[3]; cod[0] = x1; cod[1] = 3; cod[2] = x2; AddNtoL(3,cod); }
Definition at line 249 of file declare.h.
Add4Com
#define Add4Com (x1, x2, x3)
Value:
   { WORD cod[4]; cod[0] = x1; cod[1] = 4; \
   cod[2] = x2; cod[3] = x3; AddNtoL(4,cod); }
Definition at line 250 of file declare.h.
Add5Com
#define Add5Com (x1, x2, x3, x4)
Value:
   { WORD cod[5]; cod[0] = x1; cod[1] = 5; \
   cod[2] = x2; cod[3] = x3; cod[4] = x4; AddNtoL(5,cod); }
Definition at line 252 of file declare.h.
WantAddPointers
#define WantAddPointers (x)
Value:
    while((AT.pWorkPointer+(x))>AR.pWorkSize){WORD ***ppp=&AT.pWorkSpace;\
    ExpandBuffer((void **)ppp,&AR.pWorkSize,(int)(sizeof(WORD *)));}
Definition at line 258 of file declare.h.
WantAddLongs
#define WantAddLongs (x)
Value:
    while((AT.lWorkPointer+(x))>AR.lWorkSize){LONG **ppp=&AT.lWorkSpace;\
    ExpandBuffer((void **)ppp,&AR.lWorkSize,sizeof(LONG));}
Definition at line 260 of file declare.h.
WantAddPositions
#define WantAddPositions (x)
Value:
    while((AT.posWorkPointer+(x))>AR.posWorkSize){POSITION **ppp=&AT.posWorkSpace;\
    ExpandBuffer((void **)ppp,&AR.posWorkSize,sizeof(POSITION));}
Definition at line 262 of file declare.h.
FORM_INLINE
#define FORM_INLINE inline
Definition at line 266 of file declare.h.
MEMORYMACROS
#define MEMORYMACROS
Definition at line 274 of file declare.h.
TermMalloc
#define TermMalloc (x) ((AT.TermMemTop <= 0) ? TermMallocAddMemory(BHEAD0), AT.TermMemHeap[--AT.TermMemTop]: AT.TermMemHeap[--AT.TermMemTop])
Definition at line 278 of file declare.h.
NumberMalloc
#define NumberMalloc (x) ((AT.NumberMemTop <= 0) ? NumberMallocAddMemory(BHEAD0), AT.NumberMemHeap[--AT.NumberMemTop]: AT.NumberMemHeap[--AT.NumberMemTop])
Definition at line 279 of file declare.h.
CacheNumberMalloc
#define CacheNumberMalloc (x) ((AT.CacheNumberMemTop <= 0) ? CacheNumberMallocAddMemory(BHEAD0), AT.CacheNumberMemHeap[--AT.CacheNumberMemTop]: AT.CacheNumberMemHeap[--AT.CacheNumberMemTop])
Definition at line 280 of file declare.h.
TermFree
#define TermFree (TermMem, x) AT.TermMemHeap[AT.TermMemTop++] = (WORD *)(TermMem)
Definition at line 281 of file declare.h.
NumberFree
#define NumberFree (NumberMem, x) AT.NumberMemHeap[AT.NumberMemTop++] = (UWORD *)(NumberMem)
Definition at line 282 of file declare.h.
CacheNumberFree
#define CacheNumberFree (NumberMem, x) AT.CacheNumberMemHeap[AT.CacheNumberMemTop++] = (UWORD *)(NumberMem)
Definition at line 283 of file declare.h.
NestingChecksum
#define NestingChecksum () (AC.IfLevel + AC.RepLevel + AC.arglevel + AC.insidelevel + AC.termlevel + AC.inexprlevel + AC.dolooplevel +AC.SwitchLevel)
Definition at line 311 of file declare.h.
MesNesting
#define MesNesting () MesPrint("&Illegal nesting of if, repeat, argument, inside, term, inexpression and do")
Definition at line 312 of file declare.h.
MarkPolyRatFunDirty
#define MarkPolyRatFunDirty (T)
Value:
{if(*T&&AR.PolyFunType==2){WORD *TP,*TT;TT=T+*T;TT-=ABS(TT[-1]);\
TP=T+1;while(TP<TT){if(*TP==AR.PolyFun){TP[2]|=(DIRTYFLAG|MUSTCLEANPRF);}TP+=TP[1];}}}
Definition at line 314 of file declare.h.
PUSHPREASSIGNLEVEL
#define PUSHPREASSIGNLEVEL
Value:
    AP.PreAssignLevel++; { GETIDENTITY \
    if ( AP.PreAssignLevel >= AP.MaxPreAssignLevel ) { int i; \
        LONG *ap = (LONG *)Malloc1(2*AP.MaxPreAssignLevel*sizeof(LONG *),"PreAssignStack"); \
        for ( i = 0; i < AP.MaxPreAssignLevel; i++ ) ap[i] = AP.PreAssignStack[i]; \
        M_free(AP.PreAssignStack,"PreAssignStack"); \
        AP.MaxPreAssignLevel *= 2; AP.PreAssignStack = ap; \
    } \
    *AT.WorkPointer++ = AP.PreContinuation; AP.PreContinuation = 0; \
    AP.PreAssignStack[AP.PreAssignLevel] = AC.iPointer - AC.iBuffer; }
Definition at line 321 of file declare.h.
POPPREASSIGNLEVEL
#define POPPREASSIGNLEVEL
Value:
    if ( AP.PreAssignLevel > 0 ) { GETIDENTITY \
    AC.iPointer = AC.iBuffer + AP.PreAssignStack[AP.PreAssignLevel--]; \
    AP.PreContinuation = *--AT.WorkPointer; \
    *AC.iPointer = 0; }
Definition at line 331 of file declare.h.
EXTERNLOCK
#define EXTERNLOCK (x)
NOTE: We have replaced LOCK(ErrorMessageLock) and UNLOCK(ErrorMessageLock) by MLOCK(ErrorMessageLock) and MUNLOCK(ErrorMessageLock). They are used for the synchronised output in ParFORM. (TU 28 May 2011)
Definition at line 477 of file declare.h.
INILOCK
#define INILOCK (x)
Definition at line 478 of file declare.h.
LOCK
#define LOCK (x)
Definition at line 479 of file declare.h.
UNLOCK
#define UNLOCK (x)
Definition at line 480 of file declare.h.
EXTERNRWLOCK
#define EXTERNRWLOCK (x)
Definition at line 481 of file declare.h.
INIRWLOCK
#define INIRWLOCK (x)
Definition at line 482 of file declare.h.
RWLOCKR
#define RWLOCKR (x)
Definition at line 483 of file declare.h.
RWLOCKW
#define RWLOCKW (x)
Definition at line 484 of file declare.h.
UNRWLOCK
#define UNRWLOCK (x)
Definition at line 485 of file declare.h.
MLOCK
#define MLOCK (x)
Definition at line 490 of file declare.h.
MUNLOCK
#define MUNLOCK (x)
Definition at line 491 of file declare.h.
GETIDENTITY
#define GETIDENTITY
Definition at line 493 of file declare.h.
GETBIDENTITY
#define GETBIDENTITY
Definition at line 494 of file declare.h.
M_alloc
#define M_alloc (x) malloc((size_t)(x))
Definition at line 1009 of file declare.h.
CompareTerms
#define CompareTerms ((COMPARE)AR.CompareRoutine)
Definition at line 1489 of file declare.h.
FiniShuffle
#define FiniShuffle AN.SHvar.finishuf
Definition at line 1490 of file declare.h.
DoShtuffle
#define DoShtuffle ((DO_UFFLE)AN.SHvar.do_uffle)
Definition at line 1491 of file declare.h.
Typedef Documentation
WRITEBUFTOEXTCHANNEL
typedef int(* WRITEBUFTOEXTCHANNEL) (char *, size_t)
Definition at line 1482 of file declare.h.
GETCFROMEXTCHANNEL
typedef int(* GETCFROMEXTCHANNEL) (VOID)
Definition at line 1483 of file declare.h.
SETTERMINATORFOREXTERNALCHANNEL
typedef int(* SETTERMINATORFOREXTERNALCHANNEL) (char *)
Definition at line 1484 of file declare.h.
SETKILLMODEFOREXTERNALCHANNEL
typedef int(* SETKILLMODEFOREXTERNALCHANNEL) (int, int)
Definition at line 1485 of file declare.h.
WRITEFILE
typedef LONG(* WRITEFILE) (int, UBYTE *, LONG)
Definition at line 1486 of file declare.h.
GETTERM
typedef WORD(* GETTERM) (PHEAD WORD *)
Definition at line 1487 of file declare.h.
Function Documentation
TELLFILE()
VOID TELLFILE (int handle, POSITION * position) extern
Definition at line 1406 of file tools.c.
StartVariables()
VOID StartVariables (VOID) extern
All functions (well, nearly all) are declared here.
Definition at line 905 of file startup.c.
References AddNtoC(), AddRHS(), Compare1(), inicbufs(), FuNcTiOn::name, PF_BroadcastNumber(), PutPreVar(), and FuNcTiOn::symmetric.
CodeToLine()
UBYTE * CodeToLine (WORD number, UBYTE * Out) extern
Definition at line 658 of file sch.c.
AddArrayIndex()
UBYTE * AddArrayIndex (WORD num, UBYTE * out) extern
Definition at line 696 of file sch.c.
FindInIndex()
INDEXENTRY * FindInIndex (WORD expr, FILEDATA * f, WORD par, WORD mode) extern
Definition at line 2665 of file store.c.
NextFileIndex()
INDEXENTRY * NextFileIndex (POSITION * indexpos) extern
Definition at line 2258 of file store.c.
PasteTerm()
WORD * PasteTerm (PHEAD WORD number, WORD * accum, WORD * position, WORD times, WORD divby) extern
Puts the term at position in the accumulator accum at position 'number+1'. if times > 0 the coefficient of this term is multiplied by times/divby.
Parameters
number The number of term fragments in accum that should be skipped
accum The accumulator of term fragments
position A position in (typically) a compiler buffer from where a (piece of a) term comes.
times Multiply the result by this
divby Divide the result by this.
This routine is typically used when we have to replace a (sub)expression pointer by a power of a (sub)expression. This uses mostly a binomial expansion and the new term is the old term multiplied one by one by terms of the new expression. The factors times and divby keep track of the binomial coefficient. Once this is complete, the routine FiniTerm will make the contents of the accumulator into a proper term that still needs to be normalized.
Definition at line 3002 of file proces.c.
Referenced by Generator().
StrCopy()
UBYTE * StrCopy (UBYTE * from, UBYTE * to) extern
Definition at line 67 of file sch.c.
WrtPower()
UBYTE * WrtPower (UBYTE * Out, WORD Power) extern
Definition at line 738 of file sch.c.
AccumGCD()
WORD AccumGCD (PHEAD UWORD * a, WORD * na, UWORD * b, WORD nb) extern
Definition at line 647 of file reken.c.
AddArgs()
VOID AddArgs (PHEAD WORD * s1, WORD * s2, WORD * m) extern
Adds the arguments of two occurrences of the PolyFun.
Parameters
s1 Pointer to the first occurrence.
s2 Pointer to the second occurrence.
m Pointer to where the answer should be.
Definition at line 2313 of file sort.c.
Referenced by AddPoly(), and MergePatches().
AddCoef()
WORD AddCoef (PHEAD WORD ** ps1, WORD ** ps2) extern
Adds the coefficients of the terms *ps1 and *ps2. The problem comes when there is not enough space for a new longer coefficient. First a local solution is tried. If this is not successful we need to move terms around. The possibility of a garbage collection should not be ignored, as avoiding this costs very much extra space which is nearly wasted otherwise.
If the return value is zero the terms cancelled.
The resulting term is left in *ps1.
Definition at line 2012 of file sort.c.
References GarbHand(), and NormalModulus().
Referenced by SplitMerge().
AddLong()
WORD AddLong (UWORD * a, WORD na, UWORD * b, WORD nb, UWORD * c, WORD * nc) extern
Definition at line 705 of file reken.c.
AddPLon()
WORD AddPLon (UWORD * a, WORD na, UWORD * b, WORD nb, UWORD * c, WORD * nc) extern
Definition at line 750 of file reken.c.
AddPoly()
WORD AddPoly (PHEAD WORD ** ps1, WORD ** ps2) extern
Routine should be called when S->PolyWise != 0. It points then to the position of AR.PolyFun in both terms.
We add the contents of the arguments of the two polynomials. Special attention has to be given to special arguments. We have to reserve a space equal to the size of one term + the size of the argument of the other. The addition has to be done in this routine because not all objects are reentrant.
Newer addition (12-nov-2007). The PolyFun can have two arguments. In that case S->PolyFlag is 2 and we have to call the routine for adding rational polynomials. We have to be rather careful what happens with: The location of the output The order of the terms in the arguments At first we allow only univariate polynomials in the PolyFun. This restriction will be lifted a.s.a.p.
Parameters
ps1 A pointer to the position of the first term
ps2 A pointer to the position of the second term
Returns
If zero the terms cancel. Otherwise the new term is in *ps1.
Definition at line 2141 of file sort.c.
References AddArgs(), GarbHand(), and poly_ratfun_add().
Referenced by SplitMerge().
AddRat()
WORD AddRat (PHEAD UWORD * a, WORD na, UWORD * b, WORD nb, UWORD * c, WORD * nc) extern
Definition at line 210 of file reken.c.
AddToLine()
VOID AddToLine (UBYTE * s) extern
Definition at line 82 of file sch.c.
AddWild()
WORD AddWild (PHEAD WORD, WORD type, WORD newnumber) extern
Definition at line 1544 of file wildcard.c.
BigLong()
WORD BigLong (UWORD * a, WORD na, UWORD * b, WORD nb) extern
Definition at line 944 of file reken.c.
BinomGen()
WORD BinomGen (PHEAD WORD * term, WORD level, WORD ** tstops, WORD x1, WORD x2, WORD pow1, WORD pow2, WORD sign, UWORD * coef, WORD ncoef) extern
Definition at line 320 of file ratio.c.
CheckWild()
WORD CheckWild (PHEAD WORD, WORD type, WORD newnumber, WORD * newval) extern
Definition at line 1791 of file wildcard.c.
Chisholm()
WORD Chisholm (PHEAD WORD * term, WORD level) extern
Definition at line 1963 of file opera.c.
CleanExpr()
WORD CleanExpr (WORD par) extern
Definition at line 47 of file execute.c.
CleanUp()
VOID CleanUp (WORD par) extern
Definition at line 1759 of file startup.c.
ClearWild()
VOID ClearWild (PHEAD0) extern
Definition at line 1518 of file wildcard.c.
CompareFunctions()
WORD CompareFunctions (WORD * fleft, WORD * fright) extern
Definition at line 54 of file normal.c.
Commute()
WORD Commute (WORD * fleft, WORD * fright) extern
Definition at line 118 of file normal.c.
DetCommu()
WORD DetCommu (WORD * terms) extern
Definition at line 4493 of file normal.c.
DoesCommu()
WORD DoesCommu (WORD * term) extern
Definition at line 4552 of file normal.c.
CompArg()
int CompArg (WORD * s1, WORD * s2) extern
Definition at line 3307 of file tools.c.
CompCoef()
WORD CompCoef (WORD * term1, WORD * term2) extern
Routine takes a1 mod m1 and a2 mod m2 and returns a mod m1*m2 with
a mod m1 = a1 and a mod m2 = a2
Chinese remainder: a%(m1*m2) = q1*m1+a1 a%(m1*m2) = q2*m2+a2 Compute n1 such that (n1*m1)m2 is one Compute n2 such that (n2*m2)m1 is one Then (a1*n2*m2+a2*n1*m1)%(m1*m2) is a%(m1*m2)
Definition at line 3047 of file reken.c.
Referenced by Compare1().
CompGroup()
WORD CompGroup (PHEAD WORD, WORD ** args, WORD * a1, WORD * a2, WORD num) extern
Definition at line 373 of file function.c.
Compare1()
WORD Compare1 (PHEAD WORD * term1, WORD * term2, WORD level) extern
Compares two terms. The answer is: 0 equal (with exception of the coefficient if level == 0.) >0 term1 comes first. <0 term2 comes first. Some special precautions may be needed to keep the CompCoef routine from generating overflows, although this is very unlikely in subterms. This routine should not return an error condition.
Originally this routine was called Compare. With the treatment of special polynomials with terms that contain only symbols and the need for extreme speed for the polynomial routines we made a special compare routine and now we store the address of the current compare routine in AR.CompareRoutine and have a macro Compare which makes all existing code work properly and we can just replace the routine on a thread by thread basis (each thread has its own AR struct).
Parameters
term1 First input term
term2 Second input term
level The sorting level (may influence on the result)
Returns
0 equal (with exception of the coefficient if level == 0.) >0 term1 comes first. <0 term2 comes first.
When there are floating point numbers active (float_ = FLOATFUN) the presence of one or more float_ functions is returned in AT.SortFloatMode: 0: no float_ 1: float_ in term1 only 2: float_ in term2 only 3: float_ in both terms
Definition at line 2606 of file sort.c.
References CompCoef().
Referenced by InFunction(), poly_sort(), and StartVariables().
CountDo()
WORD CountDo (WORD * term, WORD * instruct) extern
Definition at line 552 of file reshuf.c.
CountFun()
WORD CountFun (WORD * term, WORD * countfun) extern
Definition at line 706 of file reshuf.c.
DimensionSubterm()
WORD DimensionSubterm (WORD * subterm) extern
Definition at line 867 of file reshuf.c.
DimensionTerm()
WORD DimensionTerm (WORD * term) extern
Definition at line 968 of file reshuf.c.
DimensionExpression()
WORD DimensionExpression (PHEAD WORD * expr) extern
Definition at line 1000 of file reshuf.c.
Deferred()
WORD Deferred (PHEAD WORD * term, WORD level) extern
Picks up the deferred brackets. These are the bracket contents of which we postpone the reading when we use the 'Keep Brackets' statement. These contents are multiplying the terms just before they are sent to the sorting system. Special attention goes to having it thread-safe We have to lock positioning the file and reading it in a thread specific buffer.
Parameters
term The term that must be multiplied by the contents of the current bracket
level The compiler level. This is needed because after multiplying term by term we call Generator again.
Definition at line 4836 of file proces.c.
References Generator(), and InsertTerm().
Referenced by Generator().
DeleteStore()
WORD DeleteStore (WORD par) extern
Definition at line 773 of file store.c.
DetCurDum()
WORD DetCurDum (PHEAD WORD * t) extern
Definition at line 252 of file reshuf.c.
DetVars()
VOID DetVars (WORD * term, WORD par) extern
Definition at line 1830 of file store.c.
Distribute()
WORD Distribute (DISTRIBUTE * d, WORD first) extern
Definition at line 509 of file symmetr.c.
DivLong()
WORD DivLong (UWORD * a, WORD na, UWORD * b, WORD nb, UWORD * c, WORD * nc, UWORD * d, WORD * nd) extern
Definition at line 972 of file reken.c.
DivRat()
WORD DivRat (PHEAD UWORD * a, WORD na, UWORD * b, WORD nb, UWORD * c, WORD * nc) extern
Definition at line 500 of file reken.c.
Divvy()
WORD Divvy (PHEAD UWORD * a, WORD * na, UWORD * b, WORD nb) extern
Definition at line 172 of file reken.c.
DoDelta()
WORD DoDelta (WORD * t) extern
Definition at line 4338 of file normal.c.
DoDelta3()
WORD DoDelta3 (PHEAD WORD * term, WORD level) extern
Definition at line 1405 of file reshuf.c.
TestPartitions()
WORD TestPartitions (WORD * tfun, PARTI * parti) extern
Definition at line 1607 of file reshuf.c.
DoPartitions()
WORD DoPartitions (PHEAD WORD * term, WORD level) extern
Definition at line 1722 of file reshuf.c.
CoCanonicalize()
int CoCanonicalize (UBYTE * s) extern
Definition at line 64 of file diagrams.c.
DoCanonicalize()
int DoCanonicalize (PHEAD WORD * term, WORD * params) extern
Definition at line 185 of file diagrams.c.
GenTopologies()
WORD GenTopologies (PHEAD WORD * term, WORD level) extern
Definition at line 962 of file diawrap.cc.
GenDiagrams()
WORD GenDiagrams (PHEAD WORD * term, WORD level) extern
Definition at line 732 of file diawrap.cc.
DoTopologyCanonicalize()
int DoTopologyCanonicalize (PHEAD WORD * term, WORD vert, WORD edge, WORD * args) extern
Definition at line 417 of file diagrams.c.
DoShattering()
int DoShattering (PHEAD WORD * connect, WORD * environ, WORD * partitions, WORD nvert) extern
Definition at line 626 of file diagrams.c.
GenerateTopologies()
WORD GenerateTopologies (PHEAD WORD, WORD nlegs, WORD setvert, WORD setmax) extern
Definition at line 123 of file topowrap.cc.
DoTableExpansion()
WORD DoTableExpansion (WORD * term, WORD level) extern
Definition at line 334 of file tables.c.
DoDistrib()
WORD DoDistrib (PHEAD WORD * term, WORD level) extern
Definition at line 1119 of file reshuf.c.
DoShuffle()
WORD DoShuffle (WORD * term, WORD level, WORD fun, WORD option) extern
Definition at line 2095 of file reshuf.c.
DoPermutations()
WORD DoPermutations (PHEAD WORD * term, WORD level) extern
Definition at line 2007 of file reshuf.c.
Shuffle()
int Shuffle (WORD * from1, WORD * from2, WORD * to) extern
Definition at line 2229 of file reshuf.c.
FinishShuffle()
int FinishShuffle (WORD * fini) extern
Definition at line 2421 of file reshuf.c.
DoStuffle()
WORD DoStuffle (WORD * term, WORD level, WORD fun, WORD option) extern
Definition at line 2487 of file reshuf.c.
Stuffle()
int Stuffle (WORD * from1, WORD * from2, WORD * to) extern
Definition at line 2702 of file reshuf.c.
FinishStuffle()
int FinishStuffle (WORD * fini) extern
Definition at line 2829 of file reshuf.c.
StuffRootAdd()
WORD * StuffRootAdd (WORD * t1, WORD * t2, WORD * to) extern
Definition at line 2876 of file reshuf.c.
TestUse()
WORD TestUse (WORD * term, WORD level) extern
Definition at line 1414 of file tables.c.
FindTB()
DBASE * FindTB (UBYTE * name) extern
Definition at line 734 of file tables.c.
CheckTableDeclarations()
int CheckTableDeclarations (DBASE * d) extern
Definition at line 1178 of file tables.c.
Apply()
WORD Apply (WORD * term, WORD level) extern
Definition at line 1980 of file tables.c.
ApplyExec()
int ApplyExec (WORD * term, int maxtogo, WORD level) extern
Definition at line 2039 of file tables.c.
ApplyReset()
WORD ApplyReset (WORD level) extern
Definition at line 2256 of file tables.c.
TableReset()
WORD TableReset (VOID) extern
Definition at line 2292 of file tables.c.
ReWorkT()
VOID ReWorkT (WORD * term, WORD * funs, WORD numfuns) extern
Definition at line 1899 of file tables.c.
GetIfDollarNum()
WORD GetIfDollarNum (WORD * ifp, WORD * ifstop) extern
Definition at line 106 of file if.c.
FindVar()
int FindVar (WORD * v, WORD * term) extern
Definition at line 173 of file if.c.
DoIfStatement()
WORD DoIfStatement (PHEAD WORD * ifcode, WORD * term) extern
Definition at line 280 of file if.c.
DoOnePow()
WORD DoOnePow (PHEAD WORD * term, WORD power, WORD nexp, WORD * accum, WORD * aa, WORD level, WORD * freeze) extern
Routine gets one power of an expression in the scratch system. If there are more powers needed there will be a recursion.
No attempt is made to use binomials because we have no information about commuting properties.
There is a searching for the contents of brackets if needed. This searching may be rather slow because of the single links.
Parameters
term is the term we are adding to.
power is the power of the expression that we need.
nexp is the number of the expression.
accum is the accumulator of terms. It accepts the termfragments that are made into a proper term in FiniTerm
aa points to the start of the entire accumulator. In *aa we store the number of term fragments that are in the accumulator.
level is the current depth in the tree of statements. It is needed to continue to the next operation/substitution with each generated term
freeze is the pointer to the bracket information that should be matched.
Definition at line 4615 of file proces.c.
References DoOnePow(), FiniTerm(), Generator(), and FiLe::handle.
Referenced by DoOnePow(), and Generator().
DoRevert()
void DoRevert (WORD * fun, WORD * tmp) extern
Definition at line 4405 of file normal.c.
DoSumF1()
WORD DoSumF1 (PHEAD WORD * term, WORD * params, WORD replac, WORD level) extern
Definition at line 395 of file ratio.c.
DoSumF2()
WORD DoSumF2 (PHEAD WORD * term, WORD * params, WORD replac, WORD level) extern
Definition at line 520 of file ratio.c.
DoTheta()
WORD DoTheta (PHEAD WORD * t) extern
Definition at line 4241 of file normal.c.
EndSort()
LONG EndSort (PHEAD WORD * buffer, int par) extern
Finishes a sort. At AR.sLevel == 0 the output is to the regular output stream. When AR.sLevel > 0, the parameter par determines the actual output. The AR.sLevel will be popped. All ongoing stages are finished and if the sortfile is open it is closed. The statistics are printed when AR.sLevel == 0 par == 0 Output to the buffer. par == 1 Sort for function arguments. The output will be copied into the buffer. It is assumed that this is in the WorkSpace. par == 2 Sort for $-variable. We return the address of the buffer that contains the output in buffer (treated like WORD **). We first catch the output in a file (unless we can intercept things after the small buffer has been sorted) Then we read from the file into a buffer. Only when par == 0 data compression can be attempted at AT.SS==AT.S0.
Parameters
buffer buffer for output when needed
par See above
Returns
If negative: error. If positive: number of words in output.
Definition at line 704 of file sort.c.
References ComPress(), FlushOut(), MergePatches(), PF_EndSort(), PutOut(), SplitMerge(), StageSort(), and WriteStats().
Referenced by generate_expression(), get_expression(), InFunction(), MakeDollarInteger(), MakeDollarMod(), PF_CollectModifiedDollars(), PF_Processor(), poly_factorize_expression(), poly_sort(), poly_unfactorize_expression(), PolyFunMul(), Processor(), TakeArgContent(), and TestMatch().
EntVar()
WORD EntVar (WORD type, UBYTE * name, WORD x, WORD y, WORD z, WORD d) extern
Definition at line 557 of file names.c.
EpfCon()
WORD EpfCon (PHEAD WORD * term, WORD * params, WORD num, WORD level) extern
Definition at line 212 of file opera.c.
EpfFind()
WORD EpfFind (PHEAD WORD * term, WORD * params) extern
Definition at line 58 of file opera.c.
EpfGen()
WORD EpfGen (WORD number, WORD * inlist, WORD * kron, WORD * perm, WORD sgn) extern
Definition at line 282 of file opera.c.
EqualArg()
WORD EqualArg (WORD * parms, WORD num1, WORD num2) extern
Definition at line 1379 of file reshuf.c.
Factorial()
int Factorial (PHEAD WORD, UWORD * a, WORD * na) extern
Definition at line 3449 of file reken.c.
Bernoulli()
int Bernoulli (WORD n, UWORD * a, WORD * na) extern
Definition at line 3529 of file reken.c.
FactorIn()
int FactorIn (PHEAD WORD * term, WORD level) extern
Definition at line 46 of file factor.c.
FactorInExpr()
int FactorInExpr (PHEAD WORD * term, WORD level) extern
Definition at line 421 of file factor.c.
FindAll()
WORD FindAll (PHEAD WORD * term, WORD * pattern, WORD level, WORD * par) extern
Definition at line 1197 of file pattern.c.
FindMulti()
WORD FindMulti (PHEAD WORD * term, WORD * pattern) extern
Definition at line 954 of file findpat.c.
FindOnce()
WORD FindOnce (PHEAD WORD * term, WORD * pattern) extern
Definition at line 419 of file findpat.c.
FindOnly()
WORD FindOnly (PHEAD WORD * term, WORD * pattern) extern
Definition at line 61 of file findpat.c.
FindRest()
WORD FindRest (PHEAD WORD * term, WORD * pattern) extern
Definition at line 1070 of file findpat.c.
FindrNumber()
WORD FindrNumber (WORD n, VARRENUM * v) extern
Definition at line 2588 of file store.c.
FiniLine()
VOID FiniLine (VOID) extern
Definition at line 182 of file sch.c.
FiniTerm()
WORD FiniTerm (PHEAD WORD * term, WORD * accum, WORD * termout, WORD number, WORD tepos) extern
Concatenates the contents of the accumulator into a single legal term, which replaces the subexpression pointer
Parameters
term the input term with the (sub)expression subterm
accum the accumulator with the term fragments
termout the location where the output should be written
number the number of term fragments in the accumulator
tepos the position of the subterm in term to be replaced
Definition at line 3067 of file proces.c.
Referenced by DoOnePow(), and Generator().
FlushOut()
WORD FlushOut (POSITION * position, FILEHANDLE * fi, int compr) extern
Completes output to an output file and writes the trailing zero.
Parameters
position The position in the file after writing
fi The file (or its cache)
compr Indicates whether there should be compression with gzip.
Returns
Regular conventions (OK -> 0).
Definition at line 1798 of file sort.c.
References FiLe::handle, BrAcKeTiNfO::indexbuffer, and PF_ISendSbuf().
Referenced by EndSort(), MergePatches(), PF_EndSort(), and Processor().
FunLevel()
VOID FunLevel (PHEAD WORD * term) extern
Definition at line 130 of file reshuf.c.
AdjustRenumScratch()
VOID AdjustRenumScratch (PHEAD0) extern
Definition at line 506 of file reshuf.c.
GarbHand()
VOID GarbHand (VOID) extern
Garbage collection that takes place when the small extension is full and we need to place more terms there. When this is the case there are many holes in the small buffer and the whole can be compactified. The major complication is the buffer for SplitMerge. There are to options for temporary memory: 1: find some buffer that has enough space (maybe in the large buffer). 2: allocate a buffer. Give it back afterwards of course. If the small extension is properly dimensioned this routine should be called very rarely. Most of the time it will be called when the polyfun or polyratfun is active.
Definition at line 3612 of file sort.c.
Referenced by AddCoef(), and AddPoly().
GcdLong()
WORD GcdLong (PHEAD UWORD * a, WORD na, UWORD * b, WORD nb, UWORD * c, WORD * nc) extern
Definition at line 2276 of file reken.c.
LcmLong()
WORD LcmLong (PHEAD UWORD * a, WORD na, UWORD * b, WORD nb, UWORD * c, WORD * nc) extern
Definition at line 2701 of file reken.c.
Generator()
WORD Generator (PHEAD WORD * term, WORD level) extern
The heart of the program. Here the expansion tree is set up in one giant recursion
Parameters
term the input term. may be overwritten
level the level in the compiler buffer (number of statement)
Returns
Normal conventions (OK = 0).
The routine looks first whether there are unsubstituted (sub)expressions. If so, one of them gets inserted term by term and the new term is used in a renewed call to Generator. If there are no (sub)expressions, the term is normalized, the compiler level is raised (next statement) and the program looks what type of statement this is. If this is a special statement it is either treated on the spot or the appropriate routine is called. If it is a substitution, the pattern matcher is called (TestMatch) which tells whether there was a match. If so we need to call TestSub again to test for (sub)expressions. If we run out of levels, the term receives a final treatment for modulus calculus and/or brackets and is then sent off to the sorting routines.
Definition at line 3266 of file proces.c.
References Deferred(), DoOnePow(), FiniTerm(), Generator(), InFunction(), InsertTerm(), CbUf::lhs, VaRrEnUm::lo, PasteFile(), PasteTerm(), PF_Deferred(), CbUf::Pointer, PolyFunMul(), PrepPoly(), PutPreVar(), CbUf::rhs, StoreTerm(), ReNuMbEr::symb, and TestMatch().
Referenced by Deferred(), DoOnePow(), generate_expression(), Generator(), InFunction(), MakeDollarInteger(), MakeDollarMod(), PF_CollectModifiedDollars(), PF_Deferred(), PF_Processor(), poly_factorize_expression(), poly_unfactorize_expression(), Processor(), and TestMatch().
GetBinom()
WORD GetBinom (UWORD * a, WORD * na, WORD i1, WORD i2) extern
Definition at line 2667 of file reken.c.
GetFromStore()
WORD GetFromStore (WORD * to, POSITION * position, RENUMBER renumber, WORD * InCompState, WORD nexpr) extern
Definition at line 1629 of file store.c.
GetLong()
WORD GetLong (UBYTE * s, UWORD * a, WORD * na) extern
Definition at line 1774 of file reken.c.
GetMoreTerms()
WORD GetMoreTerms (WORD * term) extern
Definition at line 1426 of file store.c.
GetMoreFromMem()
WORD GetMoreFromMem (WORD * term, WORD ** tpoin) extern
Definition at line 1522 of file store.c.
GetOneTerm()
WORD GetOneTerm (PHEAD WORD * term, FILEHANDLE * fi, POSITION * pos, int par) extern
Definition at line 1268 of file store.c.
GetTable()
RENUMBER GetTable (WORD expr, POSITION * position, WORD mode) extern
Definition at line 2826 of file store.c.
GetTerm()
WORD GetTerm (PHEAD WORD * term) extern
Definition at line 993 of file store.c.
Glue()
WORD Glue (PHEAD WORD * term1, WORD * term2, WORD * sub, WORD insert) extern
Definition at line 461 of file ratio.c.
InFunction()
WORD InFunction (PHEAD WORD * term, WORD * termout) extern
Makes the replacement of the subexpression with the number 'replac' in a function argument. Additional information is passed in some of the AR, AN, AT variables.
Parameters
term The input term
termout The output term
Returns
0: everything is fine, Negative: fatal, Positive: error.
Special attention should be given to nested functions!
Definition at line 2174 of file proces.c.
References Compare1(), CompareSymbols(), EndSort(), Generator(), LowerSortLevel(), NewSort(), StoreTerm(), and SymbolNormalize().
Referenced by Generator().
IniLine()
VOID IniLine (WORD extrablank) extern
Definition at line 267 of file sch.c.
IniVars()
WORD IniVars (VOID) extern
Definition at line 1354 of file startup.c.
InsertTerm()
WORD InsertTerm (PHEAD WORD * term, WORD replac, WORD extractbuff, WORD * position, WORD * termout, WORD tepos) extern
Puts the terms 'term' and 'position' together into a single legal term in termout. replac is the number of the subexpression that should be replaced. It must be a positive term. When action is needed in the argument of a function all terms in that argument are dealt with recursively. The subexpression is sorted. Only one subexpression is done at a time this way.
Parameters
term the input term
replac number of the subexpression pointer to replace
extractbuff number of the compiler buffer replac refers to
position position from where to take the term in the compiler buffer
termout the output term
tepos offset in term where the subexpression is.
Returns
Normal conventions (OK = 0).
Definition at line 2744 of file proces.c.
Referenced by Deferred(), Generator(), and PF_Deferred().
LongToLine()
VOID LongToLine (UWORD * a, WORD na) extern
Definition at line 303 of file sch.c.
MakeDirty()
WORD MakeDirty (WORD * term, WORD * x, WORD par) extern
Definition at line 51 of file function.c.
MarkDirty()
VOID MarkDirty (WORD * term, WORD flags) extern
Definition at line 97 of file function.c.
PolyFunDirty()
VOID PolyFunDirty (PHEAD WORD * term) extern
Definition at line 139 of file function.c.
PolyFunClean()
VOID PolyFunClean (PHEAD WORD * term) extern
Definition at line 174 of file function.c.
MakeModTable()
WORD MakeModTable (VOID) extern
Definition at line 3363 of file reken.c.
MatchE()
WORD MatchE (PHEAD WORD * pattern, WORD * fun, WORD * inter, WORD par) extern
Definition at line 56 of file symmetr.c.
MatchCy()
int MatchCy (PHEAD WORD * pattern, WORD * fun, WORD * inter, WORD par) extern
Definition at line 570 of file symmetr.c.
FunMatchCy()
int FunMatchCy (PHEAD WORD * pattern, WORD * fun, WORD * inter, WORD par) extern
Definition at line 1066 of file symmetr.c.
FunMatchSy()
int FunMatchSy (PHEAD WORD * pattern, WORD * fun, WORD * inter, WORD par) extern
Definition at line 1524 of file symmetr.c.
MatchArgument()
int MatchArgument (PHEAD WORD * arg, WORD * pat) extern
Definition at line 2051 of file symmetr.c.
MatchFunction()
WORD MatchFunction (PHEAD WORD * pattern, WORD * interm, WORD * wilds) extern
Definition at line 817 of file function.c.
MergePatches()
WORD MergePatches (WORD par) extern
The general merge routine. Can be used for the large buffer and the file merging. The array S->Patches tells where the patches start S->pStop tells where they end (has to be computed first). The end of a 'line to be merged' is indicated by a zero. If the end is reached without running into a zero or a term runs over the boundary of a patch it is a file merging operation and a new piece from the file is read in.
Parameters
par If par == 0 the sort is for file -> outputfile. If par == 1 the sort is for large buffer -> sortfile. If par == 2 the sort is for large buffer -> outputfile.
Definition at line 3727 of file sort.c.
References AddArgs(), FlushOut(), FiLe::handle, NormalModulus(), poly_ratfun_add(), PutIn(), PutOut(), Sflush(), and StageSort().
Referenced by EndSort(), and StoreTerm().
MesCerr()
WORD MesCerr (char * s, UBYTE * t) extern
Definition at line 824 of file message.c.
MesComp()
WORD MesComp (char * s, UBYTE * p, UBYTE * q) extern
Definition at line 843 of file message.c.
Modulus()
WORD Modulus (WORD * term) extern
Definition at line 3102 of file reken.c.
MoveDummies()
VOID MoveDummies (PHEAD WORD * term, WORD shift) extern
Definition at line 436 of file reshuf.c.
MulLong()
WORD MulLong (UWORD * a, WORD na, UWORD * b, WORD nb, UWORD * c, WORD * nc) extern
Definition at line 841 of file reken.c.
MulRat()
WORD MulRat (PHEAD UWORD * a, WORD na, UWORD * b, WORD nb, UWORD * c, WORD * nc) extern
Definition at line 378 of file reken.c.
Mully()
WORD Mully (PHEAD UWORD * a, WORD * na, UWORD * b, WORD nb) extern
Definition at line 126 of file reken.c.
MultDo()
WORD MultDo (PHEAD WORD * term, WORD * pattern) extern
Definition at line 1044 of file reshuf.c.
NewSort()
WORD NewSort (PHEAD0) extern
Starts a new sort. At the lowest level this is a 'main sort' with the struct according to the parameters in S0. At higher levels this is a sort for functions, subroutines or dollars. We prepare the arrays and structs.
Returns
Regular convention (OK -> 0)
Definition at line 614 of file sort.c.
Referenced by generate_expression(), get_expression(), InFunction(), MakeDollarInteger(), MakeDollarMod(), PF_CollectModifiedDollars(), PF_Processor(), poly_factorize_expression(), poly_sort(), poly_unfactorize_expression(), PolyFunMul(), Processor(), TakeArgContent(), and TestMatch().
ExtraSymbol()
WORD ExtraSymbol (WORD sym, WORD pow, WORD nsym, WORD * ppsym, WORD * ncoef) extern
Definition at line 4179 of file normal.c.
Normalize()
WORD Normalize (PHEAD WORD * term) extern
Definition at line 193 of file normal.c.
BracketNormalize()
WORD BracketNormalize (PHEAD WORD * term) extern
Definition at line 5254 of file normal.c.
DropCoefficient()
VOID DropCoefficient (PHEAD WORD * term) extern
Definition at line 5079 of file normal.c.
DropSymbols()
VOID DropSymbols (PHEAD WORD * term) extern
Definition at line 5097 of file normal.c.
PutInside()
int PutInside (PHEAD WORD * term, WORD * code) extern
Definition at line 609 of file index.c.
OpenTemp()
WORD OpenTemp (VOID) extern
Definition at line 48 of file store.c.
Pack()
VOID Pack (UWORD * a, WORD * na, UWORD * b, WORD nb) extern
Definition at line 62 of file reken.c.
PasteFile()
LONG PasteFile (PHEAD WORD number, WORD * accum, POSITION * position, WORD ** accfill, RENUMBER renumber, WORD * freeze, WORD nexpr) extern
Gets a term from stored expression expr and puts it in the accumulator at position number. It returns the length of the term that came from file.
Parameters
number number of partial terms to skip in accum
accum the accumulator
position file position from where to get the stored term
accfill returns tail position in accum
renumber the renumber struct for the variables in the stored expression
freeze information about if we need only the contents of a bracket
nexpr the number of the stored expression
Returns
Normal conventions (OK = 0).
Definition at line 2880 of file proces.c.
Referenced by Generator().
Permute()
WORD Permute (PERM * perm, WORD first) extern
Definition at line 443 of file symmetr.c.
PermuteP()
WORD PermuteP (PERMP * perm, WORD first) extern
Definition at line 477 of file symmetr.c.
PolyFunMul()
WORD PolyFunMul (PHEAD WORD * term) extern
Multiplies the arguments of multiple occurrences of the polyfun. In this routine we do the original PolyFun with one argument only. The PolyRatFun (PolyFunType = 2) is done in a dedicated routine in the file polywrap.cc The new result is written over the old result.
Parameters
term It contains the input term and later the output.
Returns
Normal conventions (OK = 0).
Definition at line 5352 of file proces.c.
References EndSort(), LowerSortLevel(), NewSort(), poly_ratfun_normalize(), and StoreTerm().
Referenced by Generator().
PopVariables()
WORD PopVariables (VOID) extern
Definition at line 211 of file execute.c.
PrepPoly()
WORD PrepPoly (PHEAD WORD * term, WORD par) extern
Routine checks whether the count of function AR.PolyFun is zero or one. If it is one and it has one scalarlike argument the coefficient of the term is pulled inside the argument. If the count is zero a new function is made with the coefficient as its only argument. The function should be placed at its proper position.
When this function is active it places the PolyFun as last object before the coefficient. This is needed because otherwise the compress algorithm has problems in MergePatches.
The bracket routine should also place the PolyFun at a comparable spot. The compression should then stop at the PolyFun. It doesn't really have to stop when writing the final result but this may be too complicated.
The parameter par tells whether we are at groundlevel or inside a function or dollar variable.
Definition at line 4964 of file proces.c.
References poly_ratfun_normalize().
Referenced by Generator().
Processor()
WORD Processor (VOID) extern
This is the central processor. It accepts a stream of Expressions which is accessed by calls to GetTerm. The expressions reside either in AR.infile or AR.hidefile The definitions of an expression are seen as an id-statement, so the primary Expressions should be written to the system of scratch files as single terms with an expression pointer. Each expression is terminated with a zero and the whole is terminated by two zeroes.
The routine DoExecute should determine whether results are to be printed, should revert the scratch I/O directions etc. In principle it is DoExecute that calls Processor.
Returns
if everything OK: 0. Otherwise error. The preprocessor may continue with compilation though. Really fatal errors should return on the spot by calling Terminate.
Definition at line 64 of file proces.c.
References CbUf::Buffer, EndSort(), FlushOut(), Generator(), CbUf::lhs, LowerSortLevel(), NewSort(), PF_BroadcastRHS(), PF_InParallelProcessor(), PF_Processor(), CbUf::Pointer, poly_factorize_expression(), poly_unfactorize_expression(), PutOut(), CbUf::rhs, and StoreTerm().
Product()
WORD Product (UWORD * a, WORD * na, WORD b) extern
Definition at line 1585 of file reken.c.
PrtLong()
VOID PrtLong (UWORD * a, WORD na, UBYTE * s) extern
Definition at line 1712 of file reken.c.
PrtTerms()
VOID PrtTerms (VOID) extern
Definition at line 716 of file sch.c.
PrintDeprecation()
void PrintDeprecation (const char * feature, const char * issue) extern
Prints a deprecation warning for a given feature.
Parameters
feature The name of the deprecated feature.
issue The associated issue, e.g., "issues/700".
Definition at line 2061 of file startup.c.
PrintRunningTime()
VOID PrintRunningTime (VOID) extern
Definition at line 2085 of file startup.c.
GetRunningTime()
LONG GetRunningTime (VOID) extern
Definition at line 2126 of file startup.c.
PutBracket()
WORD PutBracket (PHEAD WORD * termin) extern
Definition at line 1111 of file execute.c.
PutIn()
LONG PutIn (FILEHANDLE * file, POSITION * position, WORD * buffer, WORD ** take, int npat) extern
Reads a new patch from position in file handle. It is put at buffer, anything after take is moved forward. This would be part of a term that hasn't been used yet. Because of this there should be some space before the start of the buffer
Parameters
file The file system from which to read
position The position from which to read
buffer The buffer into which to read
take The unused tail should be moved before the buffer
npat The number of the patch. Is needed if the information was compressed with gzip, because each patch has its own independent gzip encoding.
Definition at line 1290 of file sort.c.
References FiLe::handle.
Referenced by MergePatches().
PutInStore()
WORD PutInStore (INDEXENTRY * ind, WORD num) extern
Definition at line 874 of file store.c.
PutOut()
WORD PutOut (PHEAD WORD * term, POSITION * position, FILEHANDLE * fi, WORD ncomp) extern
Routine writes one term to file handle at position. It returns the new value of the position.
NOTE: For 'final output' we may have to index the brackets. See the struct BRACKETINDEX. We should maintain: 1: a list with brackets array with the brackets 2: a list of objects of type BRACKETINDEX. It contains array with either pointers or offsets to the list of brackets. starting positions in the file. The index may be tied to a maximum size. In that case we may have to prune the list occasionally.
Parameters
term The term to be written
position The position in the file. Afterwards it is updated
fi The file (or its cache) to which should be written
ncomp Information about what type of compression should be used
Definition at line 1436 of file sort.c.
References FiLe::handle, and PF_ISendSbuf().
Referenced by EndSort(), generate_expression(), MergePatches(), PF_EndSort(), PF_Processor(), and Processor().
Quotient()
UWORD Quotient (UWORD * a, WORD * na, WORD b) extern
Definition at line 1620 of file reken.c.
RaisPow()
WORD RaisPow (PHEAD UWORD * a, WORD * na, UWORD b) extern
Definition at line 1228 of file reken.c.
RaisPowCached()
VOID RaisPowCached (PHEAD WORD x, WORD n, UWORD ** c, WORD * nc) extern
Computes power x^n and caches the value
Description
Calculates the power x^n and stores the results for caching purposes. The pointer c (i.e., the pointer, and not what it points to) is overwritten. What it points to should not be overwritten in the calling function.
Notes
Caching is done in AT.small_power[]. This array is extended if necessary.
Definition at line 1296 of file reken.c.
Referenced by poly::divmod_heap(), poly::divmod_univar(), and poly::mul_heap().
RaisPowMod()
WORD RaisPowMod (WORD x, WORD n, WORD m) extern
Definition at line 1383 of file reken.c.
NormalModulus()
int NormalModulus (UWORD * a, WORD * na) extern
Brings a modular representation in the range -p/2 to +p/2 The return value tells whether anything was done. Routine made in the general modulus revamp of July 2008 (JV).
Definition at line 1403 of file reken.c.
Referenced by AddCoef(), and MergePatches().
MakeInverses()
int MakeInverses (VOID) extern
Makes a table of inverses in modular calculus The modulus is in AC.cmod and AC.ncmod One should notice that the table of inverses can only be made if the modulus fits inside a single FORM word. Otherwise the table lookup becomes too difficult and the table too long.
Definition at line 1440 of file reken.c.
References GetModInverses().
GetModInverses()
int GetModInverses (WORD m1, WORD m2, WORD * im1, WORD * im2) extern
Input m1 and m2, which are relative prime. determines a*m1+b*m2 = 1 (and 1 is the gcd of m1 and m2) then a*m1 = 1 mod m2 and hence im1 = a. and b*m2 = 1 mod m1 and hence im2 = b. Set m1 = 0*m1+1*m2 = a1*m1+b1*m2 m2 = 1*m1+0*m2 = a2*m1+b2*m2 If everything is OK, the return value is zero
Definition at line 1476 of file reken.c.
Referenced by poly::divmod_heap(), poly::divmod_univar(), MakeDollarMod(), MakeInverses(), MakeMod(), TakeContent(), and TakeSymbolContent().
GetLongModInverses()
int GetLongModInverses (PHEAD UWORD * a, WORD na, UWORD * b, WORD nb, UWORD * ia, WORD * nia, UWORD * ib, WORD * nib) extern
Definition at line 1508 of file reken.c.
RatToLine()
VOID RatToLine (UWORD * a, WORD na) extern
Definition at line 337 of file sch.c.
RatioFind()
WORD RatioFind (PHEAD WORD * term, WORD * params) extern
Definition at line 62 of file ratio.c.
RatioGen()
WORD RatioGen (PHEAD WORD * term, WORD * params, WORD num, WORD level) extern
Definition at line 170 of file ratio.c.
ReNumber()
WORD ReNumber (PHEAD WORD * term) extern
Definition at line 80 of file reshuf.c.
ReadSnum()
WORD ReadSnum (UBYTE ** p) extern
Definition at line 1973 of file tools.c.
Remain10()
WORD Remain10 (UWORD * a, WORD * na) extern
Definition at line 1659 of file reken.c.
Remain4()
WORD Remain4 (UWORD * a, WORD * na) extern
Definition at line 1686 of file reken.c.
ResetScratch()
WORD ResetScratch (VOID) extern
Definition at line 235 of file store.c.
ResolveSet()
WORD ResolveSet (PHEAD WORD * from, WORD * to, WORD * subs) extern
Definition at line 1361 of file wildcard.c.
RevertScratch()
WORD RevertScratch (VOID) extern
Definition at line 190 of file store.c.
ScanFunctions()
WORD ScanFunctions (PHEAD WORD * inpat, WORD * inter, WORD par) extern
Definition at line 1607 of file function.c.
SeekScratch()
VOID SeekScratch (FILEHANDLE * fi, POSITION * pos) extern
Definition at line 64 of file store.c.
SetEndScratch()
VOID SetEndScratch (FILEHANDLE * f, POSITION * position) extern
Definition at line 75 of file store.c.
SetEndHScratch()
VOID SetEndHScratch (FILEHANDLE * f, POSITION * position) extern
Definition at line 89 of file store.c.
SetFileIndex()
WORD SetFileIndex (VOID) extern
Reads the next file index and puts it into AR.StoreData.Index. TODO
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 2321 of file store.c.
References WriteStoreHeader().
Sflush()
WORD Sflush (FILEHANDLE * fi) extern
Puts the contents of a buffer to output Only to be used when there is a single patch in the large buffer.
Parameters
fi The filesystem (or its cache) to which the patch should be written
Definition at line 1350 of file sort.c.
References FiLe::handle.
Referenced by MergePatches().
Simplify()
WORD Simplify (PHEAD UWORD * a, WORD * na, UWORD * b, WORD * nb) extern
Definition at line 530 of file reken.c.
SortWild()
WORD SortWild (WORD * w, WORD nw) extern
Sorts the wildcard entries in the parameter w. Double entries are removed. Full space taken is nw words. Routine serves for the reading of wildcards in the compiler. The entries come in the format: (type,4,number,0) in which the zero is reserved for the future replacement of 'number'.
Parameters
w buffer with wildcard entries.
nw number of wildcard entries.
Returns
Normal conventions (OK -> 0)
Definition at line 4723 of file sort.c.
LocateBase()
FILE * LocateBase (char ** name, char ** newname, char * iomode) extern
Definition at line 225 of file minos.c.
SplitMerge()
LONG SplitMerge (PHEAD WORD ** Pointer, LONG number) extern
Algorithm by J.A.M.Vermaseren (31-7-1988)
Note that AN.SplitScratch and AN.InScratch are used also in GarbHand
Merge sort in memory. The input is an array of pointers. Sorting is done recursively by dividing the array in two equal parts and calling SplitMerge for each. When the parts are small enough we can do the compare and take the appropriate action. An addition is that we look for 'runs'. Sequences that are already ordered. This happens a lot when there is very little action in a module. This made FORM faster by a few percent.
Parameters
Pointer The array of pointers to the terms to be sorted.
number The number of pointers in Pointer.
The terms are supposed to be sitting in the small buffer and there is supposed to be an extension to this buffer for when there are two terms that should be added and the result takes more space than each of the original terms. The notation guarantees that the result never needs more space than the sum of the spaces of the original terms.
Definition at line 3332 of file sort.c.
References AddCoef(), AddPoly(), and SplitMerge().
Referenced by EndSort(), SplitMerge(), and StoreTerm().
StoreTerm()
WORD StoreTerm (PHEAD WORD * term) extern
The central routine to accept terms, store them and keep things at least partially sorted. A call to EndSort will then complete storing and sorting.
Parameters
term The term to be stored
Returns
Regular return conventions (OK -> 0)
Definition at line 4510 of file sort.c.
References ComPress(), MergePatches(), SplitMerge(), and WriteStats().
Referenced by Generator(), get_expression(), InFunction(), PF_Processor(), poly_sort(), PolyFunMul(), Processor(), and TakeArgContent().
SubPLon()
VOID SubPLon (UWORD * a, WORD na, UWORD * b, WORD nb, UWORD * c, WORD * nc) extern
Definition at line 803 of file reken.c.
Substitute()
VOID Substitute (PHEAD WORD * term, WORD * pattern, WORD power) extern
Definition at line 640 of file pattern.c.
SymFind()
WORD SymFind (PHEAD WORD * term, WORD * params) extern
Definition at line 633 of file function.c.
SymGen()
WORD SymGen (PHEAD WORD * term, WORD * params, WORD num, WORD level) extern
Definition at line 518 of file function.c.
Symmetrize()
WORD Symmetrize (PHEAD WORD * func, WORD * Lijst, WORD ngroups, WORD gsize, WORD type) extern
Definition at line 213 of file function.c.
FullSymmetrize()
int FullSymmetrize (PHEAD WORD * fun, int type) extern
Definition at line 473 of file function.c.
TakeModulus()
WORD TakeModulus (UWORD * a, WORD * na, UWORD * cmodvec, WORD ncmod, WORD par) extern
Definition at line 3149 of file reken.c.
TakeNormalModulus()
WORD TakeNormalModulus (UWORD * a, WORD * na, UWORD * c, WORD nc, WORD par) extern
Definition at line 3321 of file reken.c.
TalToLine()
VOID TalToLine (UWORD x) extern
Definition at line 522 of file sch.c.
TenVec()
WORD TenVec (PHEAD WORD * term, WORD * params, WORD num, WORD level) extern
Definition at line 2312 of file opera.c.
TenVecFind()
WORD TenVecFind (PHEAD WORD * term, WORD * params) extern
Definition at line 2178 of file opera.c.
TermRenumber()
WORD TermRenumber (WORD * term, RENUMBER renumber, WORD nexpr) extern
!! WORD *memterm=term; static LONG ctrap=0; !!!
!! ctrap++; !!!
Definition at line 2428 of file store.c.
References ReNuMbEr::func, ReNuMbEr::funnum, ReNuMbEr::indi, ReNuMbEr::indnum, ReNuMbEr::symb, ReNuMbEr::symnum, TermRenumber(), ReNuMbEr::vecnum, and ReNuMbEr::vect.
Referenced by TermRenumber().
TestDrop()
VOID TestDrop (VOID) extern
Definition at line 483 of file execute.c.
PutInVflags()
VOID PutInVflags (WORD nexpr) extern
Definition at line 561 of file execute.c.
TestMatch()
WORD TestMatch (PHEAD WORD * term, WORD * level) extern
This routine governs the pattern matching. If it decides that a substitution should be made, this can be either the insertion of a right hand side (C->rhs) or the automatic generation of terms as a result of an operation (like trace). The object to be replaced is removed from term and a subexpression pointer is inserted. If the substitution is made more than once there can be more subexpression pointers. Its number is positive as it corresponds to the level at which the C->rhs can be found in the compiler output. The subexpression pointer contains the wildcard substitution information. The power is found in *AT.TMout. For operations the subexpression pointer is negative and corresponds to an address in the array AT.TMout. In this array are then the instructions for the routine to be called and its number in the array 'Operations' The format is here: length,functionnumber,length-2 parameters
There is a certain complexity wrt repeat levels. Another complication is the poking of the wildcard values in the subexpression prototype in the compiler buffer. This was how things were done in the past with sequential FORM, but with the advent of TFORM this cannot be maintained. Now, for TFORM we make a copy of it. 7-may-2008 (JV): We cannot yet guarantee that this has been done 100% correctly. There are errors that occur in TFORM only and that may indicate problems.
Definition at line 97 of file pattern.c.
References AddRHS(), EndSort(), Generator(), CbUf::lhs, LowerSortLevel(), and NewSort().
Referenced by Generator().
TestSub()
WORD TestSub (PHEAD WORD * term, WORD level) extern
Definition at line 684 of file proces.c.
TimeCPU()
LONG TimeCPU (WORD par) extern
Returns the CPU time.
Parameters
par If zero, the CPU time will be reset to 0.
Returns
The CPU time in milliseconds.
Definition at line 3551 of file tools.c.
Referenced by PF_GetSlaveTimes(), PF_Processor(), and WriteStats().
TimeChildren()
LONG TimeChildren (WORD par) extern
Definition at line 3533 of file tools.c.
TimeWallClock()
LONG TimeWallClock (WORD par) extern
Returns the wall-clock time.
Parameters
par If zero, the wall-clock time will be reset to 0.
Returns
The wall-clock time in centiseconds.
Definition at line 3477 of file tools.c.
Referenced by DoCheckpoint(), DoRecovery(), find_Horner_MCTS(), optimize_expression_given_Horner(), optimize_greedy(), and WriteStats().
ToStorage()
WORD ToStorage (EXPRESSIONS e, POSITION * length) extern
Definition at line 2017 of file store.c.
TokenToLine()
VOID TokenToLine (UBYTE * s) extern
Definition at line 551 of file sch.c.
Trace4()
WORD Trace4 (PHEAD WORD * term, WORD * params, WORD num, WORD level) extern
Definition at line 694 of file opera.c.
Trace4Gen()
WORD Trace4Gen (PHEAD TRACES * t, WORD number) extern
Definition at line 856 of file opera.c.
Trace4no()
WORD Trace4no (WORD number, WORD * kron, TRACES * t) extern
Definition at line 418 of file opera.c.
TraceFind()
WORD TraceFind (PHEAD WORD * term, WORD * params) extern
Definition at line 1853 of file opera.c.
TraceN()
WORD TraceN (PHEAD WORD * term, WORD * params, WORD num, WORD level) extern
Definition at line 1382 of file opera.c.
TraceNgen()
WORD TraceNgen (PHEAD TRACES * t, WORD number) extern
Definition at line 1446 of file opera.c.
TraceNno()
WORD TraceNno (WORD number, WORD * kron, TRACES * t) extern
Definition at line 1341 of file opera.c.
Traces()
WORD Traces (PHEAD WORD * term, WORD * params, WORD num, WORD level) extern
Definition at line 1831 of file opera.c.
Trick()
WORD Trick (WORD * in, TRACES * t) extern
Definition at line 331 of file opera.c.
TryDo()
WORD TryDo (PHEAD WORD * term, WORD * pattern, WORD level) extern
Definition at line 1072 of file reshuf.c.
UnPack()
VOID UnPack (UWORD * a, WORD na, WORD * denom, WORD * numer) extern
Definition at line 100 of file reken.c.
VarStore()
WORD VarStore (UBYTE * s, WORD n, WORD name, WORD namesize) extern
Definition at line 2370 of file store.c.
WildFill()
WORD WildFill (PHEAD WORD * to, WORD * from, WORD * sub) extern
Definition at line 65 of file wildcard.c.
WriteAll()
WORD WriteAll (VOID) extern
Definition at line 2501 of file sch.c.
WriteOne()
WORD WriteOne (UBYTE * name, int alreadyinline, int nosemi, WORD plus) extern
Definition at line 2727 of file sch.c.
WriteArgument()
VOID WriteArgument (WORD * t) extern
Definition at line 1424 of file sch.c.
WriteExpression()
WORD WriteExpression (WORD * terms, LONG ltot) extern
Definition at line 2470 of file sch.c.
WriteInnerTerm()
WORD WriteInnerTerm (WORD * term, WORD first) extern
Definition at line 1951 of file sch.c.
WriteLists()
VOID WriteLists (VOID) extern
Definition at line 810 of file sch.c.
WriteSetup()
VOID WriteSetup (VOID) extern
Definition at line 811 of file setfile.c.
WriteStats()
VOID WriteStats (POSITION * plspace, WORD par, WORD checkLogType) extern
Writes the statistics.
Parameters
plspace The size in bytes currently occupied
par par = 0 = STATSSPLITMERGE after a splitmerge. par = 1 = STATSMERGETOFILE after merge to sortfile. par = 2 = STATSPOSTSORT after the sort
checkLogType == CHECKLOGTYPE: The output should not go to the log file if AM.LogType is 1.
current expression is to be found in AR.CurExpr. terms are in S->TermsLeft. S->GenTerms.
Definition at line 101 of file sort.c.
References TimeCPU(), and TimeWallClock().
Referenced by EndSort(), PF_Processor(), and StoreTerm().
WriteSubTerm()
WORD WriteSubTerm (WORD * sterm, WORD first) extern
Definition at line 1542 of file sch.c.
WriteTerm()
WORD WriteTerm (WORD * term, WORD * lbrac, WORD first, WORD prtf, WORD br) extern
Definition at line 2148 of file sch.c.
execarg()
WORD execarg (PHEAD WORD * term, WORD level) extern
Definition at line 56 of file argument.c.
execterm()
WORD execterm (PHEAD WORD * term, WORD level) extern
Definition at line 1763 of file argument.c.
SpecialCleanup()
VOID SpecialCleanup (PHEAD0) extern
Definition at line 1623 of file execute.c.
SetMods()
void SetMods (VOID) extern
Definition at line 1637 of file execute.c.
UnSetMods()
void UnSetMods (VOID) extern
Definition at line 1655 of file execute.c.
DoExecute()
WORD DoExecute (WORD par, WORD skip) extern
Definition at line 615 of file execute.c.
SetScratch()
VOID SetScratch (FILEHANDLE * f, POSITION * position) extern
Definition at line 115 of file store.c.
Warning()
VOID Warning (char * s) extern
Definition at line 790 of file message.c.
HighWarning()
VOID HighWarning (char * s) extern
Definition at line 802 of file message.c.
SpareTable()
int SpareTable (TABLES TT) extern
Definition at line 694 of file tables.c.
strDup1()
UBYTE * strDup1 (UBYTE * instring, char * ifwrong) extern
Definition at line 1904 of file tools.c.
Malloc()
VOID * Malloc (LONG size) extern
Definition at line 2221 of file tools.c.
Malloc1()
VOID * Malloc1 (LONG size, const char * messageifwrong) extern
Definition at line 2303 of file tools.c.
DoTail()
int DoTail (int argc, UBYTE ** argv) extern
Definition at line 237 of file startup.c.
OpenInput()
int OpenInput (VOID) extern
Definition at line 542 of file startup.c.
PutPreVar()
int PutPreVar (UBYTE * name, UBYTE * value, UBYTE * args, int mode) extern
Inserts/Updates a preprocessor variable in the name administration.
Parameters
name Character string with the variable name.
value Character string with a possible value. Special case: if this argument is zero, then we have no value. Note: This is different from having an empty argument! This should only occur when the name starts with a ?
args Character string with possible arguments.
mode =0: always create a new name entry, =1: try to do a redefinition if possible.
Returns
Index of used entry in name list.
Definition at line 718 of file pre.c.
Referenced by ClearOptimize(), Generator(), Optimize(), PF_BroadcastRedefinedPreVars(), StartVariables(), and TheDefine().
Error0()
VOID Error0 (char * s) extern
Definition at line 56 of file message.c.
Error1()
VOID Error1 (char * s, UBYTE * t) extern
Definition at line 67 of file message.c.
Error2()
VOID Error2 (char * s1, char * s2, UBYTE * t) extern
Definition at line 78 of file message.c.
ReadFromStream()
UBYTE ReadFromStream (STREAM * stream) extern
Definition at line 151 of file tools.c.
GetFromStream()
UBYTE GetFromStream (STREAM * stream) extern
Definition at line 286 of file tools.c.
LookInStream()
UBYTE LookInStream (STREAM * stream) extern
Definition at line 309 of file tools.c.
OpenStream()
STREAM * OpenStream (UBYTE * name, int type, int prevarmode, int raiselow) extern
Definition at line 321 of file tools.c.
LocateFile()
int LocateFile (UBYTE ** name, int type) extern
Definition at line 576 of file tools.c.
CloseStream()
STREAM * CloseStream (STREAM * stream) extern
Definition at line 663 of file tools.c.
PositionStream()
VOID PositionStream (STREAM * stream, LONG position) extern
Definition at line 823 of file tools.c.
ReverseStatements()
int ReverseStatements (STREAM * stream) extern
Definition at line 855 of file tools.c.
ProcessOption()
int ProcessOption (UBYTE * s1, UBYTE * s2, int filetype) extern
Definition at line 182 of file setfile.c.
DoSetups()
int DoSetups (VOID) extern
Definition at line 132 of file setfile.c.
TerminateImpl()
VOID TerminateImpl (int errorcode, const char * file, int line, const char * function) extern
Definition at line 1848 of file startup.c.
GetNode()
NAMENODE * GetNode (NAMETREE * nametree, UBYTE * name) extern
Definition at line 49 of file names.c.
AddName()
int AddName (NAMETREE * nametree, UBYTE * name, WORD type, WORD number, int * nodenum) extern
Definition at line 71 of file names.c.
GetName()
int GetName (NAMETREE * nametree, UBYTE * namein, WORD * number, int par) extern
Definition at line 252 of file names.c.
GetFunction()
UBYTE * GetFunction (UBYTE * s, WORD * funnum) extern
Definition at line 342 of file names.c.
GetNumber()
UBYTE * GetNumber (UBYTE * s, WORD * num) extern
Definition at line 388 of file names.c.
GetLastExprName()
int GetLastExprName (UBYTE * name, WORD * number) extern
Definition at line 438 of file names.c.
GetAutoName()
int GetAutoName (UBYTE * name, WORD * number) extern
Definition at line 479 of file names.c.
GetVar()
int GetVar (UBYTE * name, WORD * type, WORD * number, int wantedtype, int par) extern
Definition at line 524 of file names.c.
MakeDubious()
int MakeDubious (NAMETREE * nametree, UBYTE * name, WORD * number) extern
Definition at line 2693 of file names.c.
GetOName()
int GetOName (NAMETREE * nametree, UBYTE * name, WORD * number, int par) extern
Definition at line 460 of file names.c.
DumpTree()
VOID DumpTree (NAMETREE * nametree) extern
Definition at line 602 of file names.c.
DumpNode()
VOID DumpNode (NAMETREE * nametree, WORD node, WORD depth) extern
Definition at line 615 of file names.c.
LinkTree()
VOID LinkTree (NAMETREE * tree, WORD offset, WORD numnodes) extern
Definition at line 784 of file names.c.
CopyTree()
VOID CopyTree (NAMETREE * newtree, NAMETREE * oldtree, WORD node, WORD par) extern
Definition at line 696 of file names.c.
CompactifyTree()
int CompactifyTree (NAMETREE * nametree, WORD par) extern
Definition at line 634 of file names.c.
MakeNameTree()
NAMETREE * MakeNameTree (VOID) extern
Definition at line 815 of file names.c.
FreeNameTree()
VOID FreeNameTree (NAMETREE * n) extern
Definition at line 834 of file names.c.
AddExpression()
int AddExpression (UBYTE * name, int x, int y) extern
Definition at line 2744 of file names.c.
AddSymbol()
int AddSymbol (UBYTE * name, int minpow, int maxpow, int cplx, int dim) extern
Definition at line 920 of file names.c.
AddDollar()
int AddDollar (UBYTE * name, WORD type, WORD * start, LONG size) extern
Definition at line 2602 of file names.c.
ReplaceDollar()
int ReplaceDollar (WORD number, WORD newtype, WORD * newstart, LONG newsize) extern
Definition at line 2646 of file names.c.
DollarRaiseLow()
int DollarRaiseLow (UBYTE * name, LONG value) extern
Definition at line 2543 of file dollar.c.
AddVector()
int AddVector (UBYTE * name, int cplx, int dim) extern
Definition at line 1244 of file names.c.
AddDubious()
int AddDubious (UBYTE * name) extern
Definition at line 2679 of file names.c.
AddIndex()
int AddIndex (UBYTE * name, int dim, int dim4) extern
Definition at line 1088 of file names.c.
DoDimension()
UBYTE * DoDimension (UBYTE * s, int * dim, int * dim4) extern
Definition at line 1160 of file names.c.
AddFunction()
int AddFunction (UBYTE * name, int comm, int istensor, int cplx, int symprop, int dim, int argmax, int argmin) extern
Definition at line 1326 of file names.c.
CoCommuteInSet()
int CoCommuteInSet (UBYTE * s) extern
Definition at line 1356 of file names.c.
CoFunction()
int CoFunction (UBYTE * s, int comm, int istensor) extern
Definition at line 1446 of file names.c.
TestName()
int TestName (UBYTE * name) extern
Definition at line 3254 of file names.c.
AddSet()
int AddSet (UBYTE * name, WORD dim) extern
Definition at line 2122 of file names.c.
DoElements()
int DoElements (UBYTE * s, SETS set, UBYTE * name) extern
Definition at line 2155 of file names.c.
DoTempSet()
int DoTempSet (UBYTE * from, UBYTE * to) extern
Definition at line 2480 of file names.c.
NameConflict()
int NameConflict (int type, UBYTE * name) extern
Definition at line 2728 of file names.c.
OpenFile()
int OpenFile (char * name) extern
Definition at line 983 of file tools.c.
OpenAddFile()
int OpenAddFile (char * name) extern
Definition at line 1002 of file tools.c.
ReOpenFile()
int ReOpenFile (char * name) extern
Definition at line 1023 of file tools.c.
CreateFile()
int CreateFile (char * name) extern
Definition at line 1043 of file tools.c.
CreateLogFile()
int CreateLogFile (char * name) extern
Definition at line 1060 of file tools.c.
CloseFile()
VOID CloseFile (int handle) extern
Definition at line 1078 of file tools.c.
CopyFile()
int CopyFile (char * source, char * dest) extern
Copies a file with name *source to a file named *dest. The involved files must not be open. Returns non-zero if an error occurred. Uses if possible the combined large and small sorting buffers as cache.
Definition at line 1101 of file tools.c.
Referenced by DoRecovery().
CreateHandle()
int CreateHandle (VOID) extern
Definition at line 1162 of file tools.c.
ReadFile()
LONG ReadFile (int handle, UBYTE * buffer, LONG size) extern
Definition at line 1217 of file tools.c.
ReadPosFile()
LONG ReadPosFile (PHEAD FILEHANDLE * fi, UBYTE * buffer, LONG size, POSITION * pos) extern
Definition at line 1267 of file tools.c.
WriteFileToFile()
LONG WriteFileToFile (int handle, UBYTE * buffer, LONG size) extern
Definition at line 1333 of file tools.c.
SeekFile()
VOID SeekFile (int handle, POSITION * offset, int origin) extern
Definition at line 1371 of file tools.c.
TellFile()
LONG TellFile (int handle) extern
Definition at line 1396 of file tools.c.
FlushFile()
void FlushFile (int handle) extern
Definition at line 1420 of file tools.c.
GetPosFile()
int GetPosFile (int handle, fpos_t * pospointer) extern
Definition at line 1434 of file tools.c.
SetPosFile()
int SetPosFile (int handle, fpos_t * pospointer) extern
Definition at line 1448 of file tools.c.
SynchFile()
VOID SynchFile (int handle) extern
Definition at line 1468 of file tools.c.
TruncateFile()
VOID TruncateFile (int handle) extern
Definition at line 1490 of file tools.c.
GetChannel()
int GetChannel (char * name, int mode) extern
Definition at line 1510 of file tools.c.
GetAppendChannel()
int GetAppendChannel (char * name) extern
Definition at line 1546 of file tools.c.
CloseChannel()
int CloseChannel (char * name) extern
Definition at line 1576 of file tools.c.
inictable()
VOID inictable (VOID) extern
Definition at line 309 of file compiler.c.
findcommand()
KEYWORD * findcommand (UBYTE * in) extern
Definition at line 335 of file compiler.c.
inicbufs()
int inicbufs (VOID) extern
Creates a new compiler buffer and returns its ID number.
Returns
The ID number for the new compiler buffer.
Definition at line 47 of file comtool.c.
References CbUf::boomlijst, CbUf::Buffer, CbUf::BufferSize, CbUf::CanCommu, CbUf::dimension, CbUf::lhs, CbUf::numdum, CbUf::NumTerms, CbUf::Pointer, CbUf::rhs, and CbUf::Top.
Referenced by AddRHS(), and StartVariables().
StartFiles()
VOID StartFiles (VOID) extern
Definition at line 956 of file tools.c.
MakeDate()
UBYTE * MakeDate (VOID) extern
Definition at line 2090 of file tools.c.
PreProcessor()
VOID PreProcessor (VOID) extern
Definition at line 947 of file pre.c.
FromList()
VOID * FromList (LIST * L) extern
Definition at line 2780 of file tools.c.
From0List()
VOID * From0List (LIST * L) extern
Definition at line 2806 of file tools.c.
FromVarList()
VOID * FromVarList (LIST * L) extern
Definition at line 2835 of file tools.c.
DoubleList()
int DoubleList (VOID *** lijst, int * oldsize, int objectsize, char * nameoftype) extern
Definition at line 2877 of file tools.c.
DoubleLList()
int DoubleLList (VOID *** lijst, LONG * oldsize, int objectsize, char * nameoftype) extern
Definition at line 2929 of file tools.c.
DoubleBuffer()
void DoubleBuffer (void ** start, void ** stop, int size, char * text) extern
Definition at line 2977 of file tools.c.
ExpandBuffer()
void ExpandBuffer (void ** buffer, LONG * oldsize, int type) extern
Definition at line 3002 of file tools.c.
iexp()
LONG iexp (LONG x, int p) extern
Definition at line 3026 of file tools.c.
IsLikeVector()
int IsLikeVector (WORD * arg) extern
Definition at line 3229 of file tools.c.
AreArgsEqual()
int AreArgsEqual (WORD * arg1, WORD * arg2) extern
Definition at line 3257 of file tools.c.
CompareArgs()
int CompareArgs (WORD * arg1, WORD * arg2) extern
Definition at line 3276 of file tools.c.
SkipField()
UBYTE * SkipField (UBYTE * s, int level) extern
Definition at line 1946 of file tools.c.
StrCmp()
int StrCmp (UBYTE * s1, UBYTE * s2) extern
Definition at line 1700 of file tools.c.
StrICmp()
int StrICmp (UBYTE * s1, UBYTE * s2) extern
Definition at line 1711 of file tools.c.
StrHICmp()
int StrHICmp (UBYTE * s1, UBYTE * s2) extern
Definition at line 1722 of file tools.c.
StrICont()
int StrICont (UBYTE * s1, UBYTE * s2) extern
Definition at line 1733 of file tools.c.
CmpArray()
int CmpArray (WORD * t1, WORD * t2, WORD n) extern
Definition at line 1745 of file tools.c.
ConWord()
int ConWord (UBYTE * s1, UBYTE * s2) extern
Definition at line 1759 of file tools.c.
StrLen()
int StrLen (UBYTE * s) extern
Definition at line 1771 of file tools.c.
GetPreVar()
UBYTE * GetPreVar (UBYTE * name, int flag) extern
Definition at line 536 of file pre.c.
ToGeneral()
void ToGeneral (WORD * r, WORD * m, WORD par) extern
Definition at line 3057 of file tools.c.
ToPolyFunGeneral()
WORD ToPolyFunGeneral (PHEAD WORD * term) extern
Definition at line 3154 of file tools.c.
ToFast()
int ToFast (WORD * r, WORD * m) extern
Definition at line 3101 of file tools.c.
GetSetupPar()
SETUPPARAMETERS * GetSetupPar (UBYTE * s) extern
Definition at line 337 of file setfile.c.
RecalcSetups()
int RecalcSetups (VOID) extern
Definition at line 357 of file setfile.c.
AllocSetups()
int AllocSetups (VOID) extern
Definition at line 404 of file setfile.c.
AllocSort()
SORTING * AllocSort (LONG inLargeSize, LONG inSmallSize, LONG inSmallEsize, LONG inTermsInSmall, int inMaxPatches, int inMaxFpatches, LONG inIOsize, int level) extern
Definition at line 869 of file setfile.c.
AllocSortFileName()
VOID AllocSortFileName (SORTING * sort) extern
Definition at line 1019 of file setfile.c.
LoadInputFile()
UBYTE * LoadInputFile (UBYTE * filename, int type) extern
Definition at line 112 of file tools.c.
GetInput()
UBYTE GetInput (VOID) extern
Definition at line 132 of file pre.c.
ClearPushback()
VOID ClearPushback (VOID) extern
Definition at line 161 of file pre.c.
GetChar()
UBYTE GetChar (int level) extern
Definition at line 179 of file pre.c.
CharOut()
VOID CharOut (UBYTE c) extern
Definition at line 489 of file pre.c.
UnsetAllowDelay()
VOID UnsetAllowDelay (VOID) extern
Definition at line 510 of file pre.c.
PopPreVars()
VOID PopPreVars (int tonumber) extern
Definition at line 820 of file pre.c.
IniModule()
VOID IniModule (int type) extern
Definition at line 835 of file pre.c.
IniSpecialModule()
VOID IniSpecialModule (int type) extern
Definition at line 937 of file pre.c.
ModuleInstruction()
int ModuleInstruction (int * moduletype, int * specialtype) extern
Definition at line 76 of file module.c.
PreProInstruction()
int PreProInstruction (VOID) extern
Definition at line 1166 of file pre.c.
LoadInstruction()
int LoadInstruction (int mode) extern
Definition at line 1254 of file pre.c.
LoadStatement()
int LoadStatement (int type) extern
Definition at line 1457 of file pre.c.
FindKeyWord()
KEYWORD * FindKeyWord (UBYTE * theword, KEYWORD * table, int size) extern
Definition at line 1963 of file pre.c.
FindInKeyWord()
KEYWORD * FindInKeyWord (UBYTE * theword, KEYWORD * table, int size) extern
Definition at line 1994 of file pre.c.
DoDefine()
int DoDefine (UBYTE * s) extern
Definition at line 2159 of file pre.c.
DoRedefine()
int DoRedefine (UBYTE * s) extern
Definition at line 2169 of file pre.c.
TheDefine()
int TheDefine (UBYTE * s, int mode) extern
Preprocessor assignment. Possible arguments and values are treated and the new preprocessor variable is put into the name administration.
Parameters
s Pointer to the character string following the preprocessor command.
mode Bitmask. 0-bit clear: always create a new name entry, 0-bit set: try to redefine an existing name, 1-bit set: ignore preprocessor if/switch status.
Returns
zero: no errors, negative number: errors.
Definition at line 2024 of file pre.c.
References PutPreVar().
TheUndefine()
int TheUndefine (UBYTE * name) extern
Definition at line 2209 of file pre.c.
ClearMacro()
int ClearMacro (UBYTE * name) extern
Definition at line 2181 of file pre.c.
DoUndefine()
int DoUndefine (UBYTE * s) extern
Definition at line 2263 of file pre.c.
DoInclude()
int DoInclude (UBYTE * s) extern
Definition at line 2315 of file pre.c.
DoReverseInclude()
int DoReverseInclude (UBYTE * s) extern
Definition at line 2322 of file pre.c.
Include()
int Include (UBYTE * s, int type) extern
Definition at line 2329 of file pre.c.
DoExternal()
int DoExternal (UBYTE * s) extern
Definition at line 5424 of file pre.c.
DoToExternal()
int DoToExternal (UBYTE * s) extern
Definition at line 5986 of file pre.c.
DoFromExternal()
int DoFromExternal (UBYTE * s) extern
Definition at line 5791 of file pre.c.
DoPrompt()
int DoPrompt (UBYTE * s) extern
Definition at line 5506 of file pre.c.
DoSetExternal()
int DoSetExternal (UBYTE * s) extern
Definition at line 5539 of file pre.c.
DoSetExternalAttr()
int DoSetExternalAttr (UBYTE * s) extern
Definition at line 5609 of file pre.c.
DoRmExternal()
int DoRmExternal (UBYTE * s) extern
Definition at line 5726 of file pre.c.
DoFactDollar()
int DoFactDollar (UBYTE * s) extern
Definition at line 6633 of file pre.c.
GetDollarNumber()
WORD GetDollarNumber (UBYTE ** inp, DOLLARS d) extern
Definition at line 6670 of file pre.c.
DoSetRandom()
int DoSetRandom (UBYTE * s) extern
Definition at line 6760 of file pre.c.
DoOptimize()
int DoOptimize (UBYTE * s) extern
Definition at line 6803 of file pre.c.
DoClearOptimize()
int DoClearOptimize (UBYTE * s) extern
Definition at line 6936 of file pre.c.
DoSkipExtraSymbols()
int DoSkipExtraSymbols (UBYTE * s) extern
Definition at line 6956 of file pre.c.
DoTimeOutAfter()
int DoTimeOutAfter (UBYTE * s) extern
Definition at line 7182 of file pre.c.
DoMessage()
int DoMessage (UBYTE * s) extern
Definition at line 3676 of file pre.c.
DoPreOut()
int DoPreOut (UBYTE * s) extern
Definition at line 3747 of file pre.c.
DoPreAppend()
int DoPreAppend (UBYTE * s) extern
Definition at line 3804 of file pre.c.
DoPreCreate()
int DoPreCreate (UBYTE * s) extern
Definition at line 3847 of file pre.c.
DoPreAssign()
int DoPreAssign (UBYTE * s) extern
Definition at line 2128 of file pre.c.
DoPreBreak()
int DoPreBreak (UBYTE * s) extern
Definition at line 4047 of file pre.c.
DoPreDefault()
int DoPreDefault (UBYTE * s) extern
Definition at line 4110 of file pre.c.
DoPreSwitch()
int DoPreSwitch (UBYTE * s) extern
Definition at line 4161 of file pre.c.
DoPreEndSwitch()
int DoPreEndSwitch (UBYTE * s) extern
Definition at line 4134 of file pre.c.
DoPreCase()
int DoPreCase (UBYTE * s) extern
Definition at line 4071 of file pre.c.
DoPreShow()
int DoPreShow (UBYTE * s) extern
Definition at line 4215 of file pre.c.
DoPreExchange()
int DoPreExchange (UBYTE * s) extern
Definition at line 2490 of file pre.c.
DoSystem()
int DoSystem (UBYTE * s) extern
Definition at line 4254 of file pre.c.
DoPipe()
int DoPipe (UBYTE * s) extern
Definition at line 3690 of file pre.c.
StartPrepro()
VOID StartPrepro (VOID) extern
Definition at line 4432 of file pre.c.
DoIfdef()
int DoIfdef (UBYTE * s, int par) extern
Definition at line 3391 of file pre.c.
DoIfydef()
int DoIfydef (UBYTE * s) extern
Definition at line 3416 of file pre.c.
DoIfndef()
int DoIfndef (UBYTE * s) extern
Definition at line 3426 of file pre.c.
DoElse()
int DoElse (UBYTE * s) extern
Definition at line 3095 of file pre.c.
DoElseif()
int DoElseif (UBYTE * s) extern
Definition at line 3132 of file pre.c.
DoEndif()
int DoEndif (UBYTE * s) extern
Definition at line 3313 of file pre.c.
DoTerminate()
int DoTerminate (UBYTE * s) extern
Definition at line 2757 of file pre.c.
DoIf()
int DoIf (UBYTE * s) extern
Definition at line 3367 of file pre.c.
DoCall()
int DoCall (UBYTE * s) extern
Definition at line 2551 of file pre.c.
DoDebug()
int DoDebug (UBYTE * s) extern
Definition at line 2720 of file pre.c.
DoContinueDo()
int DoContinueDo (UBYTE * s) extern
Definition at line 2780 of file pre.c.
DoDo()
int DoDo (UBYTE * s) extern
Definition at line 2811 of file pre.c.
DoBreakDo()
int DoBreakDo (UBYTE * s) extern
Definition at line 3026 of file pre.c.
DoEnddo()
int DoEnddo (UBYTE * s) extern
Definition at line 3167 of file pre.c.
DoEndprocedure()
int DoEndprocedure (UBYTE * s) extern
Definition at line 3341 of file pre.c.
DoInside()
int DoInside (UBYTE * s) extern
Definition at line 3451 of file pre.c.
DoEndInside()
int DoEndInside (UBYTE * s) extern
Definition at line 3544 of file pre.c.
DoProcedure()
int DoProcedure (UBYTE * s) extern
Definition at line 4005 of file pre.c.
DoPrePrintTimes()
int DoPrePrintTimes (UBYTE * s) extern
Definition at line 3770 of file pre.c.
DoPreWrite()
int DoPreWrite (UBYTE * s) extern
Definition at line 3964 of file pre.c.
DoPreClose()
int DoPreClose (UBYTE * s) extern
Definition at line 3920 of file pre.c.
DoPreRemove()
int DoPreRemove (UBYTE * s) extern
Definition at line 3887 of file pre.c.
DoPreSortReallocate()
int DoPreSortReallocate (UBYTE * s) extern
Definition at line 3784 of file pre.c.
DoCommentChar()
int DoCommentChar (UBYTE * s) extern
Definition at line 2097 of file pre.c.
DoPrcExtension()
int DoPrcExtension (UBYTE * s) extern
Definition at line 3713 of file pre.c.
DoPreReset()
int DoPreReset (UBYTE * s) extern
Definition at line 6995 of file pre.c.
WriteString()
VOID WriteString (int type, UBYTE * str, int num) extern
Definition at line 1807 of file tools.c.
WriteUnfinString()
VOID WriteUnfinString (int type, UBYTE * str, int num) extern
Definition at line 1841 of file tools.c.
AddToString()
UBYTE * AddToString (UBYTE * outstring, UBYTE * extrastring, int par) extern
Definition at line 1866 of file tools.c.
PreCalc()
UBYTE * PreCalc (VOID) extern
Definition at line 5113 of file pre.c.
PreEval()
UBYTE * PreEval (UBYTE * s, LONG * x) extern
Definition at line 5191 of file pre.c.
NumToStr()
VOID NumToStr (UBYTE * s, LONG x) extern
Definition at line 1783 of file tools.c.
PreCmp()
int PreCmp (int type, int val, UBYTE * t, int type2, int val2, UBYTE * t2, int cmpop) extern
Definition at line 4624 of file pre.c.
PreEq()
int PreEq (int type, int val, UBYTE * t, int type2, int val2, UBYTE * t2, int eqop) extern
Definition at line 4648 of file pre.c.
pParseObject()
UBYTE * pParseObject (UBYTE * s, int * type, LONG * val2) extern
Definition at line 4677 of file pre.c.
PreIfEval()
UBYTE * PreIfEval (UBYTE * s, int * value) extern
Definition at line 4495 of file pre.c.
EvalPreIf()
int EvalPreIf (UBYTE * s) extern
Definition at line 4460 of file pre.c.
PreLoad()
int PreLoad (PRELOAD * p, UBYTE * start, UBYTE * stop, int mode, char * message) extern
Definition at line 4294 of file pre.c.
PreSkip()
int PreSkip (UBYTE * start, UBYTE * stop, int mode) extern
Definition at line 4377 of file pre.c.
EndOfToken()
UBYTE * EndOfToken (UBYTE * s) extern
Definition at line 1919 of file tools.c.
SetSpecialMode()
VOID SetSpecialMode (int moduletype, int specialtype) extern
Definition at line 257 of file module.c.
MakeGlobal()
VOID MakeGlobal (VOID) extern
Definition at line 382 of file execute.c.
ExecModule()
int ExecModule (int moduletype) extern
Definition at line 274 of file module.c.
ExecStore()
int ExecStore (VOID) extern
Definition at line 299 of file module.c.
FullCleanUp()
VOID FullCleanUp (VOID) extern
Definition at line 314 of file module.c.
DoExecStatement()
int DoExecStatement (VOID) extern
Definition at line 780 of file module.c.
DoPipeStatement()
int DoPipeStatement (VOID) extern
Definition at line 797 of file module.c.
DoPolyfun()
int DoPolyfun (UBYTE * s) extern
Definition at line 395 of file module.c.
DoPolyratfun()
int DoPolyratfun (UBYTE * s) extern
Definition at line 458 of file module.c.
CompileStatement()
int CompileStatement (UBYTE * in) extern
Definition at line 553 of file compiler.c.
ToToken()
UBYTE * ToToken (UBYTE * s) extern
Definition at line 1931 of file tools.c.
GetDollar()
int GetDollar (UBYTE * name) extern
Definition at line 590 of file names.c.
MesWork()
int MesWork (VOID) extern
Definition at line 89 of file message.c.
MesCall()
int MesCall (char * s) extern
Definition at line 814 of file message.c.
NumCopy()
UBYTE * NumCopy (WORD y, UBYTE * to) extern
Definition at line 1997 of file tools.c.
LongCopy()
char * LongCopy (LONG y, char * to) extern
Definition at line 2024 of file tools.c.
LongLongCopy()
char * LongLongCopy (off_t * y, char * to) extern
Definition at line 2051 of file tools.c.
ReserveTempFiles()
VOID ReserveTempFiles (int par) extern
Definition at line 666 of file startup.c.
PrintTerm()
VOID PrintTerm (WORD * term, char * where) extern
Definition at line 857 of file message.c.
PrintTermC()
VOID PrintTermC (WORD * term, char * where) extern
Definition at line 887 of file message.c.
PrintSubTerm()
VOID PrintSubTerm (WORD * term, char * where) extern
Definition at line 921 of file message.c.
PrintWords()
VOID PrintWords (WORD * buffer, LONG number) extern
Definition at line 943 of file message.c.
PrintSeq()
void PrintSeq (WORD * a, char * text) extern
Definition at line 961 of file message.c.
ExpandTripleDots()
int ExpandTripleDots (int par) extern
Definition at line 1595 of file pre.c.
ComPress()
LONG ComPress (WORD ** ss, LONG * n) extern
Gets a list of pointers to terms and compresses the terms. In n it collects the number of terms and the return value of the function is the space that is occupied.
We have to pay some special attention to the compression of terms with a PolyFun. This PolyFun should occur only straight before the coefficient, so we can use the same trick as for the coefficient to sabotage compression of this object (Replace in the history the function pointer by zero. This is safe, because terms that would be identical otherwise would have been added).
Parameters
ss Array of pointers to terms to be compressed.
n Number of pointers in ss.
Returns
Total number of words needed for the compressed result.
Definition at line 3166 of file sort.c.
Referenced by EndSort(), and StoreTerm().
StageSort()
VOID StageSort (FILEHANDLE * fout) extern
Prepares a stage 4 or higher sort. Stage 4 sorts occur when the sort file contains more patches than can be merged in one pass.
Definition at line 4624 of file sort.c.
References FiLe::handle.
Referenced by EndSort(), and MergePatches().
M_free()
void M_free (VOID * x, const char * where) extern
Definition at line 2383 of file tools.c.
ClearWildcardNames()
void ClearWildcardNames (VOID) extern
Definition at line 849 of file names.c.
AddWildcardName()
int AddWildcardName (UBYTE * name) extern
Definition at line 854 of file names.c.
GetWildcardName()
int GetWildcardName (UBYTE * name) extern
Definition at line 898 of file names.c.
Globalize()
void Globalize (int par) extern
Definition at line 3155 of file names.c.
ResetVariables()
void ResetVariables (int par) extern
Definition at line 2832 of file names.c.
AddToPreTypes()
void AddToPreTypes (int type) extern
Definition at line 5341 of file pre.c.
MessPreNesting()
void MessPreNesting (int par) extern
Definition at line 5359 of file pre.c.
GetStreamPosition()
LONG GetStreamPosition (STREAM * stream) extern
Definition at line 813 of file tools.c.
DoubleCbuffer()
WORD * DoubleCbuffer (int num, WORD * w, int par) extern
Doubles a compiler buffer.
Parameters
num The ID number for the buffer to be doubled.
w The pointer to the end (exclusive) of the current buffer. The contents in the range of [cbuf[num].Buffer,w) will be kept.
Definition at line 143 of file comtool.c.
References CbUf::Buffer, CbUf::BufferSize, CbUf::lhs, CbUf::Pointer, CbUf::rhs, and CbUf::Top.
Referenced by AddNtoC(), and AddNtoL().
AddLHS()
WORD * AddLHS (int num) extern
Adds an LHS to a compiler buffer and returns the pointer to a buffer for the new LHS.
Parameters
num The ID number for the buffer to get another LHS.
Definition at line 188 of file comtool.c.
References CbUf::lhs, and CbUf::Pointer.
Referenced by AddNtoL().
AddRHS()
WORD * AddRHS (int num, int type) extern
Adds an RHS to a compiler buffer and returns the pointer to a buffer for the new RHS.
Parameters
num The ID number for the buffer to get another RHS.
type If 0, the subexpression tree will be reallocated.
Definition at line 214 of file comtool.c.
References TaBlEs::buffers, TaBlEs::buffersfill, TaBlEs::bufferssize, TaBlEs::bufnum, CbUf::CanCommu, CbUf::dimension, inicbufs(), CbUf::numdum, CbUf::NumTerms, CbUf::Pointer, and CbUf::rhs.
Referenced by InsertArg(), StartVariables(), and TestMatch().
AddNtoL()
int AddNtoL (int n, WORD * array) extern
Adds an LHS with the given data to the current compiler buffer.
Parameters
n The length of the data.
array The data to be added.
Returns
0 if succeeds.
Definition at line 288 of file comtool.c.
References AddLHS(), DoubleCbuffer(), CbUf::Pointer, and CbUf::Top.
AddNtoC()
int AddNtoC (int bufnum, int n, WORD * array, int par) extern
Adds the given data to the last LHS/RHS in a compiler buffer.
Parameters
bufnum The ID number for the buffer where the data will be added.
n The length of the data.
array The data to be added.
Returns
0 if succeeds.
Definition at line 317 of file comtool.c.
References DoubleCbuffer(), CbUf::Pointer, and CbUf::Top.
Referenced by InsertArg(), and StartVariables().
DoubleIfBuffers()
VOID DoubleIfBuffers (VOID) extern
Definition at line 1033 of file if.c.
CreateStream()
STREAM * CreateStream (UBYTE * where) extern
Definition at line 782 of file tools.c.
setonoff()
int setonoff (UBYTE * s, int * flag, int onvalue, int offvalue) extern
Definition at line 488 of file compcomm.c.
DoPrint()
int DoPrint (UBYTE * s, int par) extern
Definition at line 1039 of file compcomm.c.
SetExpr()
int SetExpr (UBYTE * s, int setunset, int par) extern
Definition at line 1501 of file compcomm.c.
AddToCom()
void AddToCom (int n, WORD * array) extern
Definition at line 1631 of file compcomm.c.
Add2ComStrings()
int Add2ComStrings (int n, WORD * array, UBYTE * string1, UBYTE * string2) extern
Definition at line 1705 of file compcomm.c.
DoSymmetrize()
int DoSymmetrize (UBYTE * s, int par) extern
Definition at line 2199 of file compcomm.c.
DoArgument()
int DoArgument (UBYTE * s, int par) extern
Definition at line 1844 of file compcomm.c.
ArgFactorize()
int ArgFactorize (PHEAD WORD * argin, WORD * argout) extern
Definition at line 2054 of file argument.c.
TakeArgContent()
WORD * TakeArgContent (PHEAD WORD * argin, WORD * argout) extern
Implements part of the old ExecArg in which we take common factors from arguments with more than one term. The common pieces are put in argout as a sequence of arguments. The part with the multiple terms that are now relative prime is put in argfree which is allocated via TermMalloc and is given as the return value. The difference with the old code is that negative powers are always removed. Hence it is as in MakeInteger in which only numerators will be left: now only zero or positive powers will be remaining.
Definition at line 2760 of file argument.c.
References EndSort(), MakeInteger(), MakeMod(), NewSort(), and StoreTerm().
MakeInteger()
WORD * MakeInteger (PHEAD WORD * argin, WORD * argout, WORD * argfree) extern
For normalizing everything to integers we have to determine for all elements of this argument the LCM of the denominators and the GCD of the numerators. The input argument is in argin. The number that comes out should go to argout. The new pointer in the argout buffer is the return value. The normalized argument is in argfree.
Definition at line 3306 of file argument.c.
Referenced by TakeArgContent().
MakeMod()
WORD * MakeMod (PHEAD WORD * argin, WORD * argout, WORD * argfree) extern
Similar to MakeInteger but now with modulus arithmetic using only a one WORD 'prime'. We make the coefficient of the first term in the argument equal to one. Already the coefficients are taken modulus AN.cmod and AN.ncmod == 1
Definition at line 3477 of file argument.c.
References GetModInverses().
Referenced by TakeArgContent().
FindArg()
WORD FindArg (PHEAD WORD * a) extern
Looks the argument up in the (workers) table. If it is found the number in the table is returned (plus one to make it positive). If it is not found we look in the compiler provided table. If it is found - the number in the table is returned (minus one to make it negative). If in neither table we return zero.
Definition at line 2507 of file argument.c.
InsertArg()
WORD InsertArg (PHEAD WORD * argin, WORD * argout, int par) extern
Inserts the argument into the (workers) table. If the table is too full we eliminate half of it. The eliminated elements are the ones that have not been used most recently, weighted by their total use and age(?). If par == 0 it inserts in the regular factorization cache If par == 1 it inserts in the cache defined with the FactorCache statement
Definition at line 2531 of file argument.c.
References AddNtoC(), AddRHS(), and CleanupArgCache().
CleanupArgCache()
int CleanupArgCache (PHEAD WORD bufnum) extern
Cleans up the argument factorization cache. We throw half the elements. For a weight of what we want to keep we use the product of usage and the number in the buffer.
Definition at line 2566 of file argument.c.
References CbUf::boomlijst, CbUf::Buffer, CbUf::Pointer, CbUf::rhs, SortWeights(), and tree::usage.
Referenced by InsertArg().
ArgSymbolMerge()
int ArgSymbolMerge (WORD * t1, WORD * t2) extern
Definition at line 2637 of file argument.c.
ArgDotproductMerge()
int ArgDotproductMerge (WORD * t1, WORD * t2) extern
Definition at line 2692 of file argument.c.
SortWeights()
void SortWeights (LONG * weights, LONG * extraspace, WORD number) extern
Sorts an array of LONGS in the same way SplitMerge (in sort.c) works We use gradual division in two.
Definition at line 3522 of file argument.c.
References SortWeights().
Referenced by CleanupArgCache(), and SortWeights().
DoBrackets()
int DoBrackets (UBYTE * inp, int par) extern
Definition at line 3734 of file compcomm.c.
DoPutInside()
int DoPutInside (UBYTE * inp, int par) extern
Definition at line 7020 of file compcomm.c.
CountComp()
WORD * CountComp (UBYTE * inp, WORD * to) extern
Definition at line 4012 of file compcomm.c.
CoAntiBracket()
int CoAntiBracket (UBYTE * inp) extern
Definition at line 3869 of file compcomm.c.
CoAntiSymmetrize()
int CoAntiSymmetrize (UBYTE * s) extern
Definition at line 2326 of file compcomm.c.
DoArgPlode()
int DoArgPlode (UBYTE * s, int par) extern
Definition at line 5680 of file compcomm.c.
CoArgExplode()
int CoArgExplode (UBYTE * s) extern
Definition at line 5736 of file compcomm.c.
CoArgImplode()
int CoArgImplode (UBYTE * s) extern
Definition at line 5743 of file compcomm.c.
CoArgument()
int CoArgument (UBYTE * s) extern
Definition at line 2078 of file compcomm.c.
CoInside()
int CoInside (UBYTE * s) extern
Definition at line 2111 of file compcomm.c.
ExecInside()
int ExecInside (UBYTE * s) extern
Definition at line 1681 of file dollar.c.
CoInExpression()
int CoInExpression (UBYTE * s) extern
Definition at line 3339 of file compcomm.c.
CoInParallel()
int CoInParallel (UBYTE * s) extern
Definition at line 3245 of file compcomm.c.
CoNotInParallel()
int CoNotInParallel (UBYTE * s) extern
Definition at line 3255 of file compcomm.c.
DoInParallel()
int DoInParallel (UBYTE * s, int par) extern
Definition at line 3270 of file compcomm.c.
CoEndInExpression()
int CoEndInExpression (UBYTE * s) extern
Definition at line 3392 of file compcomm.c.
CoBracket()
int CoBracket (UBYTE * inp) extern
Definition at line 3861 of file compcomm.c.
CoPutInside()
int CoPutInside (UBYTE * inp) extern
Definition at line 7017 of file compcomm.c.
CoAntiPutInside()
int CoAntiPutInside (UBYTE * inp) extern
Definition at line 7018 of file compcomm.c.
CoMultiBracket()
int CoMultiBracket (UBYTE * inp) extern
Definition at line 3880 of file compcomm.c.
CoCFunction()
int CoCFunction (UBYTE * s) extern
Definition at line 1625 of file names.c.
CoCTensor()
int CoCTensor (UBYTE * s) extern
Definition at line 1627 of file names.c.
CoCollect()
int CoCollect (UBYTE * s) extern
Definition at line 426 of file compcomm.c.
CoCompress()
int CoCompress (UBYTE * s) extern
Definition at line 504 of file compcomm.c.
CoContract()
int CoContract (UBYTE * s) extern
Definition at line 1769 of file compcomm.c.
CoCycleSymmetrize()
int CoCycleSymmetrize (UBYTE * s) extern
Definition at line 2333 of file compcomm.c.
CoDelete()
int CoDelete (UBYTE * s) extern
Definition at line 940 of file compcomm.c.
CoTableBase()
int CoTableBase (UBYTE * s) extern
Definition at line 627 of file tables.c.
CoApply()
int CoApply (UBYTE * s) extern
Definition at line 1796 of file tables.c.
CoDenominators()
int CoDenominators (UBYTE * s) extern
Definition at line 5832 of file compcomm.c.
CoDimension()
int CoDimension (UBYTE * s) extern
Definition at line 1226 of file names.c.
CoDiscard()
int CoDiscard (UBYTE * s) extern
Definition at line 1746 of file compcomm.c.
CoDisorder()
int CoDisorder (UBYTE * inp) extern
Definition at line 417 of file comexpr.c.
CoDrop()
int CoDrop (UBYTE * s) extern
Definition at line 1546 of file compcomm.c.
CoDropCoefficient()
int CoDropCoefficient (UBYTE * s) extern
Definition at line 5861 of file compcomm.c.
CoDropSymbols()
int CoDropSymbols (UBYTE * s) extern
Definition at line 5875 of file compcomm.c.
CoElse()
int CoElse (UBYTE * p) extern
Definition at line 4844 of file compcomm.c.
CoElseIf()
int CoElseIf (UBYTE * inp) extern
Definition at line 4871 of file compcomm.c.
CoEndArgument()
int CoEndArgument (UBYTE * s) extern
Definition at line 2085 of file compcomm.c.
CoEndInside()
int CoEndInside (UBYTE * s) extern
Definition at line 2118 of file compcomm.c.
CoEndIf()
int CoEndIf (UBYTE * inp) extern
Definition at line 4898 of file compcomm.c.
CoEndRepeat()
int CoEndRepeat (UBYTE * inp) extern
Definition at line 3696 of file compcomm.c.
CoEndTerm()
int CoEndTerm (UBYTE * s) extern
Definition at line 5238 of file compcomm.c.
CoEndWhile()
int CoEndWhile (UBYTE * inp) extern
Definition at line 4964 of file compcomm.c.
CoExit()
int CoExit (UBYTE * s) extern
Definition at line 3218 of file compcomm.c.
CoFactArg()
int CoFactArg (UBYTE * s) extern
Definition at line 2179 of file compcomm.c.
CoFactDollar()
int CoFactDollar (UBYTE * inp) extern
Definition at line 6391 of file compcomm.c.
CoFactorize()
int CoFactorize (UBYTE * s) extern
Definition at line 6420 of file compcomm.c.
CoNFactorize()
int CoNFactorize (UBYTE * s) extern
Definition at line 6427 of file compcomm.c.
CoUnFactorize()
int CoUnFactorize (UBYTE * s) extern
Definition at line 6434 of file compcomm.c.
CoNUnFactorize()
int CoNUnFactorize (UBYTE * s) extern
Definition at line 6441 of file compcomm.c.
DoFactorize()
int DoFactorize (UBYTE * s, int par) extern
Definition at line 6448 of file compcomm.c.
CoFill()
int CoFill (UBYTE * inp) extern
Definition at line 1070 of file comexpr.c.
CoFillExpression()
int CoFillExpression (UBYTE * inp) extern
Definition at line 1356 of file comexpr.c.
CoFixIndex()
int CoFixIndex (UBYTE * s) extern
Definition at line 997 of file compcomm.c.
CoFormat()
int CoFormat (UBYTE * s) extern
Definition at line 151 of file compcomm.c.
CoGlobal()
int CoGlobal (UBYTE * inp) extern
Definition at line 73 of file comexpr.c.
CoGlobalFactorized()
int CoGlobalFactorized (UBYTE * inp) extern
Definition at line 87 of file comexpr.c.
CoGoTo()
int CoGoTo (UBYTE * inp) extern
Definition at line 1798 of file compcomm.c.
CoId()
int CoId (UBYTE * inp) extern
Definition at line 395 of file comexpr.c.
CoIdNew()
int CoIdNew (UBYTE * inp) extern
Definition at line 406 of file comexpr.c.
CoIdOld()
int CoIdOld (UBYTE * inp) extern
Definition at line 384 of file comexpr.c.
CoIf()
int CoIf (UBYTE * inp) extern
Definition at line 4202 of file compcomm.c.
CoIfMatch()
int CoIfMatch (UBYTE * inp) extern
Definition at line 450 of file comexpr.c.
CoIfNoMatch()
int CoIfNoMatch (UBYTE * inp) extern
Definition at line 461 of file comexpr.c.
CoIndex()
int CoIndex (UBYTE * s) extern
Definition at line 1112 of file names.c.
CoInsideFirst()
int CoInsideFirst (UBYTE * s) extern
Definition at line 926 of file compcomm.c.
CoKeep()
int CoKeep (UBYTE * s) extern
Definition at line 985 of file compcomm.c.
CoLabel()
int CoLabel (UBYTE * inp) extern
Definition at line 1817 of file compcomm.c.
CoLoad()
int CoLoad (UBYTE * inp) extern
Definition at line 573 of file store.c.
CoLocal()
int CoLocal (UBYTE * inp) extern
Definition at line 66 of file comexpr.c.
CoLocalFactorized()
int CoLocalFactorized (UBYTE * inp) extern
Definition at line 80 of file comexpr.c.
CoMany()
int CoMany (UBYTE * inp) extern
Definition at line 428 of file comexpr.c.
CoMerge()
int CoMerge (UBYTE * inp) extern
Definition at line 5521 of file compcomm.c.
CoStuffle()
int CoStuffle (UBYTE * inp) extern
Definition at line 5577 of file compcomm.c.
CoMetric()
int CoMetric (UBYTE * s) extern
Definition at line 1031 of file compcomm.c.
CoModOption()
int CoModOption (UBYTE * s) extern
Definition at line 212 of file module.c.
CoModuleOption()
int CoModuleOption (UBYTE * s) extern
Definition at line 143 of file module.c.
CoModulus()
int CoModulus (UBYTE * inp) extern
Definition at line 3535 of file compcomm.c.
CoMulti()
int CoMulti (UBYTE * inp) extern
Definition at line 439 of file comexpr.c.
CoMultiply()
int CoMultiply (UBYTE * inp) extern
Definition at line 1031 of file comexpr.c.
CoNFunction()
int CoNFunction (UBYTE * s) extern
Definition at line 1624 of file names.c.
CoNPrint()
int CoNPrint (UBYTE * s) extern
Definition at line 1269 of file compcomm.c.
CoNTensor()
int CoNTensor (UBYTE * s) extern
Definition at line 1626 of file names.c.
CoNWrite()
int CoNWrite (UBYTE * s) extern
Definition at line 2372 of file compcomm.c.
CoNoDrop()
int CoNoDrop (UBYTE * s) extern
Definition at line 1553 of file compcomm.c.
CoNoSkip()
int CoNoSkip (UBYTE * s) extern
Definition at line 1567 of file compcomm.c.
CoNormalize()
int CoNormalize (UBYTE * s) extern
Definition at line 2144 of file compcomm.c.
CoMakeInteger()
int CoMakeInteger (UBYTE * s) extern
Definition at line 2151 of file compcomm.c.
CoFlags()
int CoFlags (UBYTE * s, int value) extern
Definition at line 553 of file compcomm.c.
CoOff()
int CoOff (UBYTE * s) extern
Definition at line 588 of file compcomm.c.
CoOn()
int CoOn (UBYTE * s) extern
Definition at line 654 of file compcomm.c.
CoOnce()
int CoOnce (UBYTE * inp) extern
Definition at line 472 of file comexpr.c.
CoOnly()
int CoOnly (UBYTE * inp) extern
Definition at line 483 of file comexpr.c.
CoOptimizeOption()
int CoOptimizeOption (UBYTE * s) extern
Definition at line 6581 of file compcomm.c.
CoPolyFun()
int CoPolyFun (UBYTE * s) extern
Definition at line 5304 of file compcomm.c.
CoPolyRatFun()
int CoPolyRatFun (UBYTE * s) extern
Definition at line 5351 of file compcomm.c.
CoPrint()
int CoPrint (UBYTE * s) extern
Definition at line 1255 of file compcomm.c.
CoPrintB()
int CoPrintB (UBYTE * s) extern
Definition at line 1262 of file compcomm.c.
CoProperCount()
int CoProperCount (UBYTE * s) extern
Definition at line 933 of file compcomm.c.
CoUnitTrace()
int CoUnitTrace (UBYTE * s) extern
Definition at line 5155 of file compcomm.c.
CoRCycleSymmetrize()
int CoRCycleSymmetrize (UBYTE * s) extern
Definition at line 2340 of file compcomm.c.
CoRatio()
int CoRatio (UBYTE * s) extern
Definition at line 2399 of file compcomm.c.
CoRedefine()
int CoRedefine (UBYTE * s) extern
Definition at line 2439 of file compcomm.c.
CoRenumber()
int CoRenumber (UBYTE * s) extern
Definition at line 2544 of file compcomm.c.
CoRepeat()
int CoRepeat (UBYTE * inp) extern
Definition at line 3673 of file compcomm.c.
CoSave()
int CoSave (UBYTE * inp) extern
Definition at line 363 of file store.c.
CoSelect()
int CoSelect (UBYTE * inp) extern
Definition at line 494 of file comexpr.c.
CoSet()
int CoSet (UBYTE * s) extern
Definition at line 2355 of file names.c.
CoSetExitFlag()
int CoSetExitFlag (UBYTE * s) extern
Definition at line 3418 of file compcomm.c.
CoSkip()
int CoSkip (UBYTE * s) extern
Definition at line 1560 of file compcomm.c.
CoProcessBucket()
int CoProcessBucket (UBYTE * s) extern
Definition at line 5632 of file compcomm.c.
CoPushHide()
int CoPushHide (UBYTE * s) extern
Definition at line 1276 of file compcomm.c.
CoPopHide()
int CoPopHide (UBYTE * s) extern
Definition at line 1320 of file compcomm.c.
CoHide()
int CoHide (UBYTE * inp) extern
Definition at line 1574 of file compcomm.c.
CoIntoHide()
int CoIntoHide (UBYTE * inp) extern
Definition at line 1592 of file compcomm.c.
CoNoHide()
int CoNoHide (UBYTE * inp) extern
Definition at line 1610 of file compcomm.c.
CoUnHide()
int CoUnHide (UBYTE * inp) extern
Definition at line 1617 of file compcomm.c.
CoNoUnHide()
int CoNoUnHide (UBYTE * inp) extern
Definition at line 1624 of file compcomm.c.
CoSort()
int CoSort (UBYTE * s) extern
Definition at line 5265 of file compcomm.c.
CoSplitArg()
int CoSplitArg (UBYTE * s) extern
Definition at line 2158 of file compcomm.c.
CoSplitFirstArg()
int CoSplitFirstArg (UBYTE * s) extern
Definition at line 2165 of file compcomm.c.
CoSplitLastArg()
int CoSplitLastArg (UBYTE * s) extern
Definition at line 2172 of file compcomm.c.
CoSum()
int CoSum (UBYTE * s) extern
Definition at line 2565 of file compcomm.c.
CoSymbol()
int CoSymbol (UBYTE * s) extern
Definition at line 946 of file names.c.
CoSymmetrize()
int CoSymmetrize (UBYTE * s) extern
Definition at line 2319 of file compcomm.c.
DoTable()
int DoTable (UBYTE * s, int par) extern
Definition at line 1666 of file names.c.
CoTable()
int CoTable (UBYTE * s) extern
Definition at line 2048 of file names.c.
CoTerm()
int CoTerm (UBYTE * s) extern
Definition at line 5190 of file compcomm.c.
CoNTable()
int CoNTable (UBYTE * s) extern
Definition at line 2058 of file names.c.
CoCTable()
int CoCTable (UBYTE * s) extern
Definition at line 2068 of file names.c.
EmptyTable()
void EmptyTable (TABLES T) extern
Definition at line 2078 of file names.c.
CoToTensor()
int CoToTensor (UBYTE * s) extern
Definition at line 2685 of file compcomm.c.
CoToVector()
int CoToVector (UBYTE * s) extern
Definition at line 2853 of file compcomm.c.
CoTrace4()
int CoTrace4 (UBYTE * s) extern
Definition at line 2923 of file compcomm.c.
CoTraceN()
int CoTraceN (UBYTE * s) extern
Definition at line 3010 of file compcomm.c.
CoChisholm()
int CoChisholm (UBYTE * s) extern
Definition at line 3070 of file compcomm.c.
CoTransform()
int CoTransform (UBYTE * in) extern
Definition at line 87 of file transform.c.
CoClearTable()
int CoClearTable (UBYTE * s) extern
Definition at line 5750 of file compcomm.c.
DoChain()
int DoChain (UBYTE * s, int option) extern
Definition at line 3152 of file compcomm.c.
CoChainin()
int CoChainin (UBYTE * s) extern
Definition at line 3196 of file compcomm.c.
CoChainout()
int CoChainout (UBYTE * s) extern
Definition at line 3208 of file compcomm.c.
CoTryReplace()
int CoTryReplace (UBYTE * p) extern
Definition at line 3432 of file compcomm.c.
CoVector()
int CoVector (UBYTE * s) extern
Definition at line 1267 of file names.c.
CoWhile()
int CoWhile (UBYTE * inp) extern
Definition at line 4943 of file compcomm.c.
CoWrite()
int CoWrite (UBYTE * s) extern
Definition at line 2347 of file compcomm.c.
CoAuto()
int CoAuto (UBYTE * inp) extern
Definition at line 2572 of file names.c.
CoSwitch()
int CoSwitch (UBYTE * s) extern
Definition at line 7140 of file compcomm.c.
CoCase()
int CoCase (UBYTE * s) extern
Definition at line 7186 of file compcomm.c.
CoBreak()
int CoBreak (UBYTE * s) extern
Definition at line 7236 of file compcomm.c.
CoDefault()
int CoDefault (UBYTE * s) extern
Definition at line 7262 of file compcomm.c.
CoEndSwitch()
int CoEndSwitch (UBYTE * s) extern
Definition at line 7289 of file compcomm.c.
CoTBaddto()
int CoTBaddto (UBYTE * s) extern
Definition at line 801 of file tables.c.
CoTBaudit()
int CoTBaudit (UBYTE * s) extern
Definition at line 1473 of file tables.c.
CoTBcleanup()
int CoTBcleanup (UBYTE * s) extern
Definition at line 1575 of file tables.c.
CoTBcreate()
int CoTBcreate (UBYTE * s) extern
Definition at line 756 of file tables.c.
CoTBenter()
int CoTBenter (UBYTE * s) extern
Definition at line 974 of file tables.c.
CoTBhelp()
int CoTBhelp (UBYTE * s) extern
Definition at line 1883 of file tables.c.
CoTBload()
int CoTBload (UBYTE * ss) extern
Definition at line 1252 of file tables.c.
CoTBoff()
int CoTBoff (UBYTE * s) extern
Definition at line 1544 of file tables.c.
CoTBon()
int CoTBon (UBYTE * s) extern
Definition at line 1513 of file tables.c.
CoTBopen()
int CoTBopen (UBYTE * s) extern
Definition at line 772 of file tables.c.
CoTBreplace()
int CoTBreplace (UBYTE * s) extern
Definition at line 1587 of file tables.c.
CoTBuse()
int CoTBuse (UBYTE * s) extern
Definition at line 1602 of file tables.c.
CoTestUse()
int CoTestUse (UBYTE * s) extern
Definition at line 1133 of file tables.c.
CoThreadBucket()
int CoThreadBucket (UBYTE * s) extern
Definition at line 5650 of file compcomm.c.
AddComString()
int AddComString (int n, WORD * array, UBYTE * thestring, int par) extern
Definition at line 1646 of file compcomm.c.
CompileAlgebra()
int CompileAlgebra (UBYTE * s, int leftright, WORD * prototype) extern
Definition at line 517 of file compiler.c.
IsIdStatement()
int IsIdStatement (UBYTE * s) extern
Definition at line 503 of file compiler.c.
IsRHS()
UBYTE * IsRHS (UBYTE * s, UBYTE c) extern
Definition at line 457 of file compiler.c.
ParenthesesTest()
int ParenthesesTest (UBYTE * sin) extern
Definition at line 379 of file compiler.c.
tokenize()
int tokenize (UBYTE * in, WORD leftright) extern
Definition at line 58 of file token.c.
WriteTokens()
void WriteTokens (SBYTE * in) extern
Definition at line 657 of file token.c.
simp1token()
int simp1token (SBYTE * s) extern
Definition at line 705 of file token.c.
simpwtoken()
int simpwtoken (SBYTE * s) extern
Definition at line 794 of file token.c.
simp2token()
int simp2token (SBYTE * s) extern
Definition at line 948 of file token.c.
simp3atoken()
int simp3atoken (SBYTE * s, int mode) extern
Definition at line 1196 of file token.c.
simp3btoken()
int simp3btoken (SBYTE * s, int mode) extern
Definition at line 1437 of file token.c.
simp4token()
int simp4token (SBYTE * s) extern
Definition at line 1822 of file token.c.
simp5token()
int simp5token (SBYTE * s, int mode) extern
Definition at line 1982 of file token.c.
simp6token()
int simp6token (SBYTE * tokens, int mode) extern
Definition at line 2028 of file token.c.
SkipAName()
UBYTE * SkipAName (UBYTE * s) extern
Definition at line 429 of file compiler.c.
TestTables()
int TestTables (VOID) extern
Definition at line 668 of file compiler.c.
GetLabel()
int GetLabel (UBYTE * name) extern
Definition at line 2787 of file names.c.
CoIdExpression()
int CoIdExpression (UBYTE * inp, int type) extern
Definition at line 507 of file comexpr.c.
CoAssign()
int CoAssign (UBYTE * inp) extern
Definition at line 1924 of file comexpr.c.
DoExpr()
int DoExpr (UBYTE * inp, int type, int par) extern
Definition at line 96 of file comexpr.c.
CompileSubExpressions()
int CompileSubExpressions (SBYTE * tokens) extern
Definition at line 712 of file compiler.c.
CodeGenerator()
int CodeGenerator (SBYTE * tokens) extern
Definition at line 847 of file compiler.c.
CompleteTerm()
int CompleteTerm (WORD * term, UWORD * numer, UWORD * denom, WORD nnum, WORD nden, int sign) extern
Definition at line 1910 of file compiler.c.
CodeFactors()
int CodeFactors (SBYTE * s) extern
Definition at line 1947 of file compiler.c.
GenerateFactors()
WORD GenerateFactors (WORD n, WORD inc) extern
Definition at line 2244 of file compiler.c.
InsTree()
int InsTree (int bufnum, int h) extern
Definition at line 355 of file comtool.c.
FindTree()
int FindTree (int bufnum, WORD * subexpr) extern
Definition at line 533 of file comtool.c.
RedoTree()
void RedoTree (CBUF * C, int size) extern
Definition at line 569 of file comtool.c.
ClearTree()
void ClearTree (int i) extern
Definition at line 588 of file comtool.c.
CatchDollar()
int CatchDollar (int par) extern
Definition at line 54 of file dollar.c.
AssignDollar()
int AssignDollar (PHEAD WORD * term, WORD level) extern
Definition at line 209 of file dollar.c.
WriteDollarToBuffer()
UBYTE * WriteDollarToBuffer (WORD numdollar, WORD par) extern
Definition at line 596 of file dollar.c.
WriteDollarFactorToBuffer()
UBYTE * WriteDollarFactorToBuffer (WORD numdollar, WORD numfac, WORD par) extern
Definition at line 687 of file dollar.c.
AddToDollarBuffer()
void AddToDollarBuffer (UBYTE * s) extern
Definition at line 762 of file dollar.c.
PutTermInDollar()
int PutTermInDollar (WORD * term, WORD numdollar) extern
Definition at line 863 of file dollar.c.
TermAssign()
void TermAssign (WORD * term) extern
Definition at line 803 of file dollar.c.
WildDollars()
void WildDollars (PHEAD WORD * term) extern
Definition at line 891 of file dollar.c.
numcommute()
LONG numcommute (WORD * terms, LONG * numterms) extern
Definition at line 659 of file comtool.c.
FullRenumber()
int FullRenumber (PHEAD WORD * term, WORD par) extern
Definition at line 324 of file reshuf.c.
Lus()
int Lus (WORD * term, WORD funnum, WORD loopsize, WORD numargs, WORD outfun, WORD mode) extern
Definition at line 57 of file lus.c.
FindLus()
int FindLus (int from, int level, int openindex) extern
Definition at line 515 of file lus.c.
CoReplaceLoop()
int CoReplaceLoop (UBYTE * inp) extern
Definition at line 5114 of file compcomm.c.
CoFindLoop()
int CoFindLoop (UBYTE * inp) extern
Definition at line 5106 of file compcomm.c.
DoFindLoop()
int DoFindLoop (UBYTE * inp, int mode) extern
Definition at line 4992 of file compcomm.c.
CoFunPowers()
int CoFunPowers (UBYTE * inp) extern
Definition at line 5128 of file compcomm.c.
SortTheList()
int SortTheList (int * slist, int num) extern
Definition at line 578 of file lus.c.
MatchIsPossible()
int MatchIsPossible (WORD * pattern, WORD * term) extern
Definition at line 299 of file smart.c.
StudyPattern()
int StudyPattern (WORD * lhs) extern
Definition at line 62 of file smart.c.
DolToTensor()
WORD DolToTensor (PHEAD WORD) extern
Definition at line 1082 of file dollar.c.
DolToFunction()
WORD DolToFunction (PHEAD WORD) extern
Definition at line 1143 of file dollar.c.
DolToVector()
WORD DolToVector (PHEAD WORD) extern
Definition at line 1200 of file dollar.c.
DolToNumber()
WORD DolToNumber (PHEAD WORD) extern
Definition at line 1264 of file dollar.c.
DolToSymbol()
WORD DolToSymbol (PHEAD WORD) extern
Definition at line 1323 of file dollar.c.
DolToIndex()
WORD DolToIndex (PHEAD WORD) extern
Definition at line 1377 of file dollar.c.
DolToLong()
LONG DolToLong (PHEAD WORD) extern
Definition at line 1606 of file dollar.c.
DollarFactorize()
int DollarFactorize (PHEAD WORD) extern
Definition at line 2946 of file dollar.c.
CoPrintTable()
int CoPrintTable (UBYTE * inp) extern
Definition at line 1748 of file comexpr.c.
CoDeallocateTable()
int CoDeallocateTable (UBYTE * inp) extern
Definition at line 1982 of file comexpr.c.
CleanDollarFactors()
void CleanDollarFactors (DOLLARS d) extern
Definition at line 3545 of file dollar.c.
TakeDollarContent()
WORD * TakeDollarContent (PHEAD WORD * dollarbuffer, WORD ** factor) extern
Definition at line 3566 of file dollar.c.
MakeDollarInteger()
WORD * MakeDollarInteger (PHEAD WORD * bufin, WORD ** bufout) extern
For normalizing everything to integers we have to determine for all elements of this argument the LCM of the denominators and the GCD of the numerators. The input argument is in bufin. The number that comes out is the return value. The normalized argument is in bufout.
Definition at line 3618 of file dollar.c.
References EndSort(), Generator(), and NewSort().
MakeDollarMod()
WORD * MakeDollarMod (PHEAD WORD * buffer, WORD ** bufout) extern
Similar to MakeDollarInteger but now with modulus arithmetic using only a one WORD 'prime'. We make the coefficient of the first term in the argument equal to one. Already the coefficients are taken modulus AN.cmod and AN.ncmod == 1
Definition at line 3792 of file dollar.c.
References EndSort(), Generator(), GetModInverses(), and NewSort().
GetDolNum()
int GetDolNum (PHEAD WORD * t, WORD * tstop) extern
Definition at line 3837 of file dollar.c.
AddPotModdollar()
void AddPotModdollar (WORD numdollar) extern
Adds a $-variable specified by numdollar to the list of potentially modified $-variables unless it has already been included in the list.
Parameters
numdollar The index of the $-variable to be added.
Definition at line 3950 of file dollar.c.
Optimize()
int Optimize (WORD exprnr, int do_print) extern
Optimization of expression
Description
This method takes an input expression and generates optimized code to calculate its value. The following methods are called to do so:
(1) get_expression : to read to expression
(2) get_brackets : find brackets for simultaneous optimization
(3) occurrence_order or find_Horner_MCTS : to determine (the) Horner scheme(s) to use; this depends on AO.optimize.horner
(4) optimize_expression_given_Horner : to do the optimizations for each Horner scheme; this method does either CSE or greedy optimizations dependings on AO.optimize.method
(5) generate_output : to format the output in Form notation and store it in a buffer
(6a) optimize_print_code : to print the expression (for "Print") or (6b) generate_expression : to modify the expression (for "#Optimize")
On ParFORM, all the processes must call this function at the same time. Then
(1) Because only the master can access to the expression to be optimized, the master broadcast the expression to all the slaves after reading the expression (PF_get_expression).
(2) get_brackets reads optimize_expr as the input and it works also on the slaves. We leave it although the bracket information is not needed on the slaves (used in (5) on the master).
(3) and (4) find_Horner_MCTS and optimize_expression_given_Horner are parallelized.
(5), (6a) and (6b) are needed only on the master.
Definition at line 4638 of file optimize.cc.
References ClearOptimize(), count_operators(), find_Horner_MCTS(), generate_expression(), generate_output(), get_brackets(), get_expression(), occurrence_order(), optimize_expression_given_Horner(), optimize_print_code(), PF_Broadcast(), PF_LongMultiBroadcast(), PF_Pack(), PF_PrepareLongMultiPack(), PF_PreparePack(), PF_Unpack(), and PutPreVar().
TakeLongRoot()
int TakeLongRoot (UWORD * a, WORD * n, WORD power) extern
Definition at line 2735 of file reken.c.
TakeRatRoot()
int TakeRatRoot (UWORD * a, WORD * n, WORD power) extern
Definition at line 680 of file reken.c.
MakeRational()
int MakeRational (WORD a, WORD m, WORD * b, WORD * c) extern
Definition at line 2855 of file reken.c.
MakeLongRational()
int MakeLongRational (PHEAD UWORD * a, WORD na, UWORD * m, WORD nm, UWORD * b, WORD * nb) extern
Definition at line 2903 of file reken.c.
ClearTableTree()
void ClearTableTree (TABLES T) extern
Definition at line 72 of file tables.c.
InsTableTree()
int InsTableTree (TABLES T, WORD * tp) extern
Definition at line 103 of file tables.c.
RedoTableTree()
void RedoTableTree (TABLES T, int newsize) extern
Definition at line 266 of file tables.c.
FindTableTree()
int FindTableTree (TABLES T, WORD * tp, int inc) extern
Definition at line 291 of file tables.c.
finishcbuf()
void finishcbuf (WORD num) extern
Frees a compiler buffer.
Parameters
num The ID number for the buffer to be freed.
Definition at line 89 of file comtool.c.
References CbUf::boomlijst, CbUf::Buffer, CbUf::BufferSize, CbUf::CanCommu, CbUf::lhs, CbUf::NumTerms, CbUf::Pointer, CbUf::rhs, and CbUf::Top.
Referenced by PF_BroadcastCBuf().
clearcbuf()
void clearcbuf (WORD num) extern
Clears contents in a compiler buffer.
Parameters
num The ID number for the buffer to be cleared.
Definition at line 116 of file comtool.c.
References CbUf::boomlijst, CbUf::Buffer, CbUf::Pointer, and CbUf::rhs.
CleanUpSort()
void CleanUpSort (int num) extern
Partially or completely frees function sort buffers.
Definition at line 4815 of file sort.c.
AllocFileHandle()
FILEHANDLE * AllocFileHandle (WORD par, char * name) extern
Definition at line 1044 of file setfile.c.
DeAllocFileHandle()
VOID DeAllocFileHandle (FILEHANDLE * fh) extern
Definition at line 1105 of file setfile.c.
LowerSortLevel()
VOID LowerSortLevel (VOID) extern
Lowers the level in the sort system.
Definition at line 4915 of file sort.c.
Referenced by generate_expression(), get_expression(), InFunction(), PF_CollectModifiedDollars(), PF_Processor(), poly_factorize_expression(), poly_sort(), poly_unfactorize_expression(), PolyFunMul(), Processor(), and TestMatch().
PolyRatFunSpecial()
WORD * PolyRatFunSpecial (PHEAD WORD * t1, WORD * t2) extern
Definition at line 4932 of file sort.c.
SimpleSplitMergeRec()
VOID SimpleSplitMergeRec (WORD * array, WORD num, WORD * auxarray) extern
Definition at line 5034 of file sort.c.
SimpleSplitMerge()
VOID SimpleSplitMerge (WORD * array, WORD num) extern
Definition at line 5062 of file sort.c.
BinarySearch()
WORD BinarySearch (WORD * array, WORD num, WORD x) extern
Definition at line 5080 of file sort.c.
InsideDollar()
int InsideDollar (PHEAD WORD * ll, WORD level) extern
Definition at line 1746 of file dollar.c.
DolToTerms()
DOLLARS DolToTerms (PHEAD WORD) extern
Definition at line 1458 of file dollar.c.
EvalDoLoopArg()
WORD EvalDoLoopArg (PHEAD WORD * arg, WORD par) extern
Evaluates one argument of a do loop. Such an argument is constructed from SNUMBERs DOLLAREXPRESSIONs and possibly DOLLAREXPR2s which indicate factors of the preceding dollar. Hence we have SNUMBER,num DOLLAREXPRESSION,numdollar DOLLAREXPRESSION,numdollar,DOLLAREXPR2,numfactor DOLLAREXPRESSION,numdollar,DOLLAREXPR2,numfactor,DOLLAREXPR2,numfactor etc. Because we have a do-loop at every stage we should have a number. The notation in DOLLAREXPR2 is that >= 0 is number of yet another dollar and < 0 is -n-1 with n the array element or zero. The return value is the (short) number. The routine works its way through the list in a recursive manner.
Definition at line 2642 of file dollar.c.
References EvalDoLoopArg().
Referenced by EvalDoLoopArg().
SetExprCases()
int SetExprCases (int par, int setunset, int val) extern
Definition at line 1355 of file compcomm.c.
TestSelect()
int TestSelect (WORD * term, WORD * setp) extern
Definition at line 1748 of file pattern.c.
SubsInAll()
VOID SubsInAll (PHEAD0) extern
Definition at line 1982 of file pattern.c.
TransferBuffer()
VOID TransferBuffer (int from, int to, int spectator) extern
Definition at line 2143 of file pattern.c.
TakeIDfunction()
int TakeIDfunction (PHEAD WORD * term) extern
Definition at line 2213 of file pattern.c.
MakeSetupAllocs()
int MakeSetupAllocs (VOID) extern
Definition at line 1122 of file setfile.c.
TryFileSetups()
int TryFileSetups (VOID) extern
Definition at line 1142 of file setfile.c.
ExchangeExpressions()
void ExchangeExpressions (int num1, int num2) extern
Definition at line 1670 of file execute.c.
ExchangeDollars()
void ExchangeDollars (int num1, int num2) extern
Definition at line 1840 of file dollar.c.
GetFirstBracket()
int GetFirstBracket (WORD * term, int num) extern
Definition at line 1744 of file execute.c.
GetFirstTerm()
int GetFirstTerm (WORD * term, int num, int pre) extern
Gets the first term of an expression. Routine should be thread safe.
Parameters
[out] term Pointer to the buffer where the term should be written.
[in] num The expression number from which to get the term.
[in] pre Denotes a pre-processor call (1) or not (0). Used to determine the correct source file for the expression.
Returns
First WORD of term, a negative value denotes an error.
Definition at line 1863 of file execute.c.
References FiLe::handle, VaRrEnUm::lo, and ReNuMbEr::symb.
GetContent()
int GetContent (WORD * content, int num) extern
Definition at line 1971 of file execute.c.
CleanupTerm()
int CleanupTerm (WORD * term) extern
Definition at line 2088 of file execute.c.
ContentMerge()
WORD ContentMerge (PHEAD WORD * content, WORD * term) extern
Definition at line 2112 of file execute.c.
PreIfDollarEval()
UBYTE * PreIfDollarEval (UBYTE * s, int * value) extern
Definition at line 1969 of file dollar.c.
TermsInDollar()
LONG TermsInDollar (WORD num) extern
Definition at line 1858 of file dollar.c.
SizeOfDollar()
LONG SizeOfDollar (WORD num) extern
Definition at line 1907 of file dollar.c.
TermsInExpression()
LONG TermsInExpression (WORD num) extern
Definition at line 2376 of file execute.c.
SizeOfExpression()
LONG SizeOfExpression (WORD num) extern
Definition at line 2388 of file execute.c.
TranslateExpression()
WORD * TranslateExpression (UBYTE * s) extern
Definition at line 2151 of file dollar.c.
IsSetMember()
int IsSetMember (WORD * buffer, WORD numset) extern
Definition at line 2208 of file dollar.c.
IsMultipleOf()
int IsMultipleOf (WORD * buf1, WORD * buf2) extern
Definition at line 2389 of file dollar.c.
TwoExprCompare()
int TwoExprCompare (WORD * buf1, WORD * buf2, int oprtr) extern
Definition at line 2464 of file dollar.c.
UpdatePositions()
void UpdatePositions (VOID) extern
Definition at line 2400 of file execute.c.
M_print()
void M_print (VOID) extern
Definition at line 2517 of file tools.c.
M_check1()
void M_check1 (VOID) extern
Definition at line 2516 of file tools.c.
PrintTime()
void PrintTime (UBYTE * mess) extern
Definition at line 784 of file sch.c.
FindBracket()
POSITION * FindBracket (WORD nexp, WORD * bracket) extern
Definition at line 65 of file index.c.
PutBracketInIndex()
VOID PutBracketInIndex (PHEAD WORD * term, POSITION * newpos) extern
Definition at line 331 of file index.c.
ClearBracketIndex()
void ClearBracketIndex (WORD numexp) extern
Definition at line 546 of file index.c.
OpenBracketIndex()
VOID OpenBracketIndex (WORD nexpr) extern
Definition at line 578 of file index.c.
DoNoParallel()
int DoNoParallel (UBYTE * s) extern
Definition at line 529 of file module.c.
DoParallel()
int DoParallel (UBYTE * s) extern
Definition at line 544 of file module.c.
DoModSum()
int DoModSum (UBYTE * s) extern
Definition at line 559 of file module.c.
DoModMax()
int DoModMax (UBYTE * s) extern
Definition at line 579 of file module.c.
DoModMin()
int DoModMin (UBYTE * s) extern
Definition at line 599 of file module.c.
DoModLocal()
int DoModLocal (UBYTE * s) extern
Definition at line 619 of file module.c.
DoModDollar()
UBYTE * DoModDollar (UBYTE * s, int type) extern
Definition at line 657 of file module.c.
DoProcessBucket()
int DoProcessBucket (UBYTE * s) extern
Definition at line 639 of file module.c.
DoinParallel()
int DoinParallel (UBYTE * s) extern
Definition at line 758 of file module.c.
DonotinParallel()
int DonotinParallel (UBYTE * s) extern
Definition at line 768 of file module.c.
FlipTable()
int FlipTable (FUNCTIONS f, int type) extern
Definition at line 671 of file tables.c.
ChainIn()
int ChainIn (PHEAD WORD * term, WORD funnum) extern
Definition at line 691 of file function.c.
ChainOut()
int ChainOut (PHEAD WORD * term, WORD funnum) extern
Definition at line 739 of file function.c.
ArgumentImplode()
int ArgumentImplode (PHEAD WORD * term, WORD * thelist) extern
Definition at line 1839 of file argument.c.
ArgumentExplode()
int ArgumentExplode (PHEAD WORD * term, WORD * thelist) extern
Definition at line 1943 of file argument.c.
DenToFunction()
int DenToFunction (WORD * term, WORD numfun) extern
Definition at line 2556 of file wildcard.c.
HowMany()
WORD HowMany (PHEAD WORD * ifcode, WORD * term) extern
Definition at line 840 of file if.c.
RemoveDollars()
VOID RemoveDollars (VOID) extern
Definition at line 3128 of file names.c.
CountTerms1()
LONG CountTerms1 (PHEAD0) extern
Definition at line 2461 of file execute.c.
TermsInBracket()
LONG TermsInBracket (PHEAD WORD * term, WORD level) extern
Definition at line 2569 of file execute.c.
Crash()
int Crash (VOID) extern
Definition at line 3834 of file tools.c.
str_dup()
char * str_dup (char * str) extern
Definition at line 101 of file minos.c.
convertblock()
void convertblock (INDEXBLOCK * in, INDEXBLOCK * out, int mode) extern
Definition at line 120 of file minos.c.
convertnamesblock()
void convertnamesblock (NAMESBLOCK * in, NAMESBLOCK * out, int mode) extern
Definition at line 171 of file minos.c.
convertiniinfo()
void convertiniinfo (INIINFO * in, INIINFO * out, int mode) extern
Definition at line 197 of file minos.c.
ReadIndex()
int ReadIndex (DBASE * d) extern
Definition at line 288 of file minos.c.
WriteIndexBlock()
int WriteIndexBlock (DBASE * d, MLONG num) extern
Definition at line 401 of file minos.c.
WriteNamesBlock()
int WriteNamesBlock (DBASE * d, MLONG num) extern
Definition at line 422 of file minos.c.
WriteIndex()
int WriteIndex (DBASE * d) extern
Definition at line 445 of file minos.c.
WriteIniInfo()
int WriteIniInfo (DBASE * d) extern
Definition at line 508 of file minos.c.
ReadIniInfo()
int ReadIniInfo (DBASE * d) extern
Definition at line 525 of file minos.c.
AddToIndex()
int AddToIndex (DBASE * d, MLONG number) extern
Definition at line 1063 of file minos.c.
GetDbase()
DBASE * GetDbase (char * filename, MLONG rwmode) extern
Definition at line 548 of file minos.c.
OpenDbase()
DBASE * OpenDbase (char * filename) extern
Definition at line 818 of file minos.c.
ReadObject()
char * ReadObject (DBASE * d, MLONG tablenumber, char * arguments) extern
Definition at line 1292 of file minos.c.
ReadijObject()
char * ReadijObject (DBASE * d, MLONG i, MLONG j, char * arguments) extern
Definition at line 1373 of file minos.c.
ExistsObject()
int ExistsObject (DBASE * d, MLONG tablenumber, char * arguments) extern
Definition at line 1425 of file minos.c.
DeleteObject()
int DeleteObject (DBASE * d, MLONG tablenumber, char * arguments) extern
Definition at line 1457 of file minos.c.
WriteObject()
int WriteObject (DBASE * d, MLONG tablenumber, char * arguments, char * rhs, MLONG number) extern
Definition at line 1192 of file minos.c.
AddObject()
MLONG AddObject (DBASE * d, MLONG tablenumber, char * arguments, char * rhs) extern
Definition at line 1150 of file minos.c.
NewDbase()
DBASE * NewDbase (char * name, MLONG number) extern
Definition at line 602 of file minos.c.
FreeTableBase()
void FreeTableBase (DBASE * d) extern
Definition at line 737 of file minos.c.
ComposeTableNames()
int ComposeTableNames (DBASE * d) extern
Definition at line 769 of file minos.c.
PutTableNames()
int PutTableNames (DBASE * d) extern
Definition at line 967 of file minos.c.
AddTableName()
MLONG AddTableName (DBASE * d, char * name, TABLES T) extern
Definition at line 852 of file minos.c.
GetTableName()
MLONG GetTableName (DBASE * d, char * name) extern
Definition at line 935 of file minos.c.
FindTableNumber()
MLONG FindTableNumber (DBASE * d, char * name) extern
Definition at line 1164 of file minos.c.
TryEnvironment()
int TryEnvironment (VOID) extern
Definition at line 1228 of file setfile.c.
CopyExpression()
int CopyExpression (FILEHANDLE * from, FILEHANDLE * to) extern
Definition at line 3308 of file store.c.
set_in()
int set_in (UBYTE ch, set_of_char set) extern
Definition at line 2112 of file tools.c.
set_set()
one_byte set_set (UBYTE ch, set_of_char set) extern
Definition at line 2132 of file tools.c.
set_del()
one_byte set_del (UBYTE ch, set_of_char set) extern
Definition at line 2153 of file tools.c.
set_sub()
one_byte set_sub (set_of_char set, set_of_char set1, set_of_char set2) extern
Definition at line 2175 of file tools.c.
DoPreAddSeparator()
int DoPreAddSeparator (UBYTE * s) extern
Definition at line 5382 of file pre.c.
DoPreRmSeparator()
int DoPreRmSeparator (UBYTE * s) extern
Definition at line 5407 of file pre.c.
openExternalChannel()
int openExternalChannel (UBYTE * cmd, int daemonize, UBYTE * shellname, UBYTE * stderrname) extern
Definition at line 234 of file extcmd.c.
initPresetExternalChannels()
int initPresetExternalChannels (UBYTE * theline, int thetimeout) extern
Definition at line 236 of file extcmd.c.
closeExternalChannel()
int closeExternalChannel (int n) extern
Definition at line 237 of file extcmd.c.
selectExternalChannel()
int selectExternalChannel (int n) extern
Definition at line 238 of file extcmd.c.
getCurrentExternalChannel()
int getCurrentExternalChannel (VOID) extern
Definition at line 239 of file extcmd.c.
closeAllExternalChannels()
VOID closeAllExternalChannels (VOID) extern
Definition at line 240 of file extcmd.c.
defineChannel()
UBYTE * defineChannel (UBYTE * s, HANDLERS * h) extern
Definition at line 6033 of file pre.c.
writeToChannel()
int writeToChannel (int wtype, UBYTE * s, HANDLERS * h) extern
Definition at line 6068 of file pre.c.
ReleaseTB()
int ReleaseTB (VOID) extern
Definition at line 2319 of file tables.c.
SymbolNormalize()
int SymbolNormalize (WORD * term) extern
Routine normalizes terms that contain only symbols. Regular minimum and maximum properties are ignored.
We check whether there are negative powers in the output. This is not allowed.
Definition at line 5127 of file normal.c.
Referenced by InFunction(), and poly_sort().
TestFunFlag()
int TestFunFlag (PHEAD WORD * tfun) extern
Definition at line 5223 of file normal.c.
CompareSymbols()
WORD CompareSymbols (PHEAD WORD * term1, WORD * term2, WORD par) extern
Compares the terms, based on the value of AN.polysortflag. If term1 < term2 the return value is -1 If term1 > term2 the return value is 1 If term1 = term2 the return value is 0 The coefficients may differ. The terms contain only a single subterm of type SYMBOL. If AN.polysortflag = 0 it is a 'regular' compare. If AN.polysortflag = 1 the sum of the powers is more important par is a dummy parameter to make the parameter field identical to that of Compare1 which is the regular compare routine in sort.c
Definition at line 3070 of file sort.c.
Referenced by InFunction(), and poly_sort().
CompareHSymbols()
WORD CompareHSymbols (PHEAD WORD * term1, WORD * term2, WORD par) extern
Compares terms that can have only SYMBOL and HAAKJE subterms. If term1 < term2 the return value is -1 If term1 > term2 the return value is 1 If term1 = term2 the return value is 0 par is a dummy parameter to make the parameter field identical to that of Compare1 which is the regular compare routine in sort.c
Definition at line 3113 of file sort.c.
NextPrime()
WORD NextPrime (PHEAD WORD num) extern
Gives the next prime number in the list of prime numbers.
If the list isn't long enough we expand it. For ease in ParForm and because these lists shouldn't be very big we let each worker keep its own list.
The list is cut off at MAXPOWER, because we don't want to get into trouble that the power of a variable gets larger than the prime number.
Definition at line 3664 of file reken.c.
Moebius()
WORD Moebius (PHEAD WORD) extern
Definition at line 3728 of file reken.c.
wranf()
UWORD wranf (PHEAD0) extern
Definition at line 3868 of file reken.c.
iranf()
UWORD iranf (PHEAD UWORD) extern
Definition at line 3887 of file reken.c.
iniwranf()
void iniwranf (PHEAD0) extern
Definition at line 3819 of file reken.c.
PreRandom()
UBYTE * PreRandom (UBYTE * s) extern
Definition at line 3912 of file reken.c.
TreatPolyRatFun()
int TreatPolyRatFun (PHEAD WORD * prf) extern
Definition at line 4943 of file normal.c.
ReadSaveHeader()
WORD ReadSaveHeader (VOID) extern
Reads the header in the save file and sets function pointers and flags according to the information found there. Must be called before any other ReadSave... function.
Currently works only for the exchange between 32bit and 64bit machines (WORD size must be 2 or 4 bytes)!
It is called by CoLoad().
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 4065 of file store.c.
ReadSaveIndex()
WORD ReadSaveIndex (FILEINDEX * fileind) extern
Reads a FILEINDEX from the open save file specified by AO.SaveData.Handle. Translations for adjusting endianness and data sizes are done if necessary.
Depends on the assumption that sizeof(FILEINDEX) is the same everywhere. If FILEINDEX or INDEXENTRY change, then this functions has to be adjusted.
Called by CoLoad() and FindInIndex().
Parameters
fileind contains the read FILEINDEX after successful return. must point to allocated, big enough memory.
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 4183 of file store.c.
References INFILEINDEX, FiLeInDeX::next, FiLeInDeX::number, and FuNcTiOn::number.
ReadSaveExpression()
WORD ReadSaveExpression (UBYTE * buffer, UBYTE * top, LONG * size, LONG * outsize) extern
Reads an expression from the open file specified by AO.SaveData.Handle. The endianness flip and a resizing without renumbering is done in this function. Thereafter the buffer consists of chunks with a uniform maximal word size (32bit at the moment). The actual renumbering is then done by calling the function ReadSaveTerm32(). The result is returned in buffer.
If the translation at some point doesn't fit into the buffer anymore, the function returns and must be called again. In any case size returns the number of successfully read bytes, outsize returns the number of successfully written bytes, and the file will be positioned at the next byte after the successfully read data.
It is called by PutInStore().
Parameters
buffer output buffer, holds the (translated) expression
top end of buffer
size number of read bytes
outsize number of written bytes
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 5146 of file store.c.
References ReadSaveTerm32().
ReadSaveTerm32()
UBYTE * ReadSaveTerm32 (UBYTE * bin, UBYTE * binend, UBYTE ** bout, UBYTE * boutend, UBYTE * top, int terminbuf) extern
Reads a single term from the given buffer at bin and write the translated term back to this buffer at bout.
ReadSaveTerm32() is currently the only instantiation of a ReadSaveTerm-function. It only deals with data that already has the correct endianness and that is resized to 32bit words but without being renumbered or translated in any other way. It uses the compress buffer AR.CompressBuffer.
The function is reentrant in order to cope with nested function arguments. It is called by ReadSaveExpression() and itself.
The return value indicates the position in the input buffer up to which the data has already been successfully processed. The parameter bout returns the corresponding position in the output buffer.
Parameters
bin start of the input buffer
binend end of the input buffer
bout as input points to the beginning of the output buffer, as output points behind the already translated data in the output buffer
boutend end of already decompressed data in output buffer
top end of output buffer
terminbuf flag whether decompressed data is already in the output buffer. used in recursive calls
Returns
pointer to the next unprocessed data in the input buffer
Definition at line 4736 of file store.c.
References ReadSaveTerm32().
Referenced by ReadSaveExpression(), and ReadSaveTerm32().
ReadSaveVariables()
WORD ReadSaveVariables (UBYTE * buffer, UBYTE * top, LONG * size, LONG * outsize, INDEXENTRY * ind, LONG * stage) extern
Reads the variables from the open file specified by AO.SaveData.Handle. It reads the *size bytes and writes them to the *buffer. It is called by PutInStore().
If translation is necessary, the data might shrink or grow in size, then *size is adjusted so that the reading and writing fits into the memory from the buffer to the top. The actual number of read bytes is returned in *size, the number of written bytes is returned in *outsize.
If the *size is smaller than the actual size of the variables, this function will be called several times and needs to remember the current position in the variable structure. The parameter stage does this job. When ReadSaveVariables() is called for the first time, this parameter should have the value -1.
The parameter ind is used to get the number of variables.
Parameters
buffer read variables are written into this allocated memory
top upper end of allocated memory
size number of bytes to read. might return a smaller number of read bytes if translation was necessary
outsize if translation has be done, outsize contains the number of written bytes
ind pointer of INDEXENTRY for the current expression. read-only
stage should be -1 for the first call, will be increased by ReadSaveVariables to memorize the position in the variable structure
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 4369 of file store.c.
References InDeXeNtRy::nfunctions, InDeXeNtRy::nindices, InDeXeNtRy::nsymbols, InDeXeNtRy::nvectors, and FuNcTiOn::spec.
WriteStoreHeader()
WORD WriteStoreHeader (WORD handle) extern
Writes header with information about system architecture and FORM revision to an open store file.
Called by SetFileIndex().
Parameters
handle specifies open file to which header will be written
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 3972 of file store.c.
References STOREHEADER::endianness, STOREHEADER::lenLONG, STOREHEADER::lenPOINTER, STOREHEADER::lenPOS, STOREHEADER::lenWORD, STOREHEADER::maxpower, STOREHEADER::sFun, STOREHEADER::sInd, STOREHEADER::sSym, STOREHEADER::sVec, and STOREHEADER::wildoffset.
Referenced by SetFileIndex().
InitRecovery()
void InitRecovery (VOID) extern
Sets up the strings for the filenames of the recovery files. This functions should only be called once to avoid memory leaks and after AM.TempDir has been initialized.
Definition at line 399 of file checkpoint.c.
CheckRecoveryFile()
int CheckRecoveryFile (VOID) extern
Checks whether a snapshot/recovery file exists. Returns 1 if it exists, 0 otherwise.
Definition at line 278 of file checkpoint.c.
References RecoveryFilename().
DeleteRecoveryFile()
void DeleteRecoveryFile (VOID) extern
Deletes the recovery files. It is called by CleanUp() in the case of a successful completion.
Definition at line 333 of file checkpoint.c.
RecoveryFilename()
char * RecoveryFilename (VOID) extern
Returns pointer to recovery filename.
Definition at line 364 of file checkpoint.c.
Referenced by CheckRecoveryFile(), and DoRecovery().
DoRecovery()
int DoRecovery (int * moduletype) extern
Reads from the recovery file and restores all necessary variables and states in FORM, so that the execution can recommence in preprocessor() as if no restart of FORM had occurred.
The recovery file is read into memory as a whole. The pointer p then points into this memory at the next non-processed data. The macros by which variables are restored, like R_SET, automatically increase p appropriately.
If something goes wrong, the function returns with a non-zero value.
Allocated memory that would be lost when overwriting the global structs with data from the file is freed first. A major part of the code deals with the restoration of pointers. The idiom we use is to memorize the original pointer value (org), allocate new memory and copy the data from the file into this memory, calculate the offset between the old pointer value and the new allocated memory position (ofs), and then correct all affected pointers (+=ofs).
We rely on the fact that several variables (especially in AM) are already assigned the correct values by the startup functions. That means, in principle, that a change in the setup files between snapshot creation and recovery will be noticed.
Definition at line 1402 of file checkpoint.c.
References TaBlEs::argtail, TaBlEs::boomlijst, BrAcKeTiNfO::bracketbuffer, TaBlEs::buffers, TaBlEs::bufferssize, CopyFile(), TaBlEs::flags, ReNuMbEr::func, ReNuMbEr::funnum, VaRrEnUm::hi, BrAcKeTiNfO::indexbuffer, ReNuMbEr::indi, ReNuMbEr::indnum, VaRrEnUm::lo, TaBlEs::MaxTreeSize, TaBlEs::mm, TaBlEs::numind, TaBlEs::pattern, TaBlEs::prototype, TaBlEs::prototypeSize, RecoveryFilename(), ExPrEsSiOn::renumlists, TaBlEs::reserved, TaBlEs::spare, TaBlEs::sparse, VaRrEnUm::start, ReNuMbEr::symb, ReNuMbEr::symnum, TaBlEs::tablepointers, TimeWallClock(), TaBlEs::totind, ReNuMbEr::vecnum, and ReNuMbEr::vect.
DoCheckpoint()
void DoCheckpoint (int moduletype) extern
Checks whether a snapshot should be done. Calls DoSnapshot() to create the snapshot.
Definition at line 3111 of file checkpoint.c.
References PF_BroadcastNumber(), PF_RecvFile(), PF_SendFile(), and TimeWallClock().
NumberMallocAddMemory()
VOID NumberMallocAddMemory (PHEAD0) extern
Definition at line 2654 of file tools.c.
CacheNumberMallocAddMemory()
VOID CacheNumberMallocAddMemory (PHEAD0) extern
Definition at line 2728 of file tools.c.
TermMallocAddMemory()
VOID TermMallocAddMemory (PHEAD0) extern
Definition at line 2550 of file tools.c.
ExprStatus()
void ExprStatus (EXPRESSIONS e) extern
Definition at line 66 of file bugtool.c.
iniTools()
VOID iniTools (VOID) extern
Definition at line 2201 of file tools.c.
TestTerm()
int TestTerm (WORD * term) extern
Tests the consistency of the term. Returns 0 when the term is OK. Any nonzero value is trouble. In the current version the testing isn't 100% complete. For instance, we don't check the validity of the symbols nor do we check the range of their powers. Etc. This should be extended when the need is there.
Parameters
term the term to be tested
Definition at line 3862 of file tools.c.
References TestTerm().
Referenced by TestTerm().
RunTransform()
WORD RunTransform (PHEAD WORD * term, WORD * params) extern
Definition at line 732 of file transform.c.
RunEncode()
WORD RunEncode (PHEAD WORD * fun, WORD * args, WORD * info) extern
Definition at line 982 of file transform.c.
RunDecode()
WORD RunDecode (PHEAD WORD * fun, WORD * args, WORD * info) extern
Definition at line 1169 of file transform.c.
RunReplace()
WORD RunReplace (PHEAD WORD * fun, WORD * args, WORD * info) extern
Definition at line 1339 of file transform.c.
RunImplode()
WORD RunImplode (WORD * fun, WORD * args) extern
Definition at line 1817 of file transform.c.
RunExplode()
WORD RunExplode (PHEAD WORD * fun, WORD * args) extern
Definition at line 2018 of file transform.c.
TestArgNum()
int TestArgNum (int n, int totarg, WORD * args) extern
Definition at line 3277 of file transform.c.
PutArgInScratch()
WORD PutArgInScratch (WORD * arg, UWORD * scrat) extern
Definition at line 3346 of file transform.c.
ReadRange()
UBYTE * ReadRange (UBYTE * s, WORD * out, int par) extern
Definition at line 3382 of file transform.c.
FindRange()
int FindRange (PHEAD WORD * args, WORD * arg1, WORD * arg2, WORD totarg) extern
Definition at line 3542 of file transform.c.
RunPermute()
WORD RunPermute (PHEAD WORD * fun, WORD * args, WORD * info) extern
Definition at line 2132 of file transform.c.
RunReverse()
WORD RunReverse (PHEAD WORD * fun, WORD * args) extern
Definition at line 2359 of file transform.c.
RunCycle()
WORD RunCycle (PHEAD WORD * fun, WORD * args, WORD * info) extern
Definition at line 2535 of file transform.c.
RunAddArg()
WORD RunAddArg (PHEAD WORD * fun, WORD * args) extern
Definition at line 2687 of file transform.c.
RunMulArg()
WORD RunMulArg (PHEAD WORD * fun, WORD * args) extern
Definition at line 2774 of file transform.c.
RunIsLyndon()
WORD RunIsLyndon (PHEAD WORD * fun, WORD * args, int par) extern
Definition at line 2913 of file transform.c.
RunToLyndon()
WORD RunToLyndon (PHEAD WORD * fun, WORD * args, int par) extern
Definition at line 2991 of file transform.c.
RunDropArg()
WORD RunDropArg (PHEAD WORD * fun, WORD * args) extern
Definition at line 3103 of file transform.c.
RunSelectArg()
WORD RunSelectArg (PHEAD WORD * fun, WORD * args) extern
Definition at line 3129 of file transform.c.
RunDedup()
WORD RunDedup (PHEAD WORD * fun, WORD * args) extern
Definition at line 2446 of file transform.c.
RunZtoHArg()
WORD RunZtoHArg (PHEAD WORD * fun, WORD * args) extern
Definition at line 3157 of file transform.c.
RunHtoZArg()
WORD RunHtoZArg (PHEAD WORD * fun, WORD * args) extern
Definition at line 3212 of file transform.c.
NormPolyTerm()
int NormPolyTerm (PHEAD WORD * term) extern
Definition at line 53 of file notation.c.
ConvertToPoly()
int ConvertToPoly (PHEAD WORD * term, WORD * outterm, WORD * comlist, WORD par) extern
Definition at line 307 of file notation.c.
LocalConvertToPoly()
int LocalConvertToPoly (PHEAD WORD * term, WORD * outterm, WORD startebuf, WORD par) extern
Converts a generic term to polynomial notation in which there are only symbols and brackets. During conversion there will be only symbols. Brackets are stripped. Objects that need 'translation' are put inside a special compiler buffer and represented by a symbol. The numbering of the extra symbols is down from the maximum. In principle there can be a problem when running into the already assigned ones. This uses the FindTree for searching in the global tree and then looks further in the AT.ebufnum. This allows fully parallel processing. Hence we need no locks. Cannot be used in the same module as ConvertToPoly.
Definition at line 510 of file notation.c.
Referenced by poly_factorize_expression().
ConvertFromPoly()
int ConvertFromPoly (PHEAD WORD * term, WORD * outterm, WORD from, WORD to, WORD offset, WORD par) extern
Definition at line 660 of file notation.c.
FindSubterm()
WORD FindSubterm (WORD * subterm) extern
Definition at line 773 of file notation.c.
FindLocalSubterm()
WORD FindLocalSubterm (PHEAD WORD * subterm, WORD startebuf) extern
Definition at line 842 of file notation.c.
PrintSubtermList()
void PrintSubtermList (int from, int to) extern
Definition at line 895 of file notation.c.
PrintExtraSymbol()
void PrintExtraSymbol (int num, WORD * terms, int par) extern
Definition at line 1007 of file notation.c.
FindSubexpression()
WORD FindSubexpression (WORD * subexpr) extern
Definition at line 1094 of file notation.c.
UpdateMaxSize()
void UpdateMaxSize (VOID) extern
Definition at line 1610 of file tools.c.
CoToPolynomial()
int CoToPolynomial (UBYTE * inp) extern
Definition at line 5898 of file compcomm.c.
CoFromPolynomial()
int CoFromPolynomial (UBYTE * inp) extern
Definition at line 5973 of file compcomm.c.
CoArgToExtraSymbol()
int CoArgToExtraSymbol (UBYTE * s) extern
Definition at line 5999 of file compcomm.c.
CoExtraSymbols()
int CoExtraSymbols (UBYTE * inp) extern
Definition at line 6049 of file compcomm.c.
GetDoParam()
UBYTE * GetDoParam (UBYTE * inp, WORD ** wp, int par) extern
Definition at line 6180 of file compcomm.c.
GetIfDollarFactor()
WORD * GetIfDollarFactor (UBYTE ** inp, WORD * w) extern
Definition at line 6122 of file compcomm.c.
CoDo()
int CoDo (UBYTE * inp) extern
Definition at line 6257 of file compcomm.c.
CoEndDo()
int CoEndDo (UBYTE * inp) extern
Definition at line 6360 of file compcomm.c.
ExtraSymFun()
int ExtraSymFun (PHEAD WORD * term, WORD level) extern
Definition at line 1146 of file notation.c.
PruneExtraSymbols()
int PruneExtraSymbols (WORD downto) extern
Definition at line 1214 of file notation.c.
IniFbuffer()
int IniFbuffer (WORD bufnum) extern
Initialize a factorization cache buffer. We set the size of the rhs and boomlijst buffers immediately to their final values.
Definition at line 614 of file comtool.c.
References tree::blnce, CbUf::boomlijst, CbUf::CanCommu, CbUf::dimension, tree::left, CbUf::numdum, CbUf::NumTerms, tree::parent, CbUf::rhs, tree::right, tree::usage, and tree::value.
GCDfunction()
int GCDfunction (PHEAD WORD * term, WORD level) extern
Definition at line 609 of file ratio.c.
GCDfunction3()
WORD * GCDfunction3 (PHEAD WORD * in1, WORD * in2) extern
Definition at line 1141 of file ratio.c.
ReadPolyRatFun()
int ReadPolyRatFun (PHEAD WORD * term) extern
Definition at line 2264 of file ratio.c.
FromPolyRatFun()
int FromPolyRatFun (PHEAD WORD * fun, WORD ** numout, WORD ** denout) extern
Definition at line 2383 of file ratio.c.
PolyDiv()
WORD * PolyDiv (PHEAD WORD * a, WORD * b, char * text) extern
Definition at line 2741 of file ratio.c.
GCDclean()
void GCDclean (PHEAD WORD * num, WORD * den) extern
Definition at line 2644 of file ratio.c.
TakeSymbolContent()
WORD * TakeSymbolContent (PHEAD WORD * in, WORD * term) extern
Implements part of the old ExecArg in which we take common factors from arguments with more than one term. We allow only symbols as this code is used for the polyratfun only. We have a special routine, because the generic TakeContent does too much work and speed is at a premium here. Input: in is the input expression as a sequence of terms. Output: term: the content return value: the contentfree expression. it is in new allocation, made by TermMalloc. (should be in a TermMalloc space?)
Definition at line 2434 of file ratio.c.
References GetModInverses().
GCDterms()
int GCDterms (PHEAD WORD * term1, WORD * term2, WORD * termout) extern
Definition at line 2076 of file ratio.c.
PutExtraSymbols()
WORD * PutExtraSymbols (PHEAD WORD * in, WORD startebuf, int * actionflag) extern
Definition at line 1244 of file ratio.c.
TakeExtraSymbols()
WORD * TakeExtraSymbols (PHEAD WORD * in, WORD startebuf) extern
Definition at line 1273 of file ratio.c.
MultiplyWithTerm()
WORD * MultiplyWithTerm (PHEAD WORD * in, WORD * term, WORD par) extern
Definition at line 1312 of file ratio.c.
TakeContent()
WORD * TakeContent (PHEAD WORD * in, WORD * term) extern
Implements part of the old ExecArg in which we take common factors from arguments with more than one term. Here the input is a sequence of terms in 'in' and the answer is a content-free sequence of terms. This sequence has been allocated by the Malloc1 routine in a call to EndSort, unless the expression was already content-free. In that case the input pointer is returned. The content is returned in term. This is supposed to be a separate allocation, made by TermMalloc in the calling routine.
Definition at line 1376 of file ratio.c.
References GetModInverses().
MergeSymbolLists()
int MergeSymbolLists (PHEAD WORD * old, WORD * extra, int par) extern
Definition at line 1808 of file ratio.c.
MergeDotproductLists()
int MergeDotproductLists (PHEAD WORD * old, WORD * extra, int par) extern
Definition at line 1927 of file ratio.c.
CreateExpression()
WORD * CreateExpression (PHEAD WORD) extern
Definition at line 2020 of file ratio.c.
DIVfunction()
int DIVfunction (PHEAD WORD * term, WORD level, int par) extern
Definition at line 2788 of file ratio.c.
MULfunc()
WORD * MULfunc (PHEAD WORD * p1, WORD * p2) extern
Definition at line 2957 of file ratio.c.
ConvertArgument()
WORD * ConvertArgument (PHEAD WORD * arg, int * type) extern
Definition at line 3018 of file ratio.c.
ExpandRat()
int ExpandRat (PHEAD WORD * fun) extern
Definition at line 3113 of file ratio.c.
InvPoly()
int InvPoly (PHEAD WORD * inpoly, WORD maxpow, WORD sym) extern
Definition at line 3592 of file ratio.c.
TestDoLoop()
WORD TestDoLoop (PHEAD WORD * lhsbuf, WORD level) extern
Definition at line 2753 of file dollar.c.
TestEndDoLoop()
WORD TestEndDoLoop (PHEAD WORD * lhsbuf, WORD level) extern
Definition at line 2831 of file dollar.c.
poly_gcd()
WORD * poly_gcd (PHEAD WORD * a, WORD * b, WORD fit) extern
Polynomial gcd
Description
This method calculates the greatest common divisor of two polynomials, given by two zero-terminated Form-style term lists.
Notes
The result is written at newly allocated memory
Called from ratio.c
Calls polygcd::gcd
Definition at line 124 of file polywrap.cc.
References poly_determine_modulus().
poly_div()
WORD * poly_div (PHEAD WORD * a, WORD * b, WORD fit) extern
Definition at line 435 of file polywrap.cc.
poly_rem()
WORD * poly_rem (PHEAD WORD * a, WORD * b, WORD fit) extern
Definition at line 463 of file polywrap.cc.
poly_inverse()
WORD * poly_inverse (PHEAD WORD * arga, WORD * argb) extern
Definition at line 1730 of file polywrap.cc.
poly_mul()
WORD * poly_mul (PHEAD WORD * a, WORD * b) extern
Definition at line 1935 of file polywrap.cc.
poly_ratfun_add()
WORD * poly_ratfun_add (PHEAD WORD * t1, WORD * t2) extern
Addition of PolyRatFuns
Description
This method gets two pointers to polyratfuns with up to two arguments each and calculates the sum.
Notes
The result is written at the workpointer
Called from sort.c and threads.c
Calls poly::operators and polygcd::gcd
Definition at line 633 of file polywrap.cc.
References poly_determine_modulus(), poly_ratfun_read(), and poly_sort().
Referenced by AddPoly(), and MergePatches().
poly_ratfun_normalize()
int poly_ratfun_normalize (PHEAD WORD * term) extern
Multiplication/normalization of PolyRatFuns
Description
This method searches a term for multiple polyratfuns and multiplies their contents. The result is properly normalized. Normalization also works for terms with a single polyratfun.
Notes
The result overwrites the original term
Called from proces.c
Calls poly::operators and polygcd::gcd
Definition at line 762 of file polywrap.cc.
References poly_determine_modulus(), poly_ratfun_read(), and poly_sort().
Referenced by PolyFunMul(), and PrepPoly().
poly_factorize_argument()
int poly_factorize_argument (PHEAD WORD * argin, WORD * argout) extern
Factorization of function arguments
Description
This method factorizes the Form-style argument argin.
Notes
The result is written at argout
Called from argument.c
Calls poly_factorize
Definition at line 1099 of file polywrap.cc.
References poly_factorize().
poly_factorize_dollar()
WORD * poly_factorize_dollar (PHEAD WORD * argin) extern
Factorization of dollar variables
Description
This method factorizes a dollar variable.
Notes
The result is written at newly allocated memory.
Called from dollar.c
Calls poly_factorize
Definition at line 1133 of file polywrap.cc.
References poly_factorize().
poly_factorize_expression()
int poly_factorize_expression (EXPRESSIONS expr) extern
Factorization of expressions
Description
This method factorizes an expression.
Notes
The result overwrites the input expression
Called from proces.c
Calls polyfact::factorize
Definition at line 1165 of file polywrap.cc.
References EndSort(), Generator(), FiLe::handle, LocalConvertToPoly(), LowerSortLevel(), NewSort(), and poly_determine_modulus().
Referenced by PF_Processor(), and Processor().
poly_unfactorize_expression()
int poly_unfactorize_expression (EXPRESSIONS expr) extern
Unfactorization of expressions
Description
This method expands a factorized expression.
Notes
The result overwrites the input expression
Called from proces.c
Definition at line 1522 of file polywrap.cc.
References EndSort(), Generator(), FiLe::handle, LowerSortLevel(), and NewSort().
Referenced by PF_Processor(), and Processor().
poly_free_poly_vars()
void poly_free_poly_vars (PHEAD const char * text) extern
Definition at line 2001 of file polywrap.cc.
optimize_print_code()
VOID optimize_print_code (int print_expr) extern
Print optimized code
Description
This method prints the optimized code via "PrintExtraSymbol". Depending on the flag, the original expression is printed (for "Print") or not (for "#Optimize / #write "O").
Definition at line 4525 of file optimize.cc.
Referenced by Optimize().
DoPreAdd()
int DoPreAdd (UBYTE * s) extern
Definition at line 1067 of file dict.c.
DoPreUseDictionary()
int DoPreUseDictionary (UBYTE * s) extern
Definition at line 1022 of file dict.c.
DoPreCloseDictionary()
int DoPreCloseDictionary (UBYTE * s) extern
Definition at line 998 of file dict.c.
DoPreOpenDictionary()
int DoPreOpenDictionary (UBYTE * s) extern
Definition at line 959 of file dict.c.
RemoveDictionary()
void RemoveDictionary (DICTIONARY * dict) extern
Definition at line 902 of file dict.c.
UnSetDictionary()
void UnSetDictionary (VOID) extern
Definition at line 883 of file dict.c.
SetDictionaryOptions()
int SetDictionaryOptions (UBYTE * options) extern
Definition at line 790 of file dict.c.
AddToDictionary()
int AddToDictionary (DICTIONARY * dict, UBYTE * left, UBYTE * right) extern
Definition at line 491 of file dict.c.
AddDictionary()
int AddDictionary (UBYTE * name) extern
Definition at line 449 of file dict.c.
FindDictionary()
int FindDictionary (UBYTE * name) extern
Definition at line 434 of file dict.c.
IsExponentSign()
UBYTE * IsExponentSign (VOID) extern
Definition at line 238 of file dict.c.
IsMultiplySign()
UBYTE * IsMultiplySign (VOID) extern
Definition at line 218 of file dict.c.
TransformRational()
VOID TransformRational (UWORD * a, WORD na) extern
Definition at line 71 of file dict.c.
WriteDictionary()
void WriteDictionary (DICTIONARY * dict) extern
Definition at line 1307 of file sch.c.
ShrinkDictionary()
void ShrinkDictionary (DICTIONARY * dict) extern
Definition at line 945 of file dict.c.
MultiplyToLine()
void MultiplyToLine (VOID) extern
Definition at line 671 of file sch.c.
FindSymbol()
UBYTE * FindSymbol (WORD num) extern
Definition at line 258 of file dict.c.
FindVector()
UBYTE * FindVector (WORD num) extern
Definition at line 279 of file dict.c.
FindIndex()
UBYTE * FindIndex (WORD num) extern
Definition at line 301 of file dict.c.
FindFunction()
UBYTE * FindFunction (WORD num) extern
Definition at line 323 of file dict.c.
FindFunWithArgs()
UBYTE * FindFunWithArgs (WORD * t) extern
Definition at line 345 of file dict.c.
FindExtraSymbol()
UBYTE * FindExtraSymbol (WORD num) extern
Definition at line 377 of file dict.c.
DictToBytes()
LONG DictToBytes (DICTIONARY * dict, UBYTE * buf) extern
Definition at line 1119 of file dict.c.
DictFromBytes()
DICTIONARY * DictFromBytes (UBYTE * buf) extern
Definition at line 1152 of file dict.c.
CoCreateSpectator()
int CoCreateSpectator (UBYTE * inp) extern
Definition at line 89 of file spectator.c.
CoToSpectator()
int CoToSpectator (UBYTE * inp) extern
Definition at line 181 of file spectator.c.
CoRemoveSpectator()
int CoRemoveSpectator (UBYTE * inp) extern
Definition at line 233 of file spectator.c.
CoEmptySpectator()
int CoEmptySpectator (UBYTE * inp) extern
Definition at line 293 of file spectator.c.
CoCopySpectator()
int CoCopySpectator (UBYTE * inp) extern
Definition at line 459 of file spectator.c.
PutInSpectator()
int PutInSpectator (WORD * term, WORD specnum) extern
Definition at line 345 of file spectator.c.
ClearSpectators()
void ClearSpectators (WORD par) extern
Definition at line 675 of file spectator.c.
GetFromSpectator()
WORD GetFromSpectator (WORD * term, WORD specnum) extern
Definition at line 601 of file spectator.c.
FlushSpectators()
void FlushSpectators (VOID) extern
Definition at line 402 of file spectator.c.
ReadFromScratch()
int ReadFromScratch (FILEHANDLE * fi, POSITION * pos, UBYTE * buffer, POSITION * length) extern
Definition at line 273 of file store.c.
AddToScratch()
int AddToScratch (FILEHANDLE * fi, POSITION * pos, UBYTE * buffer, POSITION * length, int withflush) extern
Definition at line 300 of file store.c.
DoPreAppendPath()
int DoPreAppendPath (UBYTE * s) extern
Appends the given path (absolute or relative to the current file directory) to the FORM path.
Syntax: #appendpath <path>
Definition at line 7153 of file pre.c.
DoPrePrependPath()
int DoPrePrependPath (UBYTE * s) extern
Prepends the given path (absolute or relative to the current file directory) to the FORM path.
Syntax: #prependpath <path>
Definition at line 7170 of file pre.c.
DoSwitch()
int DoSwitch (PHEAD WORD * term, WORD * lhs) extern
Definition at line 1070 of file if.c.
DoEndSwitch()
int DoEndSwitch (PHEAD WORD * term, WORD * lhs) extern
Definition at line 1086 of file if.c.
FindCase()
SWITCHTABLE * FindCase (WORD nswitch, WORD ncase) extern
Definition at line 1097 of file if.c.
SwitchSplitMergeRec()
VOID SwitchSplitMergeRec (SWITCHTABLE * array, WORD num, SWITCHTABLE * auxarray) extern
Definition at line 1184 of file if.c.
SwitchSplitMerge()
VOID SwitchSplitMerge (SWITCHTABLE * array, WORD num) extern
Definition at line 1213 of file if.c.
DoubleSwitchBuffers()
int DoubleSwitchBuffers (VOID) extern
Definition at line 1135 of file if.c.
DistrN()
int DistrN (int n, int * cpl, int ncpl, int * scratch) extern
Definition at line 4048 of file tools.c.
DoNamespace()
int DoNamespace (UBYTE * s) extern
Definition at line 7234 of file pre.c.
DoEndNamespace()
int DoEndNamespace (UBYTE * s) extern
Definition at line 7282 of file pre.c.
DoUse()
int DoUse (UBYTE * s) extern
Definition at line 7497 of file pre.c.
SkipName()
UBYTE * SkipName (UBYTE * s) extern
Definition at line 7305 of file pre.c.
ConstructName()
UBYTE * ConstructName (UBYTE * s, UBYTE type) extern
Definition at line 7405 of file pre.c.
DoSetUserFlag()
int DoSetUserFlag (UBYTE * s) extern
Definition at line 7662 of file pre.c.
DoClearUserFlag()
int DoClearUserFlag (UBYTE * s) extern
Definition at line 7652 of file pre.c.
CreateVertex()
VERTEX * CreateVertex (MODEL * m)
Definition at line 46 of file model.c.
ReadParticle()
UBYTE * ReadParticle (UBYTE * s, VERTEX * v, MODEL * m, int par)
Definition at line 76 of file model.c.
CoModel()
int CoModel (UBYTE * s)
Definition at line 119 of file model.c.
CoParticle()
int CoParticle (UBYTE * s)
Definition at line 194 of file model.c.
CoVertex()
int CoVertex (UBYTE * s)
Definition at line 276 of file model.c.
CoEndModel()
int CoEndModel (UBYTE * s)
Definition at line 379 of file model.c.
LoadModel()
int LoadModel (MODEL * m)
Definition at line 27 of file diawrap.cc.
CoSetUserFlag()
int CoSetUserFlag (UBYTE * s)
Definition at line 7357 of file compcomm.c.
CoClearUserFlag()
int CoClearUserFlag (UBYTE * s)
Definition at line 7385 of file compcomm.c.
CoCreateAllLoops()
int CoCreateAllLoops (UBYTE * s)
Definition at line 7422 of file compcomm.c.
CoCreateAllPaths()
int CoCreateAllPaths (UBYTE * s)
Definition at line 7542 of file compcomm.c.
CoCreateAll()
int CoCreateAll (UBYTE * s)
Definition at line 7670 of file compcomm.c.
AllLoops()
WORD AllLoops (PHEAD WORD * term, WORD level)
Definition at line 650 of file lus.c.
StartLoops()
LONG StartLoops (PHEAD WORD * term, WORD level, LONG vert, WORD nvert, WORD * arglist, WORD nargs, WORD * loop, WORD nloop)
Definition at line 894 of file lus.c.
GenLoops()
LONG GenLoops (PHEAD WORD * term, WORD level, LONG vert, WORD nvert, WORD * arglist, WORD nargs, WORD * loop, WORD nloop)
Definition at line 980 of file lus.c.
LoopOutput()
void LoopOutput (PHEAD WORD * term, WORD level, WORD * loop, WORD nloop)
Definition at line 1059 of file lus.c.
AllPaths()
WORD AllPaths (PHEAD WORD * term, WORD level)
Definition at line 1123 of file lus.c.
GenPaths()
LONG GenPaths (PHEAD WORD * term, WORD level, LONG vert, WORD nvert, WORD * arglist, WORD nargs, WORD * path, WORD npath)
Definition at line 1413 of file lus.c.
PathOutput()
void PathOutput (PHEAD WORD * term, WORD level, WORD * path, WORD npath)
Definition at line 1486 of file lus.c.