FORM: startup.c File Reference
startup.c File Reference
#include "form3.h"
#include "inivar.h"
#include <signal.h>
Macros
#define STRINGIFY(x) STRINGIFY__(x)
#define STRINGIFY__(x) #x
#define FORMNAME "FORM"
#define VERSIONSTR__ STRINGIFY(MAJORVERSION) "." STRINGIFY(MINORVERSION) "Beta"
#define VERSIONSTR FORMNAME " " VERSIONSTR__ " (" PRODUCTIONDATE ")"
#define TAKEPATH(x) if(s[1]== '='){x=s+2;} else{x=*argv++;argc--;}
#define DEFAULTFNAMELENGTH 16
Functions
int DoTail (int argc, UBYTE **argv)
int OpenInput (VOID)
VOID ReserveTempFiles (int par)
VOID StartVariables (VOID)
VOID StartMore (VOID)
WORD IniVars (VOID)
int main (int argc, char **argv)
VOID CleanUp (WORD par)
VOID TerminateImpl (int errorcode, const char *file, int line, const char *function)
void PrintDeprecation (const char *feature, const char *issue)
VOID PrintRunningTime (VOID)
LONG GetRunningTime (VOID)
Variables
UBYTE * emptystring = (UBYTE *)"."
UBYTE * defaulttempfilename = (UBYTE *)"xformxxx.str"
Detailed Description
This file contains the main program. It also deals with the very early stages of the startup of FORM and the final stages when the program attempts some cleanup. Here is the routine that analyses the command tail.
Definition in file startup.c.
Macro Definition Documentation
STRINGIFY
#define STRINGIFY (x) STRINGIFY__(x)
Definition at line 57 of file startup.c.
STRINGIFY__
#define STRINGIFY__ (x) #x
Definition at line 58 of file startup.c.
FORMNAME
#define FORMNAME "FORM"
Definition at line 68 of file startup.c.
VERSIONSTR__
#define VERSIONSTR__ STRINGIFY(MAJORVERSION) "." STRINGIFY(MINORVERSION) "Beta"
Definition at line 97 of file startup.c.
VERSIONSTR
#define VERSIONSTR FORMNAME " " VERSIONSTR__ " (" PRODUCTIONDATE ")"
Definition at line 101 of file startup.c.
TAKEPATH
#define TAKEPATH (x) if(s[1]== '='){x=s+2;} else{x=*argv++;argc--;}
Definition at line 235 of file startup.c.
DEFAULTFNAMELENGTH
#define DEFAULTFNAMELENGTH 16
Definition at line 664 of file startup.c.
Function Documentation
DoTail()
int DoTail (int argc, UBYTE ** argv)
Definition at line 237 of file startup.c.
OpenInput()
int OpenInput (VOID)
Definition at line 542 of file startup.c.
ReserveTempFiles()
VOID ReserveTempFiles (int par)
Definition at line 666 of file startup.c.
StartVariables()
VOID StartVariables (VOID)
All functions (well, nearly all) are declared here.
Definition at line 905 of file startup.c.
References AddNtoC(), AddRHS(), Compare1(), inicbufs(), FuNcTiOn::name, PF_BroadcastNumber(), PutPreVar(), and FuNcTiOn::symmetric.
StartMore()
VOID StartMore (VOID)
Definition at line 1316 of file startup.c.
IniVars()
WORD IniVars (VOID)
Definition at line 1354 of file startup.c.
main()
int main (int argc, char ** argv)
Definition at line 1660 of file startup.c.
CleanUp()
VOID CleanUp (WORD par)
Definition at line 1759 of file startup.c.
TerminateImpl()
VOID TerminateImpl (int errorcode, const char * file, int line, const char * function)
Definition at line 1848 of file startup.c.
PrintDeprecation()
void PrintDeprecation (const char * feature, const char * issue)
Prints a deprecation warning for a given feature.
Parameters
feature The name of the deprecated feature.
issue The associated issue, e.g., "issues/700".
Definition at line 2061 of file startup.c.
PrintRunningTime()
VOID PrintRunningTime (VOID)
Definition at line 2085 of file startup.c.
GetRunningTime()
LONG GetRunningTime (VOID)
Definition at line 2126 of file startup.c.
Variable Documentation
emptystring
UBYTE* emptystring = (UBYTE *)"."
Definition at line 660 of file startup.c.
defaulttempfilename
UBYTE* defaulttempfilename = (UBYTE *)"xformxxx.str"
Definition at line 661 of file startup.c.