FORM: store.c File Reference
store.c File Reference
#include "form3.h"
Macros
#define SAVEREVISION 0x02
Functions
WORD OpenTemp (void)
void SeekScratch (FILEHANDLE *fi, POSITION *pos)
void SetEndScratch (FILEHANDLE *f, POSITION *position)
void SetEndHScratch (FILEHANDLE *f, POSITION *position)
void SetScratch (FILEHANDLE *f, POSITION *position)
WORD RevertScratch (void)
WORD ResetScratch (void)
int ReadFromScratch (FILEHANDLE *fi, POSITION *pos, UBYTE *buffer, POSITION *length)
int AddToScratch (FILEHANDLE *fi, POSITION *pos, UBYTE *buffer, POSITION *length, int withflush)
int CoSave (UBYTE *inp)
int CoLoad (UBYTE *inp)
WORD DeleteStore (WORD par)
WORD PutInStore (INDEXENTRY *ind, WORD num)
WORD GetTerm (PHEAD WORD *term)
WORD GetOneTerm (PHEAD WORD *term, FILEHANDLE *fi, POSITION *pos, int par)
WORD GetMoreTerms (WORD *term)
WORD GetMoreFromMem (WORD *term, WORD **tpoin)
WORD GetFromStore (WORD *to, POSITION *position, RENUMBER renumber, WORD *InCompState, WORD nexpr)
void DetVars (WORD *term, WORD par)
WORD ToStorage (EXPRESSIONS e, POSITION *length)
INDEXENTRY * NextFileIndex (POSITION *indexpos)
WORD SetFileIndex (void)
WORD VarStore (UBYTE *s, WORD n, WORD name, WORD namesize)
WORD TermRenumber (WORD *term, RENUMBER renumber, WORD nexpr)
WORD FindrNumber (WORD n, VARRENUM *v)
INDEXENTRY * FindInIndex (WORD expr, FILEDATA *f, WORD par, WORD mode)
RENUMBER GetTable (WORD expr, POSITION *position, WORD mode)
int CopyExpression (FILEHANDLE *from, FILEHANDLE *to)
WORD WriteStoreHeader (WORD handle)
WORD ReadSaveHeader (void)
WORD ReadSaveIndex (FILEINDEX *fileind)
WORD ReadSaveVariables (UBYTE *buffer, UBYTE *top, LONG *size, LONG *outsize, INDEXENTRY *ind, LONG *stage)
UBYTE * ReadSaveTerm32 (UBYTE *bin, UBYTE *binend, UBYTE **bout, UBYTE *boutend, UBYTE *top, int terminbuf)
WORD ReadSaveExpression (UBYTE *buffer, UBYTE *top, LONG *size, LONG *outsize)
Detailed Description
Contains all functions that deal with store-files and the system independent save-files.
Definition in file store.c.
Macro Definition Documentation
SAVEREVISION
#define SAVEREVISION 0x02
Definition at line 3961 of file store.c.
Function Documentation
OpenTemp()
WORD OpenTemp (void)
Definition at line 48 of file store.c.
SeekScratch()
void SeekScratch (FILEHANDLE * fi, POSITION * pos)
Definition at line 64 of file store.c.
SetEndScratch()
void SetEndScratch (FILEHANDLE * f, POSITION * position)
Definition at line 75 of file store.c.
SetEndHScratch()
void SetEndHScratch (FILEHANDLE * f, POSITION * position)
Definition at line 89 of file store.c.
SetScratch()
void SetScratch (FILEHANDLE * f, POSITION * position)
Definition at line 115 of file store.c.
RevertScratch()
WORD RevertScratch (void)
Definition at line 190 of file store.c.
ResetScratch()
WORD ResetScratch (void)
Definition at line 235 of file store.c.
ReadFromScratch()
int ReadFromScratch (FILEHANDLE * fi, POSITION * pos, UBYTE * buffer, POSITION * length)
Definition at line 273 of file store.c.
AddToScratch()
int AddToScratch (FILEHANDLE * fi, POSITION * pos, UBYTE * buffer, POSITION * length, int withflush)
Definition at line 300 of file store.c.
CoSave()
int CoSave (UBYTE * inp)
Definition at line 363 of file store.c.
CoLoad()
int CoLoad (UBYTE * inp)
Definition at line 573 of file store.c.
DeleteStore()
WORD DeleteStore (WORD par)
Definition at line 773 of file store.c.
PutInStore()
WORD PutInStore (INDEXENTRY * ind, WORD num)
Definition at line 874 of file store.c.
GetTerm()
WORD GetTerm (PHEAD WORD * term)
Definition at line 993 of file store.c.
GetOneTerm()
WORD GetOneTerm (PHEAD WORD * term, FILEHANDLE * fi, POSITION * pos, int par)
Definition at line 1268 of file store.c.
GetMoreTerms()
WORD GetMoreTerms (WORD * term)
Definition at line 1426 of file store.c.
GetMoreFromMem()
WORD GetMoreFromMem (WORD * term, WORD ** tpoin)
Definition at line 1522 of file store.c.
GetFromStore()
WORD GetFromStore (WORD * to, POSITION * position, RENUMBER renumber, WORD * InCompState, WORD nexpr)
Definition at line 1629 of file store.c.
DetVars()
void DetVars (WORD * term, WORD par)
Definition at line 1830 of file store.c.
ToStorage()
WORD ToStorage (EXPRESSIONS e, POSITION * length)
Definition at line 2017 of file store.c.
NextFileIndex()
INDEXENTRY * NextFileIndex (POSITION * indexpos)
Definition at line 2258 of file store.c.
SetFileIndex()
WORD SetFileIndex (void)
Reads the next file index and puts it into AR.StoreData.Index. TODO
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 2321 of file store.c.
References WriteStoreHeader().
VarStore()
WORD VarStore (UBYTE * s, WORD n, WORD name, WORD namesize)
Definition at line 2370 of file store.c.
TermRenumber()
WORD TermRenumber (WORD * term, RENUMBER renumber, WORD nexpr)
!! WORD *memterm=term; static LONG ctrap=0; !!!
!! ctrap++; !!!
Definition at line 2428 of file store.c.
References ReNuMbEr::func, ReNuMbEr::funnum, ReNuMbEr::indi, ReNuMbEr::indnum, ReNuMbEr::symb, ReNuMbEr::symnum, TermRenumber(), ReNuMbEr::vecnum, and ReNuMbEr::vect.
Referenced by TermRenumber().
FindrNumber()
WORD FindrNumber (WORD n, VARRENUM * v)
Definition at line 2588 of file store.c.
FindInIndex()
INDEXENTRY * FindInIndex (WORD expr, FILEDATA * f, WORD par, WORD mode)
Definition at line 2665 of file store.c.
GetTable()
RENUMBER GetTable (WORD expr, POSITION * position, WORD mode)
Definition at line 2826 of file store.c.
CopyExpression()
int CopyExpression (FILEHANDLE * from, FILEHANDLE * to)
Definition at line 3308 of file store.c.
WriteStoreHeader()
WORD WriteStoreHeader (WORD handle)
Writes header with information about system architecture and FORM revision to an open store file.
Called by SetFileIndex().
Parameters
handle specifies open file to which header will be written
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 3972 of file store.c.
References STOREHEADER::endianness, STOREHEADER::lenLONG, STOREHEADER::lenPOINTER, STOREHEADER::lenPOS, STOREHEADER::lenWORD, STOREHEADER::maxpower, STOREHEADER::sFun, STOREHEADER::sInd, STOREHEADER::sSym, STOREHEADER::sVec, and STOREHEADER::wildoffset.
Referenced by SetFileIndex().
ReadSaveHeader()
WORD ReadSaveHeader (void)
Reads the header in the save file and sets function pointers and flags according to the information found there. Must be called before any other ReadSave... function.
Currently works only for the exchange between 32bit and 64bit machines (WORD size must be 2 or 4 bytes)!
It is called by CoLoad().
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 4065 of file store.c.
ReadSaveIndex()
WORD ReadSaveIndex (FILEINDEX * fileind)
Reads a FILEINDEX from the open save file specified by AO.SaveData.Handle. Translations for adjusting endianness and data sizes are done if necessary.
Depends on the assumption that sizeof(FILEINDEX) is the same everywhere. If FILEINDEX or INDEXENTRY change, then this functions has to be adjusted.
Called by CoLoad() and FindInIndex().
Parameters
fileind contains the read FILEINDEX after successful return. must point to allocated, big enough memory.
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 4183 of file store.c.
References INFILEINDEX, FiLeInDeX::next, FiLeInDeX::number, and FuNcTiOn::number.
ReadSaveVariables()
WORD ReadSaveVariables (UBYTE * buffer, UBYTE * top, LONG * size, LONG * outsize, INDEXENTRY * ind, LONG * stage)
Reads the variables from the open file specified by AO.SaveData.Handle. It reads the *size bytes and writes them to the *buffer. It is called by PutInStore().
If translation is necessary, the data might shrink or grow in size, then *size is adjusted so that the reading and writing fits into the memory from the buffer to the top. The actual number of read bytes is returned in *size, the number of written bytes is returned in *outsize.
If the *size is smaller than the actual size of the variables, this function will be called several times and needs to remember the current position in the variable structure. The parameter stage does this job. When ReadSaveVariables() is called for the first time, this parameter should have the value -1.
The parameter ind is used to get the number of variables.
Parameters
buffer read variables are written into this allocated memory
top upper end of allocated memory
size number of bytes to read. might return a smaller number of read bytes if translation was necessary
outsize if translation has be done, outsize contains the number of written bytes
ind pointer of INDEXENTRY for the current expression. read-only
stage should be -1 for the first call, will be increased by ReadSaveVariables to memorize the position in the variable structure
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 4369 of file store.c.
References InDeXeNtRy::nfunctions, InDeXeNtRy::nindices, InDeXeNtRy::nsymbols, InDeXeNtRy::nvectors, and FuNcTiOn::spec.
ReadSaveTerm32()
UBYTE * ReadSaveTerm32 (UBYTE * bin, UBYTE * binend, UBYTE ** bout, UBYTE * boutend, UBYTE * top, int terminbuf)
Reads a single term from the given buffer at bin and write the translated term back to this buffer at bout.
ReadSaveTerm32() is currently the only instantiation of a ReadSaveTerm-function. It only deals with data that already has the correct endianness and that is resized to 32bit words but without being renumbered or translated in any other way. It uses the compress buffer AR.CompressBuffer.
The function is reentrant in order to cope with nested function arguments. It is called by ReadSaveExpression() and itself.
The return value indicates the position in the input buffer up to which the data has already been successfully processed. The parameter bout returns the corresponding position in the output buffer.
Parameters
bin start of the input buffer
binend end of the input buffer
bout as input points to the beginning of the output buffer, as output points behind the already translated data in the output buffer
boutend end of already decompressed data in output buffer
top end of output buffer
terminbuf flag whether decompressed data is already in the output buffer. used in recursive calls
Returns
pointer to the next unprocessed data in the input buffer
Definition at line 4736 of file store.c.
References ReadSaveTerm32().
Referenced by ReadSaveExpression(), and ReadSaveTerm32().
ReadSaveExpression()
WORD ReadSaveExpression (UBYTE * buffer, UBYTE * top, LONG * size, LONG * outsize)
Reads an expression from the open file specified by AO.SaveData.Handle. The endianness flip and a resizing without renumbering is done in this function. Thereafter the buffer consists of chunks with a uniform maximal word size (32bit at the moment). The actual renumbering is then done by calling the function ReadSaveTerm32(). The result is returned in buffer.
If the translation at some point doesn't fit into the buffer anymore, the function returns and must be called again. In any case size returns the number of successfully read bytes, outsize returns the number of successfully written bytes, and the file will be positioned at the next byte after the successfully read data.
It is called by PutInStore().
Parameters
buffer output buffer, holds the (translated) expression
top end of buffer
size number of read bytes
outsize number of written bytes
Returns
= 0 everything okay, != 0 an error occurred
Definition at line 5146 of file store.c.
References ReadSaveTerm32().