FORM: checkpoint.c File Reference
checkpoint.c File Reference
#include "form3.h"
#include <errno.h>
Macros
#define CACHED_SNAPSHOT
#define CACHE_SIZE 4096
#define R_FREE(ARG) if (ARG) M_free(ARG, #ARG);
#define R_FREE_NAMETREE(ARG)
#define R_FREE_STREAM(ARG)
#define R_SET(VAR, TYPE) VAR = *((TYPE*)p); p = (unsigned char*)p + sizeof(TYPE);
#define R_COPY_B(VAR, SIZE, CAST)
#define S_WRITE_B(BUF, LEN) if (fwrite_cached(BUF, 1, LEN, fd) != (size_t)(LEN)) return(__LINE__);
#define S_FLUSH_B if (flush_cache(fd) != 1) return(__LINE__);
#define R_COPY_S(VAR, CAST)
#define S_WRITE_S(STR)
#define R_COPY_LIST(ARG)
#define S_WRITE_LIST(LST)
#define R_COPY_NAMETREE(ARG)
#define S_WRITE_NAMETREE(ARG)
#define S_WRITE_DOLLAR(ARG)
#define ANNOUNCE(str)
Functions
int CheckRecoveryFile ()
void DeleteRecoveryFile ()
char * RecoveryFilename ()
void InitRecovery ()
size_t fwrite_cached (const void *ptr, size_t size, size_t nmemb, FILE *fd)
size_t flush_cache (FILE *fd)
int DoRecovery (int *moduletype)
void DoCheckpoint (int moduletype)
Variables
unsigned char cache_buffer [CACHE_SIZE]
size_t cache_fill = 0
Detailed Description
Contains all functions that deal with the recovery mechanism controlled and activated by the On Checkpoint switch.
The main function are DoCheckpoint, DoRecovery, and DoSnapshot. If the checkpoints are activated DoCheckpoint is called every time a module is finished executing. If the conditions for the creation of a recovery snapshot are met DoCheckpoint calls DoSnapshot. DoRecovery is called once when FORM starts up with the command line argument -R. Most of the other code contains debugging facilities that are only compiled if the macro PRINTDEBUG is defined.
The recovery mechanism is atomic, i.e. only if everything went well, the final recovery file is created (and the older one overwritten) in a single step (copying). If some errors occur, a warning is issued and the program continues without having created a new recovery file. The only situation in which the creation of the recovery data leads to a termination of the running program is if not enough disk or memory space is left.
For ParFORM each slave creates its own recovery file, sends it to the master and then it deletes the recovery file. The master stores all the recovery files and on recovery it feeds these files to the slaves. It is nearly impossible to recover after some MPI fault so ParFORM terminates on any recovery failure.
DoRecovery and DoSnapshot do the loading and saving of the recovery data, respectively. Every change in one functions needs to be accompanied by the appropriate change in the other function. The structure of both functions is quite similar. They handle the relevant global structs one after the other and then care about the copying of the hide and scratch files.
The names of the recovery, scratch and hide files are hard-coded in the variables in fold "filenames and system commands".
If the global structs AM,AP,AC,AR are changed, DoRecovery and DoSnapshot usually also have to be changed. Some structs are read/written as a whole (AP,AC), some are read/written only partly as a selection of their individual elements (AM,AR). If AM or AR have been changed by adding or removing an element that is important for the runtime status, then the reading/writing statements have to be added to or removed from DoRecovery and DoSnapshot. If AP or AC are changed, then for non-pointer variables (in the case of a struct it also means that none of its elements is a pointer) nothing has to be changed in the functions here. If pointers are involved, extra code has to be added (or removed). See the comments of DoRecovery and DoSnapshot.
Definition in file checkpoint.c.
Macro Definition Documentation
CACHED_SNAPSHOT
#define CACHED_SNAPSHOT
Definition at line 1211 of file checkpoint.c.
CACHE_SIZE
#define CACHE_SIZE 4096
Definition at line 1213 of file checkpoint.c.
R_FREE
#define R_FREE (ARG) if (ARG) M_free(ARG, #ARG);
Definition at line 1278 of file checkpoint.c.
R_FREE_NAMETREE
#define R_FREE_NAMETREE (ARG)
Value:
    R_FREE(ARG->namenode); \
    R_FREE(ARG->namebuffer); \
    R_FREE(ARG);
Definition at line 1281 of file checkpoint.c.
R_FREE_STREAM
#define R_FREE_STREAM (ARG)
Value:
    R_FREE(ARG.buffer); \
    R_FREE(ARG.FoldName); \
    R_FREE(ARG.name);
Definition at line 1286 of file checkpoint.c.
R_SET
#define R_SET (VAR, TYPE) VAR = *((TYPE*)p); p = (unsigned char*)p + sizeof(TYPE);
Definition at line 1293 of file checkpoint.c.
R_COPY_B
#define R_COPY_B (VAR, SIZE, CAST)
Value:
    VAR = (CAST)Malloc1(SIZE,#VAR); \
    memcpy(VAR, p, SIZE); p = (unsigned char*)p + SIZE;
Definition at line 1298 of file checkpoint.c.
S_WRITE_B
#define S_WRITE_B (BUF, LEN) if (fwrite_cached(BUF, 1, LEN, fd) != (size_t)(LEN)) return(__LINE__);
Definition at line 1302 of file checkpoint.c.
S_FLUSH_B
#define S_FLUSH_B if (flush_cache(fd) != 1) return(__LINE__);
Definition at line 1305 of file checkpoint.c.
R_COPY_S
#define R_COPY_S (VAR, CAST)
Value:
    if ( VAR ) { \
        VAR = (CAST)Malloc1(strlen(p)+1,"R_COPY_S"); \
        strcpy((char*)VAR, p); p = (unsigned char*)p + strlen(p) + 1; \
    }
Definition at line 1310 of file checkpoint.c.
S_WRITE_S
#define S_WRITE_S (STR)
Value:
    if ( STR ) { \
        l = strlen((char*)STR) + 1; \
        if ( fwrite_cached(STR, 1, l, fd) != (size_t)l ) return(__LINE__); \
    }
Definition at line 1316 of file checkpoint.c.
R_COPY_LIST
#define R_COPY_LIST (ARG)
Value:
    if ( ARG.maxnum ) { \
        R_COPY_B(ARG.lijst, ARG.size*ARG.maxnum, void*) \
    }
Definition at line 1324 of file checkpoint.c.
S_WRITE_LIST
#define S_WRITE_LIST (LST)
Value:
    if ( LST.maxnum ) { \
        S_WRITE_B((char*)LST.lijst, LST.maxnum*LST.size) \
    }
Definition at line 1329 of file checkpoint.c.
R_COPY_NAMETREE
#define R_COPY_NAMETREE (ARG)
Value:
    R_COPY_B(ARG, sizeof(NAMETREE), NAMETREE*); \
    if ( ARG->namenode ) { \
        R_COPY_B(ARG->namenode, ARG->nodesize*sizeof(NAMENODE), NAMENODE*); \
    } \
    if ( ARG->namebuffer ) { \
        R_COPY_B(ARG->namebuffer, ARG->namesize, UBYTE*); \
    }
Definition at line 1336 of file checkpoint.c.
S_WRITE_NAMETREE
#define S_WRITE_NAMETREE (ARG)
Value:
    S_WRITE_B(ARG, sizeof(NAMETREE)); \
    if ( ARG->namenode ) { \
        S_WRITE_B(ARG->namenode, ARG->nodesize*sizeof(struct NaMeNode)); \
    } \
    if ( ARG->namebuffer ) { \
        S_WRITE_B(ARG->namebuffer, ARG->namesize); \
    }
Definition at line 1345 of file checkpoint.c.
S_WRITE_DOLLAR
#define S_WRITE_DOLLAR (ARG)
Value:
    if ( ARG.size && ARG.where && ARG.where != &(AM.dollarzero) ) { \
        S_WRITE_B(ARG.where, ARG.size*sizeof(WORD)) \
    }
Definition at line 1356 of file checkpoint.c.
ANNOUNCE
#define ANNOUNCE (str)
Definition at line 1367 of file checkpoint.c.
Function Documentation
CheckRecoveryFile()
int CheckRecoveryFile ()
Checks whether a snapshot/recovery file exists. Returns 1 if it exists, 0 otherwise.
Definition at line 278 of file checkpoint.c.
References RecoveryFilename().
DeleteRecoveryFile()
void DeleteRecoveryFile ()
Deletes the recovery files. It is called by CleanUp() in the case of a successful completion.
Definition at line 333 of file checkpoint.c.
RecoveryFilename()
char * RecoveryFilename ()
Returns pointer to recovery filename.
Definition at line 364 of file checkpoint.c.
Referenced by CheckRecoveryFile(), and DoRecovery().
InitRecovery()
void InitRecovery ()
Sets up the strings for the filenames of the recovery files. This functions should only be called once to avoid memory leaks and after AM.TempDir has been initialized.
Definition at line 399 of file checkpoint.c.
fwrite_cached()
size_t fwrite_cached (const void * ptr, size_t size, size_t nmemb, FILE * fd)
Definition at line 1219 of file checkpoint.c.
flush_cache()
size_t flush_cache (FILE * fd)
Definition at line 1244 of file checkpoint.c.
DoRecovery()
int DoRecovery (int * moduletype)
Reads from the recovery file and restores all necessary variables and states in FORM, so that the execution can recommence in preprocessor() as if no restart of FORM had occurred.
The recovery file is read into memory as a whole. The pointer p then points into this memory at the next non-processed data. The macros by which variables are restored, like R_SET, automatically increase p appropriately.
If something goes wrong, the function returns with a non-zero value.
Allocated memory that would be lost when overwriting the global structs with data from the file is freed first. A major part of the code deals with the restoration of pointers. The idiom we use is to memorize the original pointer value (org), allocate new memory and copy the data from the file into this memory, calculate the offset between the old pointer value and the new allocated memory position (ofs), and then correct all affected pointers (+=ofs).
We rely on the fact that several variables (especially in AM) are already assigned the correct values by the startup functions. That means, in principle, that a change in the setup files between snapshot creation and recovery will be noticed.
Definition at line 1399 of file checkpoint.c.
References TaBlEs::argtail, TaBlEs::boomlijst, BrAcKeTiNfO::bracketbuffer, TaBlEs::buffers, TaBlEs::bufferssize, CopyFile(), TaBlEs::flags, ReNuMbEr::func, ReNuMbEr::funnum, VaRrEnUm::hi, BrAcKeTiNfO::indexbuffer, ReNuMbEr::indi, ReNuMbEr::indnum, VaRrEnUm::lo, TaBlEs::MaxTreeSize, TaBlEs::mm, TaBlEs::numind, TaBlEs::pattern, TaBlEs::prototype, TaBlEs::prototypeSize, RecoveryFilename(), ExPrEsSiOn::renumlists, TaBlEs::reserved, TaBlEs::spare, TaBlEs::sparse, VaRrEnUm::start, ReNuMbEr::symb, ReNuMbEr::symnum, TaBlEs::tablepointers, TimeWallClock(), TaBlEs::totind, ReNuMbEr::vecnum, and ReNuMbEr::vect.
DoCheckpoint()
void DoCheckpoint (int moduletype)
Checks whether a snapshot should be done. Calls DoSnapshot() to create the snapshot.
Definition at line 3102 of file checkpoint.c.
References PF_BroadcastNumber(), PF_RecvFile(), PF_SendFile(), and TimeWallClock().
Variable Documentation
cache_buffer
unsigned char cache_buffer[CACHE_SIZE]
Definition at line 1216 of file checkpoint.c.
cache_fill
size_t cache_fill = 0
Definition at line 1217 of file checkpoint.c.